#!/usr/bin/env python3
"""translation_coverage.py - before/after coverage table for the Aug-21 import (Wave 5).

    python automation/translation_coverage.py --before automation/aug21_coverage_baseline.json --out TRANSLATION-STATUS-2026-08-27.md

Run from deliverables/CSPro/.

Before = the per-locale % each wave recorded before its import (the patch notes' own
"before" rows: F1 Task 16, F2 m3, F4 pre-wave 3.1.4, F3 wave-4a). After = measured NOW:

  * F1/F3/F4 by calling the generator's build_*() and running apply_translations() on the
    result, then parsing the summary line cspro_helpers.py prints. NO files are written -
    build_*() is called directly (never migrate_maps_namekeys.capture_source_dict, which
    rewrites the .dcf as a side effect) and write_dcf() is never reached.
  * F2 by running deliverables/F2/PWA/app/scripts/f2-coverage.py, the single source for the
    F2 denominator (pre-flight ruling T22/T44). f2_label_coverage() below re-implements its
    two regexes so the counting is unit-testable on a fixture; test_translation_coverage.py
    fails if the two ever disagree on the real items.ts.

The generated block is written between HTML markers, so re-running the tool refreshes the
measured numbers in place and leaves the hand-written sections of the status doc alone.
"""
import argparse
import contextlib
import importlib
import io
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSPRO = HERE.parent
REPO = CSPRO.parents[1]
sys.path.insert(0, str(CSPRO))
LINE = re.compile(r"^\s*([A-Z]{3}): (\d+)/(\d+) labels translated \((\d+)%\)", re.M)
BUILDERS = {"F1": "build_dictionary", "F3": "build_f3_dictionary", "F4": "build_f4_dictionary"}
F2_APP = REPO / "deliverables" / "F2" / "PWA" / "app"
F2_ITEMS = F2_APP / "src" / "generated" / "items.ts"
F2_SCRIPT = F2_APP / "scripts" / "f2-coverage.py"
F2_LOCS = ["fil", "ceb", "bis", "ilo", "hil", "war", "bcl"]   # f2-coverage.py's own order
CSPRO_LOCS = ["FIL", "BCL", "BIS", "CEB", "WAR", "HIL", "ILO"]  # TRANSLATION_LANGUAGES order
BEGIN = "<!-- BEGIN generated by automation/translation_coverage.py -->"
END = "<!-- END generated by automation/translation_coverage.py -->"


def parse_generator_summary(text):
    """-> {CODE: (matched, total, pct)} from apply_translations()' printed summary."""
    return {m.group(1): (int(m.group(2)), int(m.group(3)), int(m.group(4)))
            for m in LINE.finditer(text)}


def f2_label_coverage(items_ts_path):
    """-> (label objects, {locale: n carrying a string}). Regexes: f2-coverage.py."""
    s = Path(items_ts_path).read_text(encoding="utf-8")
    total = len(re.findall(r"\ben: '", s))
    return total, {l: len(re.findall(r"\b" + l + r": '", s)) for l in F2_LOCS}


def f2_from_script():
    """Same tuple, straight out of deliverables/F2/PWA/app/scripts/f2-coverage.py."""
    out = subprocess.run([sys.executable, str(F2_SCRIPT)], capture_output=True, text=True,
                         encoding="utf-8", check=True).stdout
    total = int(re.search(r"label objects: (\d+)", out).group(1))
    counts = dict(re.findall(r"\b([a-z]{3})(\d+)\b(?!%)", out.splitlines()[1]))
    return total, {l: int(counts[l]) for l in F2_LOCS}


def cspro_after(inst):
    """Run apply_translations on the generator's pre-apply dict -> {CODE: (m, t, pct)}.

    Superset of the brief's `{CODE: pct}`: the counts are what the status doc's
    denominators and the patch notes' tables are stated in, so they must not be re-derived.
    """
    from cspro_helpers import apply_translations
    sys.path.insert(0, str(CSPRO / inst))
    sys.modules.pop("generate_dcf", None)
    try:
        gen = importlib.import_module("generate_dcf")
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            apply_translations(getattr(gen, BUILDERS[inst])(), CSPRO / inst / "translations")
    finally:
        sys.path.remove(str(CSPRO / inst))
        sys.modules.pop("generate_dcf", None)
    return parse_generator_summary(buf.getvalue())


def render_table(before, after):
    rows = ["| instrument | locale | before | after | delta |", "|---|---|---|---|---|"]
    for inst in sorted(set(before) | set(after)):
        for loc in sorted(set(before.get(inst, {})) | set(after.get(inst, {}))):
            b, a = before.get(inst, {}).get(loc), after.get(inst, {}).get(loc)
            d = f"{a - b:+d}" if (a is not None and b is not None) else ""
            rows.append(f"| {inst} | {loc} | {'' if b is None else str(b) + '%'} | "
                        f"{'' if a is None else str(a) + '%'} | {d} |")
    return "\n".join(rows)


def splice(existing, block):
    """Replace the generated block in `existing`, or return the block alone."""
    if existing and BEGIN in existing and END in existing:
        head, rest = existing.split(BEGIN, 1)
        return head + block + rest.split(END, 1)[1]
    return block


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--before", required=True, help="baseline JSON: {inst: {locale: pct}}")
    ap.add_argument("--out", required=True, help="status markdown to write/refresh")
    a = ap.parse_args(argv)
    before = json.loads(Path(a.before).read_text(encoding="utf-8"))
    before.pop("_readme", None)
    counts = {inst: cspro_after(inst) for inst in BUILDERS}
    after = {inst: {c: pct for c, (_m, _t, pct) in per.items()} for inst, per in counts.items()}
    total, per_loc = f2_from_script()
    after["F2"] = {l: round(100 * n / total) for l, n in per_loc.items()}

    for inst, per in counts.items():
        if not per:
            raise SystemExit(f"{inst}: apply_translations printed no coverage line - "
                             f"are the maps missing from {CSPRO / inst / 'translations'}?")

    import icf_content   # CLI-only: the two layers outside the dictionary
    import notes_lookup
    lines = [BEGIN, "",
             "Coverage = keys present in the translation map (label nodes for F1/F3/F4; "
             f"label objects, {total} of them, for F2). It measures presence, not linguistic "
             "quality - the translator worklist lists what is still English and why.", "",
             "`before` = the row each wave's patch note records for the build it replaced; "
             "`after` = measured by re-running this tool's sources on today's tree "
             "(F1/F3/F4: `generate_dcf.py`'s own summary line, percentage truncated; "
             "F2: `deliverables/F2/PWA/app/scripts/f2-coverage.py`, percentage rounded).", "",
             render_table(before, after), "", "### Measured counts (`after`)", ""]
    for inst in sorted(counts):
        t = next(iter(counts[inst].values()))[1]
        lines.append(f"- **{inst}** - of {t} label nodes: "
                     + ", ".join(f"{c} {m}" for c, (m, _t, _p) in counts[inst].items()))
    notes, icf = notes_lookup.coverage(), icf_content.coverage()
    lines += [f"- **F2** - of {total} label objects: "
              + ", ".join(f"{l} {per_loc[l]}" for l in F2_LOCS), "",
              "Two layers outside the dictionary, counted by their own modules:", "",
              "- **Enumerator notes** (`notes_lookup.coverage`) - translated notes on file: "
              + ", ".join(f"{c} {notes.get(c, 0)}" for c in CSPRO_LOCS),
              "- **ICF consent paragraphs** (`icf_content.coverage`) - differing from "
              "English / recorded: "
              + ", ".join(f"{c} {icf[c]['differs']}/{icf[c]['stored']}" for c in CSPRO_LOCS),
              "", END]
    block = "\n".join(lines)
    out = Path(a.out)
    text = splice(out.read_text(encoding="utf-8") if out.exists() else "", block)
    out.write_text(text if text.endswith("\n") else text + "\n",
                   encoding="utf-8", newline="\n")
    print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
