"""ent_template.py — canonical CSPro 8.0 .ent property block.

Source-of-truth: the working F1 .ent at
deliverables/CSPro/F1/FacilityHeadSurvey.ent (Carl's hand-laid Designer
output that opens cleanly in CSPro 8.0).

Use:
    from shared.ent_template import canonical_logic_settings, canonical_properties

    ENT = {
        "software": "CSPro", "version": 8.0, "fileType": "application", "type": "entry",
        "name": "...", "label": "...",
        "dictionaries": [...],
        "forms": [...],
        "questionText": [...],
        "code": [...],
        "messages": [...],
        "logicSettings": canonical_logic_settings(),
        "properties":    canonical_properties(),
        "userSettings": [...],   # spliced by env_loader at build time
    }
"""


# Canonical .ent.qsf body (YAML) — empty styles + zero questions; matches CSPro 8.0
# Designer's default output. The leading BOM is required.
QSF_TEMPLATE = "﻿---\nfileType: Question Text\nversion: CSPro 8.0\nlanguages:\n  - name: EN\n    label: English\nstyles:\n  - name: Normal\n    className: normal\n    css: |\n      font-family: Arial;font-size: 16px;\n  - name: Instruction\n    className: instruction\n    css: |\n      font-family: Arial;font-size: 14px;color: #0000FF;\n  - name: Heading 1\n    className: heading1\n    css: |\n      font-family: Arial;font-size: 36px;\n  - name: Heading 2\n    className: heading2\n    css: |\n      font-family: Arial;font-size: 24px;\n  - name: Heading 3\n    className: heading3\n    css: |\n      font-family: Arial;font-size: 18px;\nquestions:\n  []\n...\n"


def mgf_template(app_label: str) -> str:
    """Canonical .ent.mgf body — single-line CSPro-style comment; BOM-prefixed."""
    return f"﻿{{ Application '{app_label}' message file generated by CSPro }}\n"


def canonical_logic_settings() -> dict:
    return {
        "version": 2.0,
        "caseSensitive": {"symbols": False},
        "actionInvoker": {
            "accessFromExternalCaller": "promptIfNoValidAccessToken",
            "convertResultsForLogic": True,
        },
    }


def canonical_properties() -> dict:
    return {
        "askOperatorId": False,
        "autoAdvanceOnSelection": False,
        "caseTree": "mobileOnly",
        "centerForms": False,
        "createListing": False,
        "createLog": False,
        "decimalMark": "dot",
        "displayCodesAlongsideLabels": False,
        "notes": {"delete": "all", "edit": "all"},
        "partialSave": {"operatorEnabled": True},
        "showEndCaseMessage": True,
        "showOnlyDiscreteValuesInComboBoxes": True,
        "showFieldLabels": True,
        "showErrorMessageNumbers": False,
        "showQuestionText": True,
        "showRefusals": True,
        "verify": {"frequency": 1, "start": 1},
        "htmlDialogs": True,
        "paradata": {
            "collection": "all",
            "recordCoordinates": False,
            "recordInitialPropertyValues": False,
            "recordIteratorLoadCases": False,
            "recordValues": False,
            "deviceStateIntervalMinutes": 5,
        },
        "useHtmlComponentsInsteadOfNativeVersions": False,
    }
