#!/usr/bin/env tsx
// deliverables/F2/PWA/app/scripts/dump-english-strings.ts
/**
 * Dump the exact English strings applyTranslations() localizes, for the paper
 * extractor (deliverables/CSPro/data/translations-official/anchor_extract_f2.py).
 * Invoke: `npm run dump:english`  ->  spec/english-strings.json
 * Output is deterministic (no timestamp): it changes only when F2-Spec.md changes.
 * generated by npm run dump:english - never hand-edit spec/english-strings.json
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { collectEnglishStrings } from './lib/english-strings';
import { parseSpec } from './lib/parse-spec';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const APP_ROOT = resolve(__dirname, '..');
const SPEC_PATH = resolve(APP_ROOT, 'spec/F2-Spec.md');
const OUT_PATH = resolve(APP_ROOT, 'spec/english-strings.json');

const strings = collectEnglishStrings(parseSpec(readFileSync(SPEC_PATH, 'utf-8')));
const payload = {
  source: 'spec/F2-Spec.md',
  count: strings.length,
  strings,
  _generated_by: 'npm run dump:english - never hand-edit',
};
writeFileSync(OUT_PATH, JSON.stringify(payload, null, 1) + '\n', 'utf-8');
console.log(`dump-english-strings: ${strings.length} unique English strings -> ${OUT_PATH}`);
