"""
Self-host Verde Manual fonts: fetch Bunny-already-subsetted woff2 files
for `latin` + `latin-ext` per weight, save under public/fonts/<family>/,
and write a local fonts.css that references them with relative paths.

Skips `vietnamese` subset - F2 PWA renders en + fil only.

Run: `py -3 scripts/self_host_fonts.py`

Re-runnable. Existing files are overwritten.

Closes GH #162 (E3-F2-PWA-DESIGN-004).
"""
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
PUBLIC_FONTS_DIR = HERE.parent / "public" / "fonts"

SOURCE_CSS_URL = (
    "https://fonts.bunny.net/css?"
    "family=newsreader:400,500,600,700"
    "|public-sans:400,500,600,700"
    "|jetbrains-mono:400,500,600"
    "&display=swap"
)

KEEP_SUBSETS = {"latin", "latin-ext"}

FAMILY_TO_DIR = {
    "Newsreader": "newsreader",
    "Public Sans": "public-sans",
    "JetBrains Mono": "jetbrains-mono",
}

UA = "Mozilla/5.0 self-host-fonts/1.0"


def http_get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_bunny_css(css: str):
    blocks = []
    pattern = re.compile(
        r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{([^}]+)\}",
        re.MULTILINE,
    )
    for m in pattern.finditer(css):
        subset = m.group(1)
        body = m.group(2)
        family = re.search(r"font-family:\s*'([^']+)'", body)
        weight = re.search(r"font-weight:\s*(\d+)", body)
        woff2 = re.search(
            r"url\((https://fonts\.bunny\.net/[^)]+\.woff2)\)", body
        )
        urange = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (family and weight and woff2 and urange):
            continue
        blocks.append(
            {
                "subset": subset,
                "family": family.group(1),
                "weight": weight.group(1),
                "woff2_url": woff2.group(1),
                "unicode_range": urange.group(1),
            }
        )
    return blocks


def main():
    print(f"Fetching font CSS from {SOURCE_CSS_URL}")
    css_bytes = http_get(SOURCE_CSS_URL)
    css = css_bytes.decode("utf-8")
    blocks = parse_bunny_css(css)
    print(f"Parsed {len(blocks)} @font-face blocks")

    kept = [b for b in blocks if b["subset"] in KEEP_SUBSETS]
    dropped = len(blocks) - len(kept)
    print(
        f"Keeping {len(kept)} blocks (subsets: {sorted(KEEP_SUBSETS)}); "
        f"dropping {dropped}"
    )

    for d in FAMILY_TO_DIR.values():
        (PUBLIC_FONTS_DIR / d).mkdir(parents=True, exist_ok=True)

    local_blocks = []
    total_bytes = 0

    for b in kept:
        d = FAMILY_TO_DIR.get(b["family"])
        if not d:
            print(f"  No directory mapping for family {b['family']!r}, skipping")
            continue
        filename = b["woff2_url"].rsplit("/", 1)[-1]
        local_path = PUBLIC_FONTS_DIR / d / filename
        rel_path = f"/fonts/{d}/{filename}"
        buf = http_get(b["woff2_url"])
        local_path.write_bytes(buf)
        total_bytes += len(buf)
        print(
            f"  {b['family']:<15} {b['weight']} {b['subset']:<10}"
            f" -> {filename} ({len(buf)} bytes)"
        )
        local_blocks.append({**b, "rel_path": rel_path})

    css_lines = [
        "/*",
        " * F2 PWA - Verde Manual fonts (self-hosted).",
        " *",
        " * Generated by scripts/self_host_fonts.py from Bunny Fonts CSS.",
        " * Subsets: latin + latin-ext (Vietnamese skipped - F2 PWA renders en + fil only).",
        " * Re-generate: py -3 scripts/self_host_fonts.py",
        " *",
        " * Closes GH #162 (E3-F2-PWA-DESIGN-004).",
        " */",
        "",
    ]
    for b in local_blocks:
        css_lines.append(f"/* {b['family']} {b['weight']} {b['subset']} */")
        css_lines.append("@font-face {")
        css_lines.append(f"  font-family: '{b['family']}';")
        css_lines.append("  font-style: normal;")
        css_lines.append(f"  font-weight: {b['weight']};")
        css_lines.append("  font-display: swap;")
        css_lines.append(f"  src: url({b['rel_path']}) format('woff2');")
        css_lines.append(f"  unicode-range: {b['unicode_range']};")
        css_lines.append("}")
        css_lines.append("")

    css_out = PUBLIC_FONTS_DIR / "fonts.css"
    css_out.write_text("\n".join(css_lines), encoding="utf-8")
    print(f"\nWrote {css_out} ({css_out.stat().st_size} bytes)")
    print(
        f"Total font payload: {total_bytes / 1024:.1f} KB"
        f" across {len(local_blocks)} files"
    )


if __name__ == "__main__":
    sys.exit(main() or 0)
