"""generate_apc.py — emit sync_F1_app.ent.apc.

E3-F1-088 Fix B1: F1's primary dict is declared as external in this app's
.ent, so syncdata(PUT, FACILITYHEADSURVEY_DICT) resolves against an EXTERNAL
dictionary reference — which is what the CSPro 8.0 syncdata function requires.
The polymorphic `dictname` parameter pattern is also used (belt and suspenders).

The level preproc runs the sync immediately, then endlevel exits the entry
app. menu_app.pff sets OnExit=menu_app.pff so control returns to the menu.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'UHC Sync F1' logic file generated by CSPro }
{ Fix B1 (E3-F1-088): F1 dict is external (see .ent); syncdata(PUT, dict) is
  legal because the dict reference resolves to an EXTERNAL dictionary in this
  app's namespace. Dict is also passed as a `dictname` parameter for the
  polymorphic dispatch pattern documented in CSPro 8.0 reference syntax. }

PROC GLOBAL

config string csweb_url;        { spliced by build_all.py from urls.yaml }


function push_to_server(dictname dict)
   if syncconnect(CSWeb, csweb_url) then
      syncdata(PUT, dict);
      syncdisconnect();
   else
      errmsg("Cannot reach sync server. Cases held locally; will retry on next sync.");
   endif;
end;


PROC SYNC_LEVEL
preproc
   push_to_server(FACILITYHEADSURVEY_DICT);
   endlevel;        { exit immediately — OnExit chains back to menu_app.pff }
'''

(HERE / "sync_F1_app.ent.apc").write_text(APC, encoding="utf-8")
print(f"wrote sync_F1_app.ent.apc ({len(APC)} chars; preproc sync + endlevel)")
