"""generate_apc.py — emit sync_F1_app.ent.apc.

E3-F1-088 Fix B1 (v2): F1's primary dict is declared as external in this
app's .ent, so syncdata(PUT, FACILITYHEADSURVEY_DICT) resolves against an
EXTERNAL dictionary reference — which is what the CSPro 8.0 syncdata function
requires.

v2 NOTE: the earlier polymorphic `dictname` parameter pattern (legacy
Sync-Helpers.apc idiom) does NOT compile in CSPro 8.0 Designer — the
compiler emits "'dict' is not a declared variable" at the parameter
declaration line. So we inline the syncdata call directly; no user-defined
function. F1 dict reference works because of the external declaration.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'UHC Sync F1' logic file generated by CSPro }
{ Fix B1 v2 (E3-F1-088): F1 dict declared external in .ent; direct reference
  to FACILITYHEADSURVEY_DICT is legal because it resolves as EXTERNAL in this
  app's namespace. Inline syncdata call (no user-defined function — CSPro 8.0
  doesn't accept the `dictname` parameter type from older Khurshid pattern). }

PROC GLOBAL

config string csweb_url;        { spliced by build_all.py from urls.yaml }


PROC SYNC_LEVEL
preproc
   if syncconnect(CSWeb, csweb_url) then
      syncdata(PUT, FACILITYHEADSURVEY_DICT);
      syncdisconnect();
   else
      errmsg("Cannot reach sync server. Cases held locally; will retry on next sync.");
   endif;
   endlevel;        { exit immediately — OnExit chains back to menu_app.pff }
'''

(HERE / "sync_F1_app.ent.apc").write_text(APC, encoding="utf-8")
print(f"wrote sync_F1_app.ent.apc ({len(APC)} chars; inline syncdata, no dictname param)")
