"""generate_apc.py — emit sync_F1_app.ent.apc.

E3-F1-088 Fix B1 (v3): F1's primary dict is declared as external in this
app's .ent, AND we bind it at runtime to F1.csdb (CSPro DB format, sync-
capable) using setfile(). Without setfile, CSPro defaults to a flat .dat
datasource and syncdata fails with "The datasource to FACILITYHEADSURVEY_DICT
does not support the sync features used in the program."

v3 history:
- v1 used a `dictname dict` polymorphic parameter → Designer rejected it
  ("'dict' is not a declared variable") because that idiom isn't valid in
  CSPro 8.0.
- v2 dropped the parameter, inlined syncdata directly → compiled clean, but
  at runtime syncdata complained the F1 datasource didn't support sync.
- v3 adds setfile() to bind FACILITYHEADSURVEY_DICT to F1.csdb so syncdata
  sees a CSDB-format datasource.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'UHC Sync F1' logic file generated by CSPro }
{ Fix B1 v3 (E3-F1-088): F1 dict declared external in .ent; bound at runtime
  to F1.csdb via setfile() so syncdata sees a CSDB-format (sync-capable)
  datasource. Without the setfile, syncdata fails with "datasource ... does
  not support sync features used in the program." }

PROC GLOBAL

config string csweb_url;        { spliced by build_all.py from urls.yaml }


PROC SYNC_LEVEL
preproc
   setfile(FACILITYHEADSURVEY_DICT, "..\107_F1\F1.csdb");
   if syncconnect(CSWeb, csweb_url) then
      syncdata(PUT, FACILITYHEADSURVEY_DICT);
      syncdisconnect();
   else
      errmsg("Cannot reach sync server. Cases held locally; will retry on next sync.");
   endif;
   endlevel;        { exit immediately — OnExit chains back to menu_app.pff }
'''

(HERE / "sync_F1_app.ent.apc").write_text(APC, encoding="utf-8")
print(f"wrote sync_F1_app.ent.apc ({len(APC)} chars; setfile binds F1.csdb)")
