# -*- coding: utf-8 -*-
"""Unit tests for the shared shell. Plain script, stdlib only.

    python test_portal_shell.py      # exit 0 = all pass

Same conventions as auth/test_acl.php: a check() helper, a running count, and
a non-zero exit on any failure. No pytest — the box generators have no
third-party deps and neither do their tests.
"""
import sys
import portal_shell as PS

_pass = 0
_fail = 0


def check(what, got, want):
    global _pass, _fail
    if got == want:
        _pass += 1
        return
    _fail += 1
    print("FAIL  %-52s got=%r want=%r" % (what, got, want))


def contains(what, haystack, needle):
    check(what, needle in haystack, True)


def missing(what, haystack, needle):
    check(what, needle in haystack, False)


# --- css mode --------------------------------------------------------------
h_inline = PS.head("T", css="inline")
h_link = PS.head("T", css="link")
contains("inline mode emits a style block", h_inline, "<style>")
missing("inline mode has no stylesheet link", h_inline, 'rel="stylesheet"')
contains("link mode emits the stylesheet", h_link, '<link rel="stylesheet" href="/portal.css">')
missing("link mode inlines no tokens", h_link, "--verde")
check("inline is the default", PS.head("T"), h_inline)

# --- nav permission model --------------------------------------------------
check("monitoring needs monitoring.view", PS.NAV_PERMS.get(PS.P + "/monitoring/"), "monitoring.view")
check("data needs data.export", PS.NAV_PERMS.get(PS.P + "/data/"), "data.export")
check("tabulations needs tabulations.view", PS.NAV_PERMS.get(PS.P + "/tabulations/"), "tabulations.view")
# Deliberately still /docs/admin/: the portal URL for admin only starts working
# in Slice 5 (nginx proxy), and a nav link must never point at a 404. The flip
# to P + "/admin/" happens in the same task that creates the proxy.
check("admin needs admin.system", PS.NAV_PERMS.get("/docs/admin/"), "admin.system")
check("overview needs nothing", PS.NAV_PERMS.get(PS.P + "/"), None)

side = PS.sidebar(PS.P + "/monitoring/")
contains("permissioned entry carries data-perm", side, 'data-perm="monitoring.view"')
missing("unpermissioned entry carries none", side,
        '<a class="" href="/projects/uhc-y2/guides/" data-perm')
contains("active entry is marked", side, 'class="on" href="/projects/uhc-y2/monitoring/"')
missing("the decorative padlock is gone", side, '<span class="lk">')

# --- the lock pill is gone, dimming replaces it ----------------------------
check("PILL_LOCK is removed", hasattr(PS, "PILL_LOCK"), False)
contains("PILL_LIVE survives", PS.PILL_LIVE, "Fieldwork live")
contains("dim script reads the session", PS.PERM_DIM_JS, "/docs/idp/me")
contains("dim script keys off data-perm", PS.PERM_DIM_JS, "data-perm")
contains("dim css ships with the tokens", PS.tokens_css(), ".sb-nav a.sb-off")
contains("close_shell ships the dim script", PS.close_shell(), "data-perm")
# me.php returns a FLAT object -- {signed_in, user, perms, tier, logout} --
# NOT the {ok,data} envelope the admin API uses. Reading d.data here would
# silently blank the chip on every page (each fetch ends in an empty .catch()).
contains("signout uses the idp endpoint", PS.SIGNOUT_JS, "/docs/idp/me")
contains("signout reads the flat shape", PS.SIGNOUT_JS, "d.signed_in")
missing("signout never reads an envelope", PS.SIGNOUT_JS, "d.data")
contains("dim script reads the flat perms", PS.PERM_DIM_JS, "d.perms")
contains("signout links the idp logout", PS.SIGNOUT_JS, "/docs/idp/logout")
missing("no legacy whoami", PS.SIGNOUT_JS, "whoami.php")
missing("no legacy logout", PS.SIGNOUT_JS, "/docs/auth/logout")

# --- generated php partial -------------------------------------------------
import os
import tempfile

_tmp = os.path.join(tempfile.gettempdir(), "capi-shell-test.php")
_n = PS.emit_php_partial(_tmp)
with open(_tmp, encoding="utf-8") as _fh:
    _php = _fh.read()

check("emit reports the byte count", _n, len(_php.encode("utf-8")))
contains("partial opens with a php tag", _php[:5], "<?php")
contains("partial warns against editing", _php, "GENERATED by portal_shell.py")
contains("partial defines the open helper", _php, "function capi_shell_open(")
contains("partial defines the close helper", _php, "function capi_shell_close(")
contains("partial carries the real sidebar", _php, 'class="sb-brand"')
# Active entry matches the CURRENT admin href; both flip together in Slice 5.
contains("partial marks admin active", _php, 'class="on" href="/docs/admin/"')
contains("partial links the stylesheet, never inlines", _php, 'href="/portal.css"')
missing("nowdoc terminator never collides", _php, "\nCAPIHTML;\nCAPIHTML;")
os.unlink(_tmp)

print("%d passed, %d failed" % (_pass, _fail))
sys.exit(1 if _fail else 0)
