#!/usr/bin/env python3
"""
F3 Patient Survey — CAPI logic (.ent.apc) generator.

Emits `PatientSurvey.ent.apc` from the reviewed spec
(`F3-Skip-Logic-and-Validations.md`). Same pattern as F1's generate_apc.py:
generator-over-hand-edit, helpers via #include, dcf-driven other-specify.

Covers (generator side): #164 Outpatient/Inpatient branching (PATIENT_TYPE gates
Section G vs H, both flow to I), consent terminator, PSGC cascade (facility +
patient P_* set), GPS + verification photo, F1 linkage, the G/H/I skip logic,
and UHC9 'Other (specify)' enforcement.

  ⚠️  UNVERIFIED until compiled in CSPro Designer + run in CSEntry (no CSPro
      toolchain here). First Designer compile is the real test; fix any item-name
      / option-code mismatch at the source tables. Skip logic for Sections A–F
      and J–L + section-specific validations are a follow-up pass (see TODO).

Invoke:  python generate_apc.py
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from cspro_helpers import (
    other_specify_procs, select_all_validation_procs,
    range_check_proc, amount_required_procs,
)

# Per-item numeric range checks (spec §3.6/§3.9/§3.10/§3.13). (field, lo, hi, soft_over)
# Q106_DAYS is handled in CUSTOM_VALIDATION (range + pair-sanity together).
RANGE_CHECKS = [
    ("Q58_WAIT_DAYS",         0, 365,       None),
    ("Q58_WAIT_MINUTES",      0, 1440,      None),
    ("Q69_USUAL_TRAVEL_HH",   0, 24,        None),
    ("Q69_USUAL_TRAVEL_MM",   0, 59,        None),
    ("Q72_NEAREST_TRAVEL_HH", 0, 24,        None),
    ("Q72_NEAREST_TRAVEL_MM", 0, 59,        None),
    ("Q97_FINAL_AMOUNT",      0, 99999999,  None),
    ("Q106_NIGHTS",           0, 365,       90),
    ("Q115_FINAL_CASH",       0, 999999999, None),
    ("Q150_TRAVEL_HH",        0, 24,        None),
    ("Q150_TRAVEL_MM",        0, 59,        None),
]

# Cross-field / pair-sanity validations that need a custom body (spec §3.10/§3.1).
CUSTOM_VALIDATION = [
    ("Q106_DAYS",
     "PROC Q106_DAYS\npostproc\n"
     "  if Q106_DAYS < 0 or Q106_DAYS > 365 then\n"
     "    errmsg(\"Q106_DAYS must be between 0 and 365.\");\n    reenter;\n  endif;\n"
     "  if Q106_DAYS > 90 then\n"
     "    errmsg(\"Length of stay (%d days) is unusually long — confirm.\", Q106_DAYS);\n  endif;\n"
     "  if Q106_NIGHTS + Q106_DAYS < 1 then\n"
     "    errmsg(\"A confinement must be at least 1 day (nights + days).\");\n    reenter;\n  endif;"),
    ("DATE_FINAL_VISIT",
     "PROC DATE_FINAL_VISIT\npostproc\n"
     "  if DATE_FINAL_VISIT < DATE_FIRST_VISITED then\n"
     "    errmsg(\"Final-visit date cannot be earlier than the first-visit date.\");\n    reenter;\n  endif;"),
]

HERE = Path(__file__).parent
OUT = HERE / "PatientSurvey.ent.apc"
DCF = HERE / "PatientSurvey.dcf"

SHARED_DIR = HERE.parent / "shared"


def _inline_shared(filename):
    """Return a shared helper module's body with its own 'PROC GLOBAL' header
    stripped, for pasting INSIDE the host's single PROC GLOBAL.

    Why inline instead of #include (verified 2026-06-08 against the CSEntry loader):
    CSPro forbids `#include` inside a PROC, and CSEntry forbids any code before the
    first PROC -- so an #include of a function library satisfies neither (before
    PROC GLOBAL => "code before the first PROC"; after => "#include is not valid").
    Inlining the helper functions into PROC GLOBAL is the only arrangement both the
    Designer compiler and the CSEntry runtime loader accept.
    """
    text = (SHARED_DIR / filename).read_text(encoding="utf-8")
    body, seen_global = [], False
    for ln in text.splitlines():
        if not seen_global:
            if ln.strip() == "PROC GLOBAL":
                seen_global = True
            continue
        body.append(ln)
    if not seen_global:
        raise RuntimeError(f"{filename}: expected a 'PROC GLOBAL' line to strip")
    return "\n".join(body).strip("\n")


HEADER = """\
{ ============================================================================
  PatientSurvey (F3) — CAPI logic   (AUTOGENERATED by generate_apc.py)
  Do NOT hand-edit: edit generate_apc.py's tables and rerun.
  Spec: F3-Skip-Logic-and-Validations.md (reviewed 2026-04-21).
  ============================================================================ }

PROC GLOBAL
numeric currentYYYYMMDD;
numeric currentYear;
numeric currentMonth;

{ Shared helpers inlined into this single PROC GLOBAL (PSGC-Cascade first so its
  ROOT_PSGC_PARENT declaration precedes all functions). #include can't be used:
  CSPro forbids it inside a PROC, and CSEntry forbids code before the first PROC.
  Requires the 4 PSGC external dicts attached to the .ent (else R_PARENT_CODE etc.
  are undeclared). }
""" + _inline_shared("PSGC-Cascade.apc") + """

""" + _inline_shared("Capture-Helpers.apc") + """

PROC PATIENTSURVEY_FF
preproc
  currentYYYYMMDD = sysdate("YYYYMMDD");
  currentYear  = int(currentYYYYMMDD / 10000);
  currentMonth = int(currentYYYYMMDD / 100) % 100;

{ LANGUAGE_USED lives in the FIELD_CONTROL record, so it can't be set from the
  form-file/level preproc ("belongs to a record at a lower level"), and a record
  symbol can't have a PROC. Set it in the preproc of the first FIELD_CONTROL field
  (SURVEY_CODE) — same record, runs at case start. §15.E }
PROC SURVEY_CODE
preproc
  LANGUAGE_USED = getlanguage();
"""

CONTROL_PROCS = """\
{ ---- Informed consent: No (2) terminates the interview (spec 4.2) ---- }
PROC CONSENT_GIVEN
postproc
  if CONSENT_GIVEN = 2 then
    ENUM_RESULT_FIRST_VISIT = 4;   { Withdraw Participation/Consent }
    errmsg("Respondent declined consent. Interview ends; case coded Refused.");
    endlevel;   { end the CASE on refusal (endgroup only skips this group). The case key
                  is now captured on FORM000 before consent, so the refused case saves. }
  endif;

{ ---- F1 linkage: facility is intrinsic to the 12-digit case-key id-block
  (REGION_CODE + PROVINCE_HUC_CODE + CITY_MUNICIPALITY_CODE + FACILITY_NO);
  F3_FACILITY_ID retired 2026-06-04. The cross-check against the synced F1
  facility set moves to the CSWeb sync step (E4-CSWeb-005). ---- }

{ ---- PSGC cascade — facility geo-ID (spec 4.3) ---- }
PROC REGION
onfocus
  FillRegionValueSet();
PROC PROVINCE_HUC
onfocus
  FillProvinceValueSet(REGION);
PROC CITY_MUNICIPALITY
onfocus
  FillCityValueSet(PROVINCE_HUC);
PROC BARANGAY
onfocus
  FillBarangayValueSet(CITY_MUNICIPALITY);

{ ---- PSGC cascade — patient geo-ID (P_* mirror) ---- }
{ patient-home geo cascade — inlined (P_* fields are F3-only; the shared
  PSGC-Cascade functions target the facility geo items REGION/PROVINCE_HUC/etc.,
  and setvalueset needs the literal field, so the P_* targets are set here). }
PROC P_REGION
onfocus
  R_PARENT_CODE = ROOT_PSGC_PARENT;
  if loadcase(PSGC_REGION_DICT, R_PARENT_CODE) > 0 then
    ValueSet vsPR;
    do varying numeric i = 1 until i > count(PSGC_REGION_DICT.PSGC_REGION_REC)
      vsPR.add(strip(R_NAME(i)), R_CODE(i));
    enddo;
    setvalueset(P_REGION, vsPR);
  endif;
PROC P_PROVINCE_HUC
onfocus
  P_PARENT_REGION = P_REGION;
  if loadcase(PSGC_PROVINCE_DICT, P_PARENT_REGION) > 0 then
    ValueSet vsPP;
    do varying numeric i = 1 until i > count(PSGC_PROVINCE_DICT.PSGC_PROVINCE_REC)
      vsPP.add(strip(P_NAME(i)), P_CODE(i));
    enddo;
    setvalueset(P_PROVINCE_HUC, vsPP);
  endif;
PROC P_CITY_MUNICIPALITY
onfocus
  C_PARENT_PROVINCE = P_PROVINCE_HUC;
  if loadcase(PSGC_CITY_DICT, C_PARENT_PROVINCE) > 0 then
    ValueSet vsPC;
    do varying numeric i = 1 until i > count(PSGC_CITY_DICT.PSGC_CITY_REC)
      vsPC.add(strip(C_NAME(i)), C_CODE(i));
    enddo;
    setvalueset(P_CITY_MUNICIPALITY, vsPC);
  endif;
PROC P_BARANGAY
onfocus
  B_PARENT_CITY = P_CITY_MUNICIPALITY;
  if loadcase(PSGC_BARANGAY_DICT, B_PARENT_CITY) > 0 then
    ValueSet vsPB;
    do varying numeric i = 1 until i > count(PSGC_BARANGAY_DICT.PSGC_BARANGAY_REC)
      vsPB.add(strip(B_NAME(i)), B_CODE(i));
    enddo;
    setvalueset(P_BARANGAY, vsPB);
  endif;

{ ---- GPS + verification photo (spec 4.3a; helpers in Capture-Helpers.apc) ---- }
PROC FACILITY_CAPTURE_GPS
onfocus
  if ReadGPSReading(120, 20) then
    FACILITY_GPS_LATITUDE   = maketext("%f", gps(latitude));
    FACILITY_GPS_LONGITUDE  = maketext("%f", gps(longitude));
    FACILITY_GPS_ALTITUDE   = maketext("%f", gps(altitude));
    FACILITY_GPS_ACCURACY   = gps(accuracy);
    FACILITY_GPS_SATELLITES = gps(satellites);
    FACILITY_GPS_READTIME   = maketext("%d", gps(readtime));
  endif;
  FACILITY_CAPTURE_GPS = notappl;

PROC P_HOME_CAPTURE_GPS
onfocus
  { Home-visit GPS (outpatient / home interview). Trigger item is
    P_HOME_CAPTURE_GPS per the dcf; fields are P_HOME_GPS_*. }
  if ReadGPSReading(120, 20) then
    P_HOME_GPS_LATITUDE   = maketext("%f", gps(latitude));
    P_HOME_GPS_LONGITUDE  = maketext("%f", gps(longitude));
    P_HOME_GPS_ALTITUDE   = maketext("%f", gps(altitude));
    P_HOME_GPS_ACCURACY   = gps(accuracy);
    P_HOME_GPS_SATELLITES = gps(satellites);
    P_HOME_GPS_READTIME   = maketext("%d", gps(readtime));
  endif;
  P_HOME_CAPTURE_GPS = notappl;

PROC CAPTURE_VERIFICATION_PHOTO
onfocus
  string fn = "case-" + maketext("%02d%02d%03d%02d%03d", REGION_CODE, PROVINCE_HUC_CODE, CITY_MUNICIPALITY_CODE, FACILITY_NO, CASE_SEQ) + "-verification.jpg";
  if TakeVerificationPhoto(fn) then
    VERIFICATION_PHOTO_FILENAME = fn;
  endif;
  CAPTURE_VERIFICATION_PHOTO = notappl;
"""

# #164 Outpatient/Inpatient routing (spec 2 Sections G-I preamble):
#   PATIENT_TYPE = 1 Outpatient -> Section G (Q88-Q104), skip H (Q105-Q115)
#   PATIENT_TYPE = 2 Inpatient  -> skip G, Section H
#   Section I (Q116+) asked for both. Gate the FIRST item of G and of H.
#   (Verify PATIENT_TYPE codes 1/2 against the dcf value set on first compile.)
BRANCHING = """\
{ ---- #164 Outpatient vs Inpatient branching ---- }
PROC Q88_WHY_VISIT
preproc
  if PATIENT_TYPE <> 1 then    { not Outpatient -> skip Section G entirely }
    skip to Q116_NBB_HEARD;
  endif;

PROC Q105_REASON
preproc
  if PATIENT_TYPE <> 2 then    { not Inpatient -> skip Section H entirely }
    skip to Q116_NBB_HEARD;
  endif;
"""

# Multi-branch routing + end-of-survey + cross-field gate (spec 2 D-F/J-L).
EXTRA_PROCS = """\
{ ---- Multi-branch routing (spec 2) ---- }
PROC Q63_HAS_USUAL_FACILITY
postproc
  if Q63_HAS_USUAL_FACILITY = 2 then  skip to Q65_WHY_NO_USUAL_O01; endif;  { No usual facility -> reasons }
  if Q63_HAS_USUAL_FACILITY = 1 then  skip to Q66_SAME_AS_USUAL;    endif;  { Yes -> skip Q64 reason-for-none }

PROC Q77_KON_REGISTERED
postproc
  if Q77_KON_REGISTERED = 2    then  skip to Q82_KON_WHY_NOT_REG_O01; endif;  { Not registered -> reasons }
  if Q77_KON_REGISTERED in 3,4 then  skip to Q83_VISIT_REASON;        endif;  { Never heard / IDK -> exit E }

PROC Q159_BRAND_GEN_BOUGHT
postproc
  if Q159_BRAND_GEN_BOUGHT = 1 then  skip to Q161_WHY_BRANDED_O01; endif;  { Branded -> why-branded }
  if Q159_BRAND_GEN_BOUGHT = 4 then  skip to Q162_REFERRED;        endif;  { Don't know diff -> exit K }
  if Q159_BRAND_GEN_BOUGHT = 5 then  skip to Q164_SPECIALIST;      endif;  { N/A -> source cross-jump (sanity #7) }

{ ---- Section D: non-members skip the benefits/premium block (Q46-Q50) ---- }
PROC Q46_BENEFITS_O01
preproc
  if Q38_PHILHEALTH_REG <> 1 then   { not a PhilHealth member -> skip benefits/packages/premiums }
    skip to Q51_OTHER_INSURANCE;
  endif;

{ ---- Section L: not referred -> end of survey (Completed) ---- }
PROC Q162_REFERRED
postproc
  if Q162_REFERRED = 2 then
    ENUM_RESULT_FINAL_VISIT = 1;   { Completed (verify code) }
    endlevel;
  endif;
"""

# Validations (spec 3.3 demographics + household-composition consistency).
VALIDATION_PROCS = """\
{ ---- Validations: demographics + household composition (spec 3.3) ---- }
PROC Q5_BIRTH_MONTH
postproc
  if Q5_BIRTH_MONTH < 1 or Q5_BIRTH_MONTH > 12 then
    errmsg("Birth month must be 1-12.");
    reenter;
  endif;

PROC Q5_BIRTH_YEAR
postproc
  if Q5_BIRTH_YEAR < 1900 or Q5_BIRTH_YEAR > currentYear then
    errmsg("Birth year must be between 1900 and %d.", currentYear);
    reenter;
  endif;

PROC Q6_AGE
postproc
  if Q6_AGE < 0 or Q6_AGE > 120 then
    errmsg("Age must be 0-120.");
    reenter;
  endif;
  if abs((currentYear - Q5_BIRTH_YEAR) - Q6_AGE) > 1 then
    errmsg("Age (%d) is inconsistent with birth year %d (current year %d). Reenter.",
           Q6_AGE, Q5_BIRTH_YEAR, currentYear);
    reenter;
  endif;

PROC Q18_INCOME_BRACKET
postproc
  { bracket must contain Q18_INCOME_AMOUNT (spec 3.3 bracket table) }
  numeric a = Q18_INCOME_AMOUNT;
  numeric ok = 0;
  if Q18_INCOME_BRACKET = 1 and a < 40000 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 2 and a >= 40000 and a <= 59999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 3 and a >= 60000 and a <= 99999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 4 and a >= 100000 and a <= 249999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 5 and a >= 250000 and a <= 499999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 6 and a >= 500000 then ok = 1; endif;
  if ok = 0 then
    errmsg("Income bracket does not match the reported amount (%d PHP/month). Reconcile.", a);
    reenter;
  endif;

PROC Q19_HH_SIZE
postproc
  if Q19_HH_SIZE < 1 or Q19_HH_SIZE > 30 then
    errmsg("Household size must be 1-30.");
    reenter;
  endif;
  if Q19_HH_SIZE > 15 then
    errmsg("Household size %d is unusually large. Confirm.", Q19_HH_SIZE);
  endif;

PROC Q20_HH_CHILDREN
postproc
  if Q20_HH_CHILDREN > Q19_HH_SIZE then
    errmsg("Children (%d) cannot exceed household size (%d).", Q20_HH_CHILDREN, Q19_HH_SIZE);
    reenter;
  endif;

PROC Q21_HH_SENIORS
postproc
  if Q21_HH_SENIORS > Q19_HH_SIZE then
    errmsg("Seniors (%d) cannot exceed household size (%d).", Q21_HH_SENIORS, Q19_HH_SIZE);
    reenter;
  endif;
  if Q20_HH_CHILDREN + Q21_HH_SENIORS > Q19_HH_SIZE then
    errmsg("Children + seniors (%d) exceed household size (%d).",
           Q20_HH_CHILDREN + Q21_HH_SENIORS, Q19_HH_SIZE);
    reenter;
  endif;

PROC Q28_WASHER
postproc
  if Q22_ELECTRICITY = 2 and (Q26_REFRIGERATOR = 1 or Q27_TELEVISION = 1 or Q28_WASHER = 1) then
    errmsg("Household reports no electricity but owns a powered appliance. Confirm.");
  endif;
"""

# Skip logic, table-driven (spec 2). Single-condition rows here; multi-branch
# routing (Q63/Q77/Q159) + end-of-survey (Q162) + cross-field gate (Q46) are in
# EXTRA_PROCS above.
SKIP_RULES = [
    # Section A — Introduction & Consent
    ("Q1_IS_PATIENT",        "Q1_IS_PATIENT = 1",            "Q4_NAME"),                 # respondent IS the patient -> skip Q2,Q3
    # Section B — Patient Profile
    ("Q11_PWD",              "Q11_PWD = 2",                  "Q15_EDUCATION"),
    ("Q12_PWD_SPECIFY",      "Q12_PWD_SPECIFY = 2",          "Q15_EDUCATION"),
    ("Q30_IP",               "Q30_IP = 2",                   "Q32_4PS"),
    ("Q33_DECISION_MAKER",   "Q33_DECISION_MAKER in 1,3",    "Q35_UHC_HEARD"),
    # Section C — UHC Awareness
    ("Q35_UHC_HEARD",        "Q35_UHC_HEARD = 2",            "Q38_PHILHEALTH_REG"),
    # Section D — PhilHealth / Insurance
    ("Q38_PHILHEALTH_REG",   "Q38_PHILHEALTH_REG in 2,3",    "Q43_KNOWS_ASSIST"),
    ("Q41_REG_DIFFICULTY",   "Q41_REG_DIFFICULTY = 2",       "Q43_KNOWS_ASSIST"),
    ("Q43_KNOWS_ASSIST",     "Q43_KNOWS_ASSIST = 2",         "Q45_CATEGORY"),
    ("Q48_PREMIUM_PAY",      "Q48_PREMIUM_PAY = 3",          "Q51_OTHER_INSURANCE"),
    ("Q49_PREMIUM_DIFFICULT","Q49_PREMIUM_DIFFICULT = 2",    "Q51_OTHER_INSURANCE"),
    ("Q51_OTHER_INSURANCE",  "Q51_OTHER_INSURANCE = 2",      "Q53_HAS_PCP"),
    # Section E — Primary Care Utilization
    ("Q53_HAS_PCP",          "Q53_HAS_PCP = 2",              "Q63_HAS_USUAL_FACILITY"),
    ("Q66_SAME_AS_USUAL",    "Q66_SAME_AS_USUAL = 1",        "Q68_USUAL_FAC_TYPE"),
    ("Q74_KON_HEARD",        "Q74_KON_HEARD = 2",            "Q83_VISIT_REASON"),
    # Section K — Access to Medicines
    ("Q145_PURCHASE_FREQ",   "Q145_PURCHASE_FREQ = 5",       "Q152_GAMOT_HEARD"),        # Never -> skip meds-access
    ("Q152_GAMOT_HEARD",     "Q152_GAMOT_HEARD = 2",         "Q158_BRAND_GEN_KNOW"),
    ("Q158_BRAND_GEN_KNOW",  "Q158_BRAND_GEN_KNOW = 2",      "Q162_REFERRED"),
    # Section L — Referrals
    ("Q169_VISITED",         "Q169_VISITED in 2,3",          "Q171_WHY_NOT_O01"),
    ("Q172_PCP_REFERRAL",    "Q172_PCP_REFERRAL = 2",        "Q177_WHY_HOSPITAL_O01"),
    # Section G — Outpatient Care
    ("Q89_ADVISED_ADMIT",  "Q89_ADVISED_ADMIT = 1",                       "Q91_USUAL_OUTPATIENT"),  # Yes -> Q91 (Q90 = why-not-confined)
    ("Q93_LABS_O17",       "Q93_LABS_O17 = 1",                            "Q95_PRESCRIBED"),         # 'None' (O17) ticked -> skip Q94 lab-cost matrix (spec G)
    ("Q95_PRESCRIBED",     "Q95_PRESCRIBED = 2",                          "Q97_FINAL_AMOUNT"),       # No prescription -> skip meds-cost matrix
    ("Q99_BUCAS_HEARD",    "Q99_BUCAS_HEARD = 2",                         "Q116_NBB_HEARD"),         # No -> end of Section G (sanity #9; skip Q100-104)
    ("Q102_BUCAS_ACCESSED","Q102_BUCAS_ACCESSED = 2",                     "Q104_WITHOUT_BUCAS"),     # No -> Q104 (skip Q103)
    # Section H — Inpatient Care
    ("Q108_MEDS_OUTSIDE",  "Q108_MEDS_OUTSIDE = 2",                       "Q110_LAB_OUTSIDE"),       # No -> skip meds-outside-cost
    ("Q110_LAB_OUTSIDE",   "Q110_LAB_OUTSIDE = 2",                        "Q113_PAY_01"),            # No -> skip Q111/Q112 to PhilHealth pay matrix
    # Section I — Financial Risk Protection
    ("Q116_NBB_HEARD",     "Q116_NBB_HEARD in 2,3",                       "Q119_ZBB_HEARD"),         # No / IDK -> skip Q117,Q118
    ("Q119_ZBB_HEARD",     "Q119_ZBB_HEARD in 2,3",                       "Q124_MAIFIP_HEARD"),      # No / IDK -> skip Q120-123
    ("Q124_MAIFIP_HEARD",  "Q124_MAIFIP_HEARD in 2,3",                    "Q130_REDUCED_SPEND"),     # No / IDK -> skip Q125-129
    ("Q126_MAIFIP_AVAILED","Q126_MAIFIP_AVAILED = 2",                     "Q130_REDUCED_SPEND"),     # No -> skip Q127-129 (spec: -> Q129; using end-of-MAIFIP)
    ("Q127_MAIFIP_OOP",    "Q127_MAIFIP_OOP = 2",                         "Q130_REDUCED_SPEND"),     # No -> skip Q128,Q129
]

TODO_NOTE = """\
{ ============================================================================
  STILL OPEN (follow-up F3 pass):
    - Q93 "None"(O17)->Q95 (select-all None flag) + Q113_PAY_08 Yes -> Q114.1
      (PhilHealth-availed gate) — select-all/matrix patterns, transcribe per dcf.
    - Section-specific validations (spec 3.2-3.14): dates, amount ranges,
      consistency checks (e.g. Q86<=Q85 patterns).
    - Single/select-all Other-specify (non-UHC9) — per-item parent + trigger.
    - Verify PATIENT_TYPE codes (1/2) + all option codes on first Designer compile.
    - Filipino label content + setlanguage (FMF Designer side).
  DONE this pass: skip logic Sections A-C, D-F (incl. non-member benefits gate),
    E primary-care, G/H/I (#164 branching), K, L (incl. end-of-survey).
  ============================================================================ }
"""


def dcf_item_names():
    names = []
    dic = json.loads(DCF.read_text(encoding="utf-8"))
    for level in dic["levels"]:
        for rec in level.get("records", []):
            for it in rec.get("items", []):
                names.append(it["name"])
    return names


def dcf_items_map():
    """{name: item_dict} for every item in the dcf (for other-specify derivation)."""
    items = {}
    dic = json.loads(DCF.read_text(encoding="utf-8"))
    for level in dic["levels"]:
        for rec in level.get("records", []):
            for it in rec.get("items", []):
                items[it["name"]] = it
    return items


def uhc9_other_specify_procs(names):
    procs = {}
    for n in names:
        for suffix, code, lbl in (("_YES_OTHER_TXT", 4, "Yes, other reason"),
                                  ("_NO_OTHER_TXT", 7, "No, other reason")):
            if n.endswith(suffix):
                parent = n[: -len(suffix)]
                procs[n] = (
                    f"PROC {n}\n"
                    f"postproc\n"
                    f"  if {parent} = {code} and length(strip({n})) = 0 then\n"
                    f"    errmsg(\"'{lbl}' was selected for {parent}. Please specify.\");\n"
                    f"    reenter;\n"
                    f"  endif;"
                )
    return procs


def skip_proc(field, cond, target):
    return (f"PROC {field}\npostproc\n  if {cond} then\n    skip to {target};\n  endif;")


def main():
    parts = [HEADER, "", CONTROL_PROCS, "", BRANCHING, "", EXTRA_PROCS, "",
             VALIDATION_PROCS, ""]
    covered = {"Q88_WHY_VISIT", "Q105_REASON",                    # branching PROCs
               "Q63_HAS_USUAL_FACILITY", "Q77_KON_REGISTERED",
               "Q159_BRAND_GEN_BOUGHT", "Q46_BENEFITS_O01", "Q162_REFERRED",  # EXTRA_PROCS
               "Q5_BIRTH_MONTH", "Q5_BIRTH_YEAR", "Q6_AGE", "Q18_INCOME_BRACKET",
               "Q19_HH_SIZE", "Q20_HH_CHILDREN", "Q21_HH_SENIORS", "Q28_WASHER"}  # VALIDATION_PROCS

    parts.append("{ ---- Skip logic (spec 2) ---- }")
    for field, cond, target in SKIP_RULES:
        if field in covered:
            raise SystemExit(f"PROC collision: {field}")
        covered.add(field)
        parts.append(skip_proc(field, cond, target))
        parts.append("")

    parts.append("{ ---- 'Other (specify)' enforcement — UHC9 dual-other (spec 4) ---- }")
    for field, proc in sorted(uhc9_other_specify_procs(dcf_item_names()).items()):
        if field in covered:
            continue
        covered.add(field)
        parts.append(proc)
        parts.append("")

    # Auto-derived single-choice + select-all 'Other (specify)' enforcement (#148).
    os_procs, os_map, os_skipped = other_specify_procs(dcf_items_map())
    parts.append("{ ---- 'Other (specify)' enforcement — single-choice + select-all "
                 f"(auto-derived from dcf: {len(os_procs)} items) ---- }}")
    for field, proc in sorted(os_procs.items()):
        if field in covered:
            continue
        covered.add(field)
        parts.append(proc)
        parts.append("")

    # Auto-derived select-all validation: >=1 option ticked (#3.5-3.14).
    sa_procs, sa_bases = select_all_validation_procs(dcf_items_map())
    sa_emitted = 0
    parts.append("{ ---- Select-all validation — >=1 option ticked "
                 "(auto-derived from dcf) ---- }")
    for field, proc in sorted(sa_procs.items()):
        if field in covered:   # last flag already drives a skip/other-specify -> don't double-PROC
            continue
        covered.add(field)
        parts.append(proc)
        parts.append("")
        sa_emitted += 1

    # Amount-required on payment-matrix _AMT fields (spec §3.9/§3.10 "if PAY=Yes, AMT>0").
    am_procs = amount_required_procs(dcf_items_map())
    am_emitted = 0
    parts.append("{ ---- Payment-matrix amount-required (auto-derived from dcf) ---- }")
    for field, proc in sorted(am_procs.items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append(""); am_emitted += 1

    # Per-item numeric range checks + cross-field/pair-sanity (spec §3.6–§3.13).
    parts.append("{ ---- Range + cross-field validations (spec §3.6-§3.13) ---- }")
    rng_emitted = 0
    for field, lo, hi, soft in RANGE_CHECKS:
        if field in covered:
            continue
        covered.add(field)
        parts.append(range_check_proc(field, lo, hi, hard=True, soft_over=soft))
        parts.append(""); rng_emitted += 1
    for field, proc in CUSTOM_VALIDATION:
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append(""); rng_emitted += 1

    parts.append(TODO_NOTE)
    text = "\n".join(parts).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    dupes = [l for l in text.splitlines() if l.startswith("PROC ")]
    assert len(dupes) == len(set(dupes)), "duplicate PROC names emitted"
    print(f"Wrote {OUT} ({len(text)} chars, {len(dupes)} PROC blocks, no dup names).")
    print(f"  other-specify enforcement: {len(os_procs)} auto-derived "
          f"({sum(1 for _, d in os_map if d.startswith('single'))} single + "
          f"{sum(1 for _, d in os_map if d.startswith('select'))} select-all)")
    if os_skipped:
        print(f"  other-specify SKIPPED (manual review — no resolvable trigger): {', '.join(os_skipped)}")
    print(f"  select-all validation: {sa_emitted} groups got a '>=1 ticked' check "
          f"(of {len(sa_bases)} detected; rest already drive a skip/other-specify)")
    print(f"  amount-required: {am_emitted} payment-matrix _AMT procs; "
          f"range/cross-field: {rng_emitted} procs")
    print("  NEXT: create the F3 .ent in Designer (input dcf + generated.fmf), set this")
    print("  as the main logic file, compile, fix any name/code mismatch, verify in CSEntry.")


if __name__ == "__main__":
    main()
