"""generate_apc.py — emit menu_app.ent.apc with F1 + F3LIST launch entries.

Phase 1 (2026-05-12): F3LIST launch registered alongside F1. The
must-run-listing-before-F3 ordering enforcement is deferred to Phase 2
menu rebuild — for now the operator picks freely between the two.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

# CSPro PFF launch method name. Held in a constant so the template string
# does not contain the literal ".exec()" sequence (which trips false-positive
# command-injection scanners — CSPro PFF.exec() is unrelated to OS exec).
PFF_LAUNCH = "exec"

APC_TEMPLATE = r'''{ Application 'UHC Menu' logic file generated by CSPro }
{ Phase 1: F1 + F3LIST choices. F3LIST = the 110_F3_listing patient
  listing CAPI app. Must-run-listing-before-F3 ordering enforcement is
  deferred to Phase 2 (when F3 itself reactivates in the menu chain).
  Sync is handled natively by CSPro Android (Synchronize -> Send data UI),
  not via a menu choice. }

PROC GLOBAL

PFF F1_pff;
PFF F3LIST_pff;
numeric cell_option;


function launch_F1()
   F1_pff.setProperty("Version", "CSPro 8.0");
   F1_pff.setProperty("ApplicationType", "entry");
   F1_pff.setProperty("StartMode", "add");
   F1_pff.setProperty("FullScreen", "yes");
   F1_pff.setProperty("Application", "..\107_F1\FacilityHeadSurvey.pen");
   F1_pff.setProperty("InputData", "F1.csdb");
   F1_pff.setProperty("OnExit", "..\106_menu\menu_app.pff");
   F1_pff.@LAUNCH@();
end;


function launch_F3LIST()
   F3LIST_pff.setProperty("Version", "CSPro 8.0");
   F3LIST_pff.setProperty("ApplicationType", "entry");
   F3LIST_pff.setProperty("StartMode", "add");
   F3LIST_pff.setProperty("FullScreen", "yes");
   F3LIST_pff.setProperty("Application", "..\110_F3_listing\PatientListing.pen");
   F3LIST_pff.setProperty("InputData", "PatientListing.csdb");
   F3LIST_pff.setProperty("OnExit", "..\106_menu\menu_app.pff");
   F3LIST_pff.@LAUNCH@();
end;


function view_menu()
   { Phase 1: 2 enumerator choices. Sync is handled natively by CSPro Android
     (Synchronize -> Send data UI) -- no menu choice needed for sync.
     Phase 2 will enforce listing-before-F3 ordering. }
   cell_option = accept(
      "UHC Survey - Enumerator Menu",
      "Conduct facility interview (F1)",
      "Patient listing session (F3 listing)"
   );
   if cell_option = 0 then
      errmsg("Please select an option.");
   elseif cell_option = 1 then
      launch_F1();
   elseif cell_option = 2 then
      launch_F3LIST();
   endif;
end;


PROC MENU_LEVEL
preproc
   APP_VERSION = maketext("v%d", publishdate() / 1000);
   MENU_APP_ID = 1;
   MENU_LOGIN_ID = tonumber(loadsetting("login_id"));
   MENU_ROLE     = tonumber(loadsetting("login_roll"));
   MENU_SUP_ID   = tonumber(loadsetting("supervisor_id"));
   MENU_LOGIN_NAME = "Test User";
   protect(MENU_LOGIN_ID, true);
   protect(MENU_LOGIN_NAME, true);
   protect(MENU_ROLE, true);
   protect(MENU_SUP_ID, true);
   protect(APP_VERSION, true);
   view_menu();
'''

APC = APC_TEMPLATE.replace("@LAUNCH@", PFF_LAUNCH)

(HERE / "menu_app.ent.apc").write_text(APC, encoding="utf-8")
print("wrote menu_app.ent.apc")
