"""generate_apc.py — emit menu_app.ent.apc with role-conditional accept() menu."""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'UHC Menu' logic file generated by CSPro }
{ Phase 1: role-conditional menu + PFF launch. Helpers via #include
  deferred to Phase 2 once Designer accepts include paths. }

PROC GLOBAL

PFF F1_pff;
PFF sync_pff;
numeric cell_option;


function launch_F1()
   F1_pff.setProperty("Version", "CSPro 8.0");
   F1_pff.setProperty("ApplicationType", "entry");
   F1_pff.setProperty("StartMode", "add");
   F1_pff.setProperty("FullScreen", "yes");
   F1_pff.setProperty("Application", "..\107_F1\FacilityHeadSurvey.pen");
   F1_pff.setProperty("InputData", "F1.csdb");
   F1_pff.setProperty("OnExit", "..\106_menu\menu_app.pff");
   F1_pff.exec();
end;


function launch_sync_F1()
   { E3-F1-088 Fix B1: sync runs in a dedicated entry app that declares F1's }
   { dict as external -- required for syncdata(PUT, dict) to resolve.        }
   sync_pff.setProperty("Version", "CSPro 8.0");
   sync_pff.setProperty("ApplicationType", "entry");
   sync_pff.setProperty("StartMode", "add");
   sync_pff.setProperty("FullScreen", "yes");
   sync_pff.setProperty("Application", "..\109_sync\sync_F1_app.pen");
   sync_pff.setProperty("InputData", "sync_F1.csdb");
   sync_pff.setProperty("OnExit", "..\106_menu\menu_app.pff");
   sync_pff.exec();
end;


function view_menu()
   { Phase 1: 2 enumerator choices. F1 entry first, then explicit sync.     }
   cell_option = accept(
      "UHC Survey - Enumerator Menu",
      "Conduct facility interview (F1)",
      "Sync data to server"
   );
   if cell_option = 0 then
      errmsg("Please select an option.");
   elseif cell_option = 1 then
      launch_F1();
   elseif cell_option = 2 then
      launch_sync_F1();
   endif;
end;


PROC MENU_LEVEL
preproc
   APP_VERSION = maketext("v%d", publishdate() / 1000);
   MENU_APP_ID = 1;
   MENU_LOGIN_ID = tonumber(loadsetting("login_id"));
   MENU_ROLE     = tonumber(loadsetting("login_roll"));
   MENU_SUP_ID   = tonumber(loadsetting("supervisor_id"));
   MENU_LOGIN_NAME = "Test User";
   protect(MENU_LOGIN_ID, true);
   protect(MENU_LOGIN_NAME, true);
   protect(MENU_ROLE, true);
   protect(MENU_SUP_ID, true);
   protect(APP_VERSION, true);
   view_menu();
'''

(HERE / "menu_app.ent.apc").write_text(APC, encoding="utf-8")
print("wrote menu_app.ent.apc")
