"""generate_apc.py — emit menu_app.ent.apc with single-F1 launch.

Phase 1 (2026-05-11): parked. Menu app reactivates in Phase 2 when 2nd
questionnaire arrives. Single-F1-choice form retained for forward continuity.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'UHC Menu' logic file generated by CSPro }
{ Phase 1: parked — menu app activates in Phase 2 when 2nd questionnaire is
  deployed. Single-choice form retained for forward continuity. Sync is
  handled natively by CSPro Android (Synchronize -> Send data UI), not via
  a menu choice. }

PROC GLOBAL

PFF F1_pff;
numeric cell_option;


function launch_F1()
   F1_pff.setProperty("Version", "CSPro 8.0");
   F1_pff.setProperty("ApplicationType", "entry");
   F1_pff.setProperty("StartMode", "add");
   F1_pff.setProperty("FullScreen", "yes");
   F1_pff.setProperty("Application", "..\107_F1\FacilityHeadSurvey.pen");
   F1_pff.setProperty("InputData", "F1.csdb");
   F1_pff.setProperty("OnExit", "..\106_menu\menu_app.pff");
   F1_pff.exec();
end;


function view_menu()
   { Phase 1: 1 enumerator choice. Sync is handled natively by CSPro Android
     (Synchronize -> Send data UI) -- no menu choice needed for sync. }
   cell_option = accept(
      "UHC Survey - Enumerator Menu",
      "Conduct facility interview (F1)"
   );
   if cell_option = 0 then
      errmsg("Please select an option.");
   elseif cell_option = 1 then
      launch_F1();
   endif;
end;


PROC MENU_LEVEL
preproc
   APP_VERSION = maketext("v%d", publishdate() / 1000);
   MENU_APP_ID = 1;
   MENU_LOGIN_ID = tonumber(loadsetting("login_id"));
   MENU_ROLE     = tonumber(loadsetting("login_roll"));
   MENU_SUP_ID   = tonumber(loadsetting("supervisor_id"));
   MENU_LOGIN_NAME = "Test User";
   protect(MENU_LOGIN_ID, true);
   protect(MENU_LOGIN_NAME, true);
   protect(MENU_ROLE, true);
   protect(MENU_SUP_ID, true);
   protect(APP_VERSION, true);
   view_menu();
'''

(HERE / "menu_app.ent.apc").write_text(APC, encoding="utf-8")
print("wrote menu_app.ent.apc")
