#!/usr/bin/env python3
"""
F1 Facility Head Survey — CAPI logic (.ent.apc) generator.

Emits `FacilityHeadSurvey.ent.apc` from the reviewed spec
(`F1-Skip-Logic-and-Validations.md`). Generator-over-hand-edit: edit the tables
below + rerun, never hand-edit the .apc in Designer (changes would be lost on
regenerate).

Covers GH issues (generator side — FMF Designer GUI + CSEntry verification are
Carl's): #146 master skip gates, #147 field skip logic, #148 hard validations,
#149 soft validations, #152 cross-field checks, #151 dynamic value sets,
#153 conditional fills, #154 consent capture, #156 disposition, #157 GPS,
#231 verification photo, #232 PSGC cascade wiring.

  ⚠️  UNVERIFIED until compiled in CSPro Designer + run in CSEntry. This was
      authored without a CSPro toolchain; treat the first Designer compile as
      the real test. Item names follow generate_dcf.py / the spec §4 templates;
      any mismatch surfaces as a compile error to fix at the source table here.

Invoke:  python generate_apc.py
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "FacilityHeadSurvey.ent.apc"
DCF = HERE / "FacilityHeadSurvey.dcf"


def dcf_item_names():
    """All item names in the F1 dcf (the source of truth for names)."""
    names = []
    dic = json.loads(DCF.read_text(encoding="utf-8"))
    for level in dic["levels"]:
        for rec in level.get("records", []):
            for it in rec.get("items", []):
                names.append(it["name"])
    return names


def uhc9_other_specify_procs(names):
    """#148: enforce 'Other (specify)' text on UHC9 dual-other items.
    `<FIELD>_YES_OTHER_TXT` (parent code 4) and `<FIELD>_NO_OTHER_TXT` (code 7),
    per spec 4.13. Parent = the name minus the suffix (dcf is the truth — spec
    used shortened names like Q12_YES_OTHER_TXT)."""
    procs = {}
    for n in names:
        for suffix, code, lbl in (("_YES_OTHER_TXT", 4, "Yes, other reason"),
                                  ("_NO_OTHER_TXT", 7, "No, other reason")):
            if n.endswith(suffix):
                parent = n[: -len(suffix)]
                procs[n] = (
                    f"PROC {n}\n"
                    f"postproc\n"
                    f"  if {parent} = {code} and length(strip({n})) = 0 then\n"
                    f"    errmsg(\"'{lbl}' was selected for {parent}. Please specify.\");\n"
                    f"    reenter;\n"
                    f"  endif;"
                )
    return procs


# Why-difficult display gates (spec 4.10): each Q66-74 option-set is shown only
# if the matching Q65 difficulty option was flagged; same for Q122-134 vs Q121.
# Gate fires as a first-field (O01) preproc. Question number -> option index by
# position (Q66->Q65 O01 ... Q74->Q65 O09; Q122->Q121 O01 ... Q134->Q121 O13).
WHY_DIFF_GATES = [
    (range(66, 75), "Q65_ACCRED_DIFFICULT", 66),   # Q66..Q74 -> Q65 O01..O09
    (range(122, 135), "Q121_DOH_LIC_DIFFICULT", 122),  # Q122..Q134 -> Q121 O01..O13
]


def why_difficult_gate_procs(names):
    procs = {}
    # base name (no _O##/_OTHER_TXT/_VS#) per question number, e.g. 66 -> Q66_WHY_DIFF_PREVENTIVE
    base_by_q = {}
    first_field_by_q = {}
    for n in names:
        m = re.match(r"^Q(\d+)_(WHY_DIFF_[A-Z0-9_]+?)_O(\d+)$", n)
        if not m:
            continue
        q, opt = int(m.group(1)), int(m.group(3))
        if opt == 1:
            first_field_by_q[q] = n  # the O01 field is where the gate preproc lives
    for qrange, gate_dict, start in WHY_DIFF_GATES:
        for q in qrange:
            field = first_field_by_q.get(q)
            if not field:
                continue
            opt_idx = q - start + 1
            gate = f"{gate_dict}_O{opt_idx:02d}"
            procs[field] = (
                f"PROC {field}\n"
                f"preproc\n"
                f"  if {gate} = 0 then   {{ Q{q} shown only if {gate} was flagged in the difficulty list }}\n"
                f"    skip to next;\n"
                f"  endif;"
            )
    return procs

HEADER = """\
{ ============================================================================
  FacilityHeadSurvey — CAPI logic   (AUTOGENERATED by generate_apc.py)
  Do NOT hand-edit: edit generate_apc.py's tables and rerun.
  Spec: F1-Skip-Logic-and-Validations.md (reviewed 2026-04-21).
  Helpers are #include'd from ../shared (CSPro 8 logic v2.0 supports #include).
  ============================================================================ }

#include "../shared/Capture-Helpers.apc"
#include "../shared/PSGC-Cascade.apc"

PROC GLOBAL
{ Date context for accreditation / tenure validations (see spec 4.1). }
numeric currentYYYYMMDD;
numeric currentYear;
numeric currentMonth;
"""

# --- Application entry: init date context + (no global skips here) -----------
APP_ENTRY = """\
PROC FACILITYHEADSURVEY_FF
preproc
  currentYYYYMMDD = systemdate("YYYYMMDD");
  currentYear  = int(currentYYYYMMDD / 10000);
  currentMonth = int(currentYYYYMMDD / 100) % 100;
  LANGUAGE_USED = getlanguage();   { §15.E — capture the active CSEntry language for this case }
endpreproc
"""

# --- Interview-control scaffolding: consent gate, GPS, photo, PSGC -----------
# Item names per generate_dcf.py (FIELD_CONTROL, REC_FACILITY_CAPTURE, geo-ID).
CONTROL_PROCS = """\
{ ---- #154 Informed consent: Consent = No (2) aborts the interview ---- }
PROC CONSENT_GIVEN
postproc
  if CONSENT_GIVEN = 2 then    { 1 = Yes, 2 = No }
    ENUM_RESULT_FINAL_VISIT = 4;   { 4 = Refused (set disposition before ending) }
    errmsg("Respondent declined consent. Interview ends; case coded Refused.");
    endlevel;
  endif;

{ ---- #157 Facility GPS capture (REC_FACILITY_CAPTURE, type Z, off-form) ----
  Enumerator taps the FACILITY_CAPTURE_GPS trigger; ReadGPSReading() lives in
  Capture-Helpers.apc. }
PROC FACILITY_CAPTURE_GPS
onfocus
  if ReadGPSReading(120, 20) then
    FACILITY_GPS_LATITUDE   = maketext("%f", gps(latitude));
    FACILITY_GPS_LONGITUDE  = maketext("%f", gps(longitude));
    FACILITY_GPS_ALTITUDE   = maketext("%f", gps(altitude));
    FACILITY_GPS_ACCURACY   = gps(accuracy);
    FACILITY_GPS_SATELLITES = gps(satellites);
    FACILITY_GPS_READTIME   = gps(readtime);
  endif;
  FACILITY_CAPTURE_GPS = notappl;   { reset trigger so the button re-arms }

{ ---- #231 Verification photo. Filename pattern case-{12-digit case id RR-PP-MMM-FF-CCC}-verification.jpg.
  Trigger item is CAPTURE_VERIFICATION_PHOTO per the dcf (off-form, type Z). ---- }
PROC CAPTURE_VERIFICATION_PHOTO
onfocus
  string fn = "case-" + maketext("%02d%02d%03d%02d%03d", REGION_CODE, PROVINCE_HUC_CODE, CITY_MUNICIPALITY_CODE, FACILITY_NO, CASE_SEQ) + "-verification.jpg";
  if TakeVerificationPhoto(fn) then
    VERIFICATION_PHOTO_FILENAME = fn;
  endif;
  CAPTURE_VERIFICATION_PHOTO = notappl;

{ ---- #232 / #151 PSGC cascade: each child's value set is filtered to children
  of the chosen parent at onfocus (handlers in PSGC-Cascade.apc). ---- }
PROC REGION
onfocus
  FillRegionValueSet(REGION);

PROC PROVINCE_HUC
onfocus
  FillProvinceValueSet(PROVINCE_HUC, REGION);

PROC CITY_MUNICIPALITY
onfocus
  FillCityValueSet(CITY_MUNICIPALITY, PROVINCE_HUC);

PROC BARANGAY
onfocus
  FillBarangayValueSet(BARANGAY, CITY_MUNICIPALITY);
"""

# --- Bespoke PROCs transcribed verbatim from spec §4 (author-validated names).
# Each entry is keyed by the field name it owns so we never emit a duplicate
# PROC for a field that also appears in a table-driven skip below.
BESPOKE_PROCS = {
    # 4.2 + 4.3 eligibility / tenure (Section A) — #148 hard, #152 cross-field
    "Q5_MONTHS_AT_FACILITY": """\
PROC Q5_MONTHS_AT_FACILITY
postproc
  if (Q5_YEARS_AT_FACILITY * 12 + Q5_MONTHS_AT_FACILITY) < 6 then
    errmsg("Respondent must have >= 6 months in current position. End interview and code as Refused/Incomplete.");
    ENUM_RESULT_FINAL_VISIT = 4;   { Refused/Incomplete }
    endlevel;
  endif;
  if Q5_YEARS_AT_FACILITY > (Q3_AGE - 18) then
    errmsg("Years at facility (%d) exceeds working-age years available (%d). Reenter.",
           Q5_YEARS_AT_FACILITY, Q3_AGE - 18);
    reenter;
  endif;""",
    "Q6_MONTHS_HEALTH": """\
PROC Q6_MONTHS_HEALTH
postproc
  numeric tenureMos = Q5_YEARS_AT_FACILITY * 12 + Q5_MONTHS_AT_FACILITY;
  numeric healthMos = Q6_YEARS_HEALTH * 12 + Q6_MONTHS_HEALTH;
  if healthMos < tenureMos then
    errmsg("Years in any health-related role (%d mos) cannot be less than years at this facility (%d mos).",
           healthMos, tenureMos);
    reenter;
  endif;
  if Q6_YEARS_HEALTH > (Q3_AGE - 18) then
    errmsg("Years in health (%d) exceeds working-age years available (%d).",
           Q6_YEARS_HEALTH, Q3_AGE - 18);
    reenter;
  endif;""",
    # 4.6 YAKAP accreditation date (Section D) — #148 hard
    "Q52_YK_SINCE_YEAR": """\
PROC Q52_YK_SINCE_YEAR
postproc
  if Q52_YK_SINCE_YEAR < 2019 or Q52_YK_SINCE_YEAR > currentYear then
    errmsg("YAKAP accreditation year must be between 2019 and %d.", currentYear);
    reenter;
  endif;""",
    "Q52_YK_SINCE_MONTH": """\
PROC Q52_YK_SINCE_MONTH
postproc
  if Q52_YK_SINCE_MONTH < 1 or Q52_YK_SINCE_MONTH > 12 then
    errmsg("Month must be 1-12.");
    reenter;
  endif;
  if Q52_YK_SINCE_YEAR = currentYear and Q52_YK_SINCE_MONTH > currentMonth then
    errmsg("Accreditation date is in the future. Reenter.");
    reenter;
  endif;""",
    # 4.7 registered <= eligible (Section D) — #152 cross-field
    "Q87_REGISTERED_PATIENTS": """\
PROC Q87_REGISTERED_PATIENTS
postproc
  if Q87_REGISTERED_PATIENTS > Q86_ELIGIBLE_PATIENTS then
    errmsg("Registered patients (%d) cannot exceed eligible patients (%d).",
           Q87_REGISTERED_PATIENTS, Q86_ELIGIBLE_PATIENTS);
    reenter;
  endif;""",
    # 4.8 capitation soft warning (Section D) — #149 soft (accept) + #148 hard cap
    "Q57_CAPITATION_AMT": """\
PROC Q57_CAPITATION_AMT
postproc
  if Q57_CAPITATION_AMT > 5000 then
    errmsg("Capitation %d PHP is implausibly high. Reenter or confirm.", Q57_CAPITATION_AMT);
    reenter;
  endif;
  if Q57_CAPITATION_AMT > 1700 then
    if accept("Capitation %d exceeds the PHP 1,700 PhilHealth max. Confirm?", "Yes", "No") <> 1 then
      reenter;
    endif;
  endif;""",
    # 4.9 Q121 "select all that apply" DOH-licensing-difficulty (Section F).
    # Reconciled vs the Apr 20 questionnaire (#151): the dcf models Q121 as 14
    # binary option fields (_O01..O14), so facility-type option visibility is a
    # PER-OPTION gate, not a setvalueset on a single field (the old PROC named a
    # field — Q121_DOH_LIC_DIFFICULT — that does not exist in the dcf, a hard
    # compile error). Per the questionnaire: O10/O11/O12 are hospital-only, O13
    # (public access to price information) is primary-care-only, O14 = "None of
    # the above" -> skip the why-difficult cluster to Q135. Q8_SERVICE_LEVEL = 1
    # is Primary Care Facility.
    # DESIGNER-VERIFY: the `noinput` conditional-hide idiom for a multi-select
    # option is the one bit to confirm on compile; symbols all resolve.
    "Q121_DOH_LIC_DIFFICULT_O10": """\
PROC Q121_DOH_LIC_DIFFICULT_O10
preproc
  if Q8_SERVICE_LEVEL = 1 then noinput; endif;   { hospital-only option; hide for primary-care facilities }""",
    "Q121_DOH_LIC_DIFFICULT_O11": """\
PROC Q121_DOH_LIC_DIFFICULT_O11
preproc
  if Q8_SERVICE_LEVEL = 1 then noinput; endif;   { hospital-only option; hide for primary-care facilities }""",
    "Q121_DOH_LIC_DIFFICULT_O12": """\
PROC Q121_DOH_LIC_DIFFICULT_O12
preproc
  if Q8_SERVICE_LEVEL = 1 then noinput; endif;   { hospital-only option; hide for primary-care facilities }""",
    "Q121_DOH_LIC_DIFFICULT_O13": """\
PROC Q121_DOH_LIC_DIFFICULT_O13
preproc
  if Q8_SERVICE_LEVEL <> 1 then noinput; endif;  { primary-care-only option; hide for hospitals }""",
    "Q121_DOH_LIC_DIFFICULT_O14": """\
PROC Q121_DOH_LIC_DIFFICULT_O14
postproc
  if Q121_DOH_LIC_DIFFICULT_O14 = 1 then   { "None of the above" -> skip the why-difficult cluster }
    skip to Q135_NBB_CURR;
  endif;""",
}

# --- Multi-branch routing (spec 2 Section D/E/G) deferred from pass 1. Branch
# VALUES are from the spec's skip table; controlling-field item names confirmed
# against the dcf. Single-choice control fields, so these are field PROCs.
# (Verify the literal option codes for Q116/Q152 in Designer — spec gives them
# as labels, not numbers; the common cases are coded below.)
ROUTING_PROCS = {
    # Section C: Q32 "No, not submitting" (4) -> Q35
    "Q32_DATA_SUBMIT": """\
PROC Q32_DATA_SUBMIT
postproc
  if Q32_DATA_SUBMIT = 4 then       { No, not submitting }
    skip to Q35_STAFFING_CHANGED;
  endif;""",
    # Section D: Q61 = No -> Q62 (skip the reason-text item Q61.1)
    "Q61_TRANCHE_DELAY": """\
PROC Q61_TRANCHE_DELAY
postproc
  if Q61_TRANCHE_DELAY = 2 then     { No }
    skip to Q62_TRANCHE_INTERVAL;
  endif;""",
    # Section D: Q80 5-way intend-accredit routing
    "Q80_INTEND_ACCRED": """\
PROC Q80_INTEND_ACCRED
postproc
  if Q80_INTEND_ACCRED in 1,2 then  skip to Q84_PROCESS_CHALL;        endif;  { Yes (in/ not-in process) }
  if Q80_INTEND_ACCRED = 3    then  skip to Q82_DECIDED_NOT_REASON;   endif;  { No, decided not to }
  if Q80_INTEND_ACCRED = 4    then  skip to Q83_TRIED_FAILED_REASON;  endif;  { No, tried and failed }
  if Q80_INTEND_ACCRED = 5    then  skip to Q81_KNOW_HOW_START;       endif;  { No, haven't thought }
  if Q80_INTEND_ACCRED = 6    then  skip to Q85_CATCHMENT_AREA;   endif;  { I don't know }""",
    # Section D: Q90 costing-viable x Q51 accreditation status
    "Q90_COSTING_VIABLE": """\
PROC Q90_COSTING_VIABLE
postproc
  if Q90_COSTING_VIABLE = 1 and Q51_YK_ACCRED = 1 then  skip to Q91_MIN_CAP_VALUE_ACC;    endif;  { Viable + accredited }
  if Q90_COSTING_VIABLE = 2 and Q51_YK_ACCRED = 2 then  skip to Q92_MIN_CAP_VALUE_NONACC; endif;  { Not viable + non-accredited }
  if Q90_COSTING_VIABLE = 3 then                        skip to Q93_CHARGE_ADDL_CAP;      endif;  { I don't know }""",
    # Section D: Q95 received-payments (Yes-all / Yes-some) -> Q97
    "Q95_RECEIVED_PAYMENTS": """\
PROC Q95_RECEIVED_PAYMENTS
postproc
  if Q95_RECEIVED_PAYMENTS in 1,2 then   { Yes, all / Yes, some }
    skip to Q97_PAYMENT_CHALL;
  endif;""",
    # Section E: Q102 has-BUCAS 3-way (No falls through to Q103)
    "Q102_HAS_BUCAS": """\
PROC Q102_HAS_BUCAS
postproc
  if Q102_HAS_BUCAS = 1 then  skip to Q104_BUCAS_SERVICES_O01; endif;  { Yes -> services (skip Q103) }
  if Q102_HAS_BUCAS = 3 then  skip to Q108_HEARD_GAMOT;        endif;  { I don't know -> Q108 }""",
    "Q103_NO_BUCAS_REASON": """\
PROC Q103_NO_BUCAS_REASON
postproc
  skip to Q108_HEARD_GAMOT;          { any answer -> Q108 (skip Q104-107) }""",
    # Section E: Q109 GAMOT-accredited (No falls through to Q110)
    "Q109_GAMOT_ACCRED": """\
PROC Q109_GAMOT_ACCRED
postproc
  if Q109_GAMOT_ACCRED = 1 then  skip to Q111_GAMOT_FACTORS_O01; endif;  { Yes (skip Q110) }""",
    "Q110_NO_GAMOT_REASON": """\
PROC Q110_NO_GAMOT_REASON
postproc
  skip to Q112_STOCKOUT;             { any answer -> Q112 (skip Q111) }""",
    # Section E: Q116 = No / Did-not-experience -> Q118 (codes per dcf value set; verify)
    "Q116_ADDR_STOCKOUT": """\
PROC Q116_ADDR_STOCKOUT
postproc
  if Q116_ADDR_STOCKOUT in 2,3 then  { 2 = No, 3 = Did not experience (verify codes in Designer) }
    skip to Q118_DOH_LICENSED;
  endif;""",
    # Section G: Q145 Malasakit provided
    "Q145_MALASAKIT_PROVIDED": """\
PROC Q145_MALASAKIT_PROVIDED
postproc
  if Q145_MALASAKIT_PROVIDED = 2 then    { No -> skip the why-provided block to the not-provided block }
    skip to Q147_NO_MALASAKIT_WHY_O01;
  endif;""",
    # Q145=Yes path: Q146 (why-provided) is asked, then Q147 (not-provided) must
    # be skipped. Gate Q147's first field on Q145=Yes -> jump to Q148 (spec 4.10
    # first-field-preproc pattern; Q145=No reaches Q147 normally).
    "Q147_NO_MALASAKIT_WHY_O01": """\
PROC Q147_NO_MALASAKIT_WHY_O01
preproc
  if Q145_MALASAKIT_PROVIDED = 1 then   { Yes -> Q146 already asked; skip the not-provided block }
    skip to Q148_LGU_SUPPORT;
  endif;""",
    # Section G: Q152 protocol clarity (Very Clear / Clear) -> Q154
    "Q152_PHO_PROTOCOL_CLARITY": """\
PROC Q152_PHO_PROTOCOL_CLARITY
postproc
  if Q152_PHO_PROTOCOL_CLARITY in 1,2 then   { Very Clear / Clear (verify codes) }
    skip to Q154_NUM_REFERRED_OUT;
  endif;""",
}
BESPOKE_PROCS.update(ROUTING_PROCS)

# --- Table-driven skip logic (spec §2). Each row: field PROC -> if <cond> skip.
# Kept simple/dichotomous; complex multi-branch routing (Q80, Q90, Q102/Q109)
# stays bespoke/TODO below. Fields already in BESPOKE_PROCS are skipped to avoid
# duplicate PROC blocks.
SKIP_RULES = [
    # Section C — UHC Implementation
    ("Q10_HAS_PRIMARY_PKG",   "Q10_HAS_PRIMARY_PKG = 2",        "Q12_PCB_LICENSING"),
    ("Q13_PUBLIC_HEALTH_UNIT","Q13_PUBLIC_HEALTH_UNIT in 2,9",  "Q16_HEALTH_PROMO_UNIT"),
    ("Q14_PHU_CREATED",       "Q14_PHU_CREATED in 5:9",         "Q16_HEALTH_PROMO_UNIT"),
    ("Q16_HEALTH_PROMO_UNIT", "Q16_HEALTH_PROMO_UNIT in 2,9",   "Q19_NEW_ROLES"),
    ("Q17_HPU_CREATED",       "Q17_HPU_CREATED in 5:9",         "Q19_NEW_ROLES"),
    ("Q19_NEW_ROLES",         "Q19_NEW_ROLES in 5:9",           "Q21_NEW_DEPTS"),
    ("Q21_NEW_DEPTS",         "Q21_NEW_DEPTS in 5:9",           "Q23_NEW_BUILDINGS"),
    ("Q23_NEW_BUILDINGS",     "Q23_NEW_BUILDINGS in 5:9",       "Q25_NEW_ROOMS"),
    ("Q25_NEW_ROOMS",         "Q25_NEW_ROOMS in 5:9",           "Q27_INC_EQUIPMENT"),
    ("Q27_INC_EQUIPMENT",     "Q27_INC_EQUIPMENT in 5:9",       "Q29_INC_SUPPLIES"),
    ("Q29_INC_SUPPLIES",      "Q29_INC_SUPPLIES in 5:9",        "Q31_EMR_USE"),
    ("Q31_EMR_USE",           "Q31_EMR_USE in 5:8 or Q31_EMR_USE = 9", "Q35_STAFFING_CHANGED"),
    ("Q35_STAFFING_CHANGED",  "Q35_STAFFING_CHANGED = 2",       "Q37_REFERRAL_CHANGED"),
    ("Q37_REFERRAL_CHANGED",  "Q37_REFERRAL_CHANGED = 2",       "Q39_MOU_MOA"),
    # Section D — YAKAP / Konsulta
    ("Q51_YK_ACCRED",         "Q51_YK_ACCRED = 2",              "Q79_NOT_ACCRED_REASON_O01"),
    ("Q59_KNOW_PAY_FREQ",     "Q59_KNOW_PAY_FREQ = 2",          "Q61_TRANCHE_DELAY"),
    ("Q77_ENROLL_CHALL",      "Q77_ENROLL_CHALL = 2",           "Q85_CATCHMENT_AREA"),
    ("Q89_COSTING_DONE",      "Q89_COSTING_DONE = 2",           "Q91_MIN_CAP_VALUE_ACC"),
    ("Q93_CHARGE_ADDL_CAP",   "Q93_CHARGE_ADDL_CAP = 2",        "Q95_RECEIVED_PAYMENTS"),
    ("Q97_PAYMENT_CHALL",     "Q97_PAYMENT_CHALL = 2",          "Q99_EXPAND_NEXT_O01"),
    # Section E — BUCAS / GAMOT
    ("Q101_HEARD_BUCAS",      "Q101_HEARD_BUCAS = 2",           "Q108_HEARD_GAMOT"),
    ("Q108_HEARD_GAMOT",      "Q108_HEARD_GAMOT = 2",           "Q112_STOCKOUT"),
    ("Q112_STOCKOUT",         "Q112_STOCKOUT = 2",              "Q118_DOH_LICENSED"),
    # Section F — DOH Licensing
    ("Q118_DOH_LICENSED",     "Q118_DOH_LICENSED in 2,3,4",     "Q135_NBB_CURR"),
    # Section G — Service Delivery
    ("Q135_NBB_CURR",         "Q135_NBB_CURR = 2",              "Q138_ZBB_CURR"),
    ("Q138_ZBB_CURR",         "Q138_ZBB_CURR = 2",              "Q141_ALLOW_OOP_BASIC"),
    ("Q141_ALLOW_OOP_BASIC",  "Q141_ALLOW_OOP_BASIC = 2",       "Q143_DIFFICULT_BENEFIT"),
    ("Q148_LGU_SUPPORT",      "Q148_LGU_SUPPORT = 2",           "Q152_PHO_PROTOCOL_CLARITY"),
    ("Q150_LGU_SATISFIED",    "Q150_LGU_SATISFIED = 1",         "Q154_NUM_REFERRED_OUT"),
    ("Q161_REF_SATISFACTION", "Q161_REF_SATISFACTION in 1,2",   "Q163_HR_CHALL_O01"),
]

# Multi-branch / routing skips left for a follow-up pass (need careful per-branch
# transcription + ASPSI confirmation): Q80 (5-way intend-accredit), Q90 (costing
# viable x Q51), Q102/Q109 (BUCAS/GAMOT has-x branches), Q32 DATA_SUBMIT,
# Q65/Q121 "why-difficult" per-option gates (Q66-Q74, Q122-Q134).
TODO_NOTE = """\
{ ============================================================================
  STILL OPEN (need per-item data or FMF/CSEntry verification):
    - "Other (specify)" on SINGLE-choice + SELECT-ALL items (non-UHC9): each
      needs its own parent field + trigger code/flag (e.g. Q11_OTHER_TXT ->
      Q11_PRIMARY_PKG_STATUS = 5; Q104_..._OTHER_TXT -> the option's _O##_OTHER
      flag). ~80 items; transcribe per item from the dcf value sets.
    - Q65 / Q121 "None of the above only" -> skip the whole why-difficult block
      (Q65_ACCRED_DIFFICULT_O10 / Q121_DOH_LIC_DIFFICULT_O14 = the None flag).
    - #144/#145 Filipino label content + setlanguage (FMF Designer side).
    - Verify every literal option CODE marked "(verify codes)" against the dcf
      value sets on first Designer compile.
  ============================================================================ }
"""


def skip_proc(field, cond, target):
    return (
        f"PROC {field}\n"
        f"postproc\n"
        f"  if {cond} then\n"
        f"    skip to {target};\n"
        f"  endif;"
    )


def main():
    parts = [HEADER, "", APP_ENTRY, "", CONTROL_PROCS, ""]

    parts.append("{ ---- Validations & cross-field checks (spec 4) ---- }")
    for field in sorted(BESPOKE_PROCS):
        parts.append(BESPOKE_PROCS[field])
        parts.append("")

    parts.append("{ ---- Skip logic (spec 2), table-driven ---- }")
    covered = set(BESPOKE_PROCS)
    for field, cond, target in SKIP_RULES:
        if field in covered:
            # field already owns a bespoke PROC — fold the skip in there instead
            raise SystemExit(
                f"PROC collision: {field} is both bespoke and a skip rule; "
                f"merge the skip into its BESPOKE_PROCS entry."
            )
        covered.add(field)
        parts.append(skip_proc(field, cond, target))
        parts.append("")

    # dcf-driven blocks (names read straight from the dictionary)
    names = dcf_item_names()

    parts.append("{ ---- Why-difficult display gates (spec 4.10) ---- }")
    for field, proc in sorted(why_difficult_gate_procs(names).items()):
        if field in covered:
            continue
        covered.add(field)
        parts.append(proc)
        parts.append("")

    parts.append("{ ---- 'Other (specify)' enforcement — UHC9 dual-other items (spec 4.13) ---- }")
    for field, proc in sorted(uhc9_other_specify_procs(names).items()):
        if field in covered:
            continue
        covered.add(field)
        parts.append(proc)
        parts.append("")

    parts.append(TODO_NOTE)

    text = "\n".join(parts).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    n_procs = text.count("\nPROC ") + text.startswith("PROC ")
    print(f"Wrote {OUT} ({len(text)} chars, ~{n_procs} PROC blocks).")
    print("  NEXT: open in CSPro Designer, compile (Build > Compile), fix any")
    print("  item-name mismatches at the source tables in generate_apc.py, then")
    print("  verify the skip/validation flow in CSEntry (issues stay 'pending-verify').")


if __name__ == "__main__":
    main()
