"""generate_apc.py — emit F4Listing.ent.apc.

Logic for the F4 household-listing app. Sibling to 110_F3_listing's APC
but with these structural differences (per Carl's 2026-05-12 design
decisions):

  - NO random-interval cadence engine. The barangay-listing crew walks
    a predefined frame (captain's list or door-to-door) rather than
    sampling on a clock. (PROC GLOBAL still seeds a PRNG so the
    LISTING_NO order is deterministic for desk-audit replay -- Q8.)
  - NO auto-tag. Every listed household is F4-eligible. F4_STATUS
    starts at 0 (pending) and is moved by the F4 entry app, not the
    listing app.
  - LISTING_SOURCE hybrid validation (Q1) -- soft warnmsg if the
    operator marks LISTING_SOURCE=1 but FRAME_NOTES contains text
    indicating the captain refused / list missing.
  - Frame finalizer postproc -- when SESSION_STATUS leaves "1 In
    progress" the .apc snapshots the running counters as the
    canonical frame for downstream F4 consumption + triggers the
    synchronize_file() push.
  - Sync path encodes BARANGAY_CODE as a separate segment (Q3 plan):
      f4_listing/<env>/<RR><PP><MMM><FF>/<YYYYMMDD>/<BARANGAY10>/<SSS>.csdb

Structure:
  PROC GLOBAL                          -- named constants + helper functions
  PROC F4LISTING_LEVEL                 -- level preproc placeholder
  PROC REC_LISTING_CONTROL             -- session header preproc
  PROC LISTING_SOURCE                  -- onfocus -> warnmsg cross-check
  PROC SESSION_STATUS                  -- postproc -> frame finalize + sync
  PROC REC_LISTING_BRGY_FRAME          -- per-listed-household preproc
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'F4Listing' logic file generated by CSPro }
{ F4 Household Listing CAPI app -- barangay-frame builder + audit trail.    }
{ Sibling to PatientListing.ent.apc but without the cadence engine + tag    }
{ rule. See 110_F3_listing/generate_apc.py for the symmetrical PROC layout. }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Project-wide replacement-protocol partitioning (audit only) ----- }
{ Mirrored from shared/cspro_helpers.py::CASE_SEQ_*_RANGE. The listing  }
{ app does NOT assign F-series CASE_SEQ -- F4 preproc handles that when }
{ it consumes the roster. Kept here as constants so the listing app    }
{ self-documents the F-series CASE_SEQ landscape for desk reviewers     }
{ reading the source.                                                    }
numeric SEQ_ACTIVE_LO      =   1;
numeric SEQ_ACTIVE_HI      = 699;
numeric SEQ_REPLACEMENT_LO = 700;
numeric SEQ_REPLACEMENT_HI = 899;
numeric SEQ_REFUSED_LO     = 900;
numeric SEQ_REFUSED_HI     = 999;

{ ---- Frame-design constants ----------------------------------------- }
{ Default replacement reserves per Carl's Q2 decision = 10. Held here  }
{ as a named constant so a Myra edit-pass tune does not need a DCF     }
{ recompile -- only the .apc.                                          }
numeric DEFAULT_REPLACEMENT_RESERVES = 10;

{ ---- Internal state -------------------------------------------------- }
{ Tracked at PROC GLOBAL scope because CSPro level variables are        }
{ wiped between cases. These are valid for one session only.            }
numeric g_session_seed    = 0;     { PRNG seed for this session         }


{ ---- PRNG seed ----------------------------------------------------- }

function SeedSessionPRNG(numeric enumeratorId, numeric dateSession,
                         numeric timeStart,    numeric barangayCode)
    { Derive a per-session seed from enumerator + date + start-time +
      barangay (Carl's Q8 seed inputs).

      Determinism: same (enumerator, date, time-of-day, barangay) ->
      same seed sequence. Used only to make LISTING_NO ordering
      reproducible for desk-audit replay when the crew randomizes
      household-visit order within a captain-supplied list. NOT a
      security claim -- it is an audit trail.

      Determinism note: BARANGAY_CODE is a 10-digit value; folding it
      into the seed widens the per-day key beyond what F3-listing's
      seed offers (F3 lists at one facility-day per session, so the
      BARANGAY dimension does not exist there). }

    numeric s = (enumeratorId * 100000000) + dateSession + timeStart;
    s = s + (barangayCode * 10000);
    { Fold to 32-bit unsigned range; CSPro seed() accepts any numeric. }
    g_session_seed = s % 4294967295;
    seed(g_session_seed);
end;


{ ---- Roster bookkeeping -------------------------------------------- }

function IncrementSessionCounter(string outcome)
    { Bump the session-header running counter that matches the listing
      outcome. Counter names match REC_LISTING_CONTROL items. }

    if outcome = "listed" then
        LISTED_COUNT = LISTED_COUNT + 1;
    elseif outcome = "refused" then
        REFUSED_COUNT = REFUSED_COUNT + 1;
    elseif outcome = "excluded" then
        EXCLUDED_COUNT = EXCLUDED_COUNT + 1;
    endif;
end;


function ContainsRefusalMarker(string notes)
    { Returns 1 if the free-text notes look like the captain refused /
      list missing. Cheap heuristic -- avoids regex; case-insensitive
      substring match on common phrases.

      Used by PROC LISTING_SOURCE onfocus/postproc to soft-warn when
      the operator marks LISTING_SOURCE=1 but the notes suggest the
      crew actually fell back to LISTING_SOURCE=2. Soft warnmsg only --
      the operator may have legitimate context. }

    string lower = lower(strip(notes));
    if lower = "" then
        ContainsRefusalMarker = 0;
        exit;
    endif;
    if pos("captain refused",  lower) > 0 or
       pos("refused to share", lower) > 0 or
       pos("list missing",     lower) > 0 or
       pos("no captain list",  lower) > 0 or
       pos("captain unavail",  lower) > 0 then
        ContainsRefusalMarker = 1;
        exit;
    endif;
    ContainsRefusalMarker = 0;
end;


PROC F4LISTING_LEVEL
{ Level-scope preproc placeholder. Settings populated by 101_login at
  sign-in time (FACILITY_TARGET tier mapping, LGU + barangay assignments)
  are read in REC_LISTING_CONTROL.preproc once the case opens. }


PROC REC_LISTING_CONTROL
preproc
    { Default SURVEY_CODE for routing in paradata -- distinct from F4
      so paradata collators route F4 listings separately from F4 cases. }
    SURVEY_CODE = "F4L";

    { Initialize counters to zero. }
    LISTED_COUNT   = 0;
    REFUSED_COUNT  = 0;
    EXCLUDED_COUNT = 0;

    { Default replacement reserves per Carl's Q2 decision = 10. The
      operator may override on a per-barangay basis if the field
      protocol calls for tighter / looser padding. }
    if REPLACEMENT_RESERVES = 0 then
        REPLACEMENT_RESERVES = DEFAULT_REPLACEMENT_RESERVES;
    endif;

    SESSION_STATUS = 1;   { In progress }


PROC TIME_SESSION_START
onfocus
    { Seed the session PRNG when the operator confirms session start.
      Seed inputs per Carl's Q8 = ENUMERATOR_ID + DATE_SESSION +
      TIME_SESSION_START + BARANGAY_CODE. BARANGAY_CODE may not yet be
      entered at this point if the operator works the form top-to-
      bottom -- in that case the seed is recomputed at LISTING_SOURCE
      onfocus (which forces the operator to have already entered the
      barangay). }

    SeedSessionPRNG(ENUMERATOR_ID, DATE_SESSION, TIME_SESSION_START,
                    BARANGAY_CODE);


PROC LISTING_SOURCE
onfocus
    { Re-seed once BARANGAY_CODE is confirmed (it sits above
      LISTING_SOURCE in the form sequence). }
    SeedSessionPRNG(ENUMERATOR_ID, DATE_SESSION, TIME_SESSION_START,
                    BARANGAY_CODE);

postproc
    { Q1 hybrid-model cross-check. If the operator marks
      LISTING_SOURCE=1 (captain-supplied, primary path) but the
      FRAME_NOTES contains markers of captain refusal / list missing,
      the operator probably meant LISTING_SOURCE=2 (fresh door-to-
      door). Soft warnmsg only -- the operator may continue with the
      original value if intentional. }

    if LISTING_SOURCE = 1 and ContainsRefusalMarker(FRAME_NOTES) then
        warnmsg("LISTING_SOURCE is set to 1 (captain-supplied) but "
                "FRAME_NOTES mentions captain refused / list missing. "
                "Confirm: should this be LISTING_SOURCE = 2 (fresh "
                "door-to-door)? Press Enter to keep current value, or "
                "go back and change.");
    endif;


PROC REC_LISTING_BRGY_FRAME
preproc
    { Defaults for a new roster occurrence. }
    F4_STATUS = 0;                 { Pending -- F4 entry app moves this }
    LISTING_NO = totocc(REC_LISTING_BRGY_FRAME);

    { FROM_RESERVE_POOL defaults to 2 (No) -- the supervisor-side
      dashboard rule kicks in only after this 1-indexed sequence
      exceeds FRAME_TARGET. Operator marks 1 (Yes) when replacing a
      refused / non-contacted primary-frame row. }
    if FROM_RESERVE_POOL = 0 then
        FROM_RESERVE_POOL = 2;
    endif;

    { ASSIGNED_F4_CASE_SEQ remains 0 until F4 preproc consumes this
      roster occurrence and stamps the assigned slot back. }


PROC HH_ELIGIBLE
postproc
    { Bump the matching session counter when the operator confirms
      eligibility. Per the F4 listing semantics:
        HH_ELIGIBLE = 1 (eligible)    -> listed   (LISTED_COUNT++)
        HH_ELIGIBLE = 2 (ineligible)  -> excluded (EXCLUDED_COUNT++)
      Refused-to-list rows (operator backs out of the row at the head-
      name field) are tracked via REFUSED_COUNT incremented at the
      operator's discretion via the explicit refuse-and-skip path
      (not yet wired -- E2-F4LIST-005). }

    if HH_ELIGIBLE = 1 then
        IncrementSessionCounter("listed");
    elseif HH_ELIGIBLE = 2 then
        IncrementSessionCounter("excluded");
    endif;


PROC SESSION_STATUS
postproc
    { When the operator closes the session (status changes from 1 to
      anything else), trigger sync. Per SYNC.md, the listing app
      pushes the session .csdb to CSWeb under:
        f4_listing/<env>/<RR><PP><MMM><FF>/<YYYYMMDD>/<BARANGAY10>/<SSS>.csdb
      so F4 tablets can read it via the EXTERNAL dictionary mechanism
      at interview time. BARANGAY_CODE is a separate path segment
      derived from REC_LISTING_CONTROL.BARANGAY_CODE per Carl's Q3
      sync-path-encoding plan. }

    if SESSION_STATUS = 1 then
        exit;   { still in progress -- no sync }
    endif;

    { Build the remote path from the ID block + BARANGAY_CODE. Same
      %02d / %03d / %08d / %010d specifiers as the case-ID concatenation
      in shared/Capture-Helpers.apc::CAPTURE_VERIFICATION_PHOTO. }
    string facilityPrefix =
        maketext("%02d", REGION_CODE) +
        maketext("%02d", PROVINCE_HUC_CODE) +
        maketext("%03d", CITY_MUNICIPALITY_CODE) +
        maketext("%02d", FACILITY_NO);

    string remotePath =
        "f4_listing/" + userpref("env") + "/" +
        facilityPrefix + "/" +
        maketext("%08d", LISTING_SESSION_DATE) + "/" +
        maketext("%010d", BARANGAY_CODE) + "/" +
        maketext("%03d", LISTING_SESSION_SEQ) + ".csdb";

    { Snapshot session end-time for the audit trail. }
    if TIME_SESSION_END = 0 then
        TIME_SESSION_END = SYSTIME("HHMMSS");
    endif;

    { Synchronize the current case .csdb to CSWeb at the remote path.
      synchronize_file() is CSPro's built-in directive -- see CSPro 8.0
      Users Guide -> Synchronization -> File-mode sync. }
    if not synchronize_file(remotePath) then
        errmsg("F4 listing-session sync FAILED for remote path %s. "
               "The session has been saved locally and will retry "
               "on next Synchronize -> Send data. Inform the STL.",
               remotePath);
    endif;
'''


def main():
    (HERE / "F4Listing.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote F4Listing.ent.apc ({len(APC)} chars; frame builder + sync + LISTING_SOURCE warnmsg)")


if __name__ == "__main__":
    main()
