"""generate_apc.py — emit PatientListing.ent.apc.

Logic for the F3 patient-listing app. Commit 7 lands the random-interval
cadence engine + roster bookkeeping; the commit-8 follow-up appends the
auto-tag PROC.

Structure:
  PROC GLOBAL                          — named constants + helper functions
  PROC PATIENTLISTING_LEVEL            — level preproc (compute BACKUP_TARGET,
                                         load settings, seed PRNG)
  PROC REC_LISTING_CONTROL             — session header preproc (capture
                                         session start time, set defaults)
  PROC REC_RANDOM_INTERVAL_LOG         — engine: draw interval, wait, fire
                                         trigger, record outcome
  PROC REC_PATIENT_ROSTER              — per-listed-patient preproc
                                         (auto-tag rule wired in commit 8)
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'PatientListing' logic file generated by CSPro }
{ F3 Patient Listing CAPI app — random-interval engine + roster bookkeeping. }
{ Commit 7 of 12: cadence engine + roster preproc skeleton.                  }
{ Commit 8 will append the PROC LISTING_TAG auto-tag rule + seq assignment. }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Named constants (tunable; do not change at runtime) ------------- }
{                                                                       }
{ CADENCE_HARD_MIN_SEC / CADENCE_HARD_MAX_SEC are absolute bounds the   }
{ engine refuses to leave even if the session-header config tries to   }
{ widen further. Hard floor: 60 sec (1 min) so the engine cannot fire  }
{ faster than a person can list one patient. Hard ceiling: 14400 sec   }
{ (4 hours) to keep within a single facility-day session.              }

numeric CADENCE_HARD_MIN_SEC = 60;
numeric CADENCE_HARD_MAX_SEC = 14400;

{ Replacement-protocol partitioning, mirrored from
  shared/cspro_helpers.py::CASE_SEQ_*_RANGE. Kept here as APC constants
  so the listing app can self-document the F-series CASE_SEQ landscape
  for desk reviewers reading the source. The listing app itself does
  not assign F-series CASE_SEQ — F3/F4 preproc handles that when they
  consume the roster. }
numeric SEQ_ACTIVE_LO      =   1;
numeric SEQ_ACTIVE_HI      = 699;
numeric SEQ_REPLACEMENT_LO = 700;
numeric SEQ_REPLACEMENT_HI = 899;
numeric SEQ_REFUSED_LO     = 900;
numeric SEQ_REFUSED_HI     = 999;

{ ---- Internal state -------------------------------------------------- }
{ Tracked at PROC GLOBAL scope because CSPro level variables are        }
{ wiped between cases. These are valid for one session only.            }
numeric g_cycle_no        = 0;     { 1-based cycle index within session }
numeric g_session_seed    = 0;     { PRNG seed for this session         }

{ ---- Random-interval engine ----------------------------------------- }

function DrawRandomInterval(numeric minSec, numeric maxSec)
    { Returns a pseudorandom interval in [minSec, maxSec] inclusive.
      Honors CADENCE_HARD_* clamps. Uses CSPro's rand() — a 32-bit
      Mersenne-Twister-class generator seeded via seed() below.

      Audit trail: caller is expected to write the returned value to
      RI_INTERVAL_SEC of a freshly-added REC_RANDOM_INTERVAL_LOG
      occurrence (no side effects here so the function is testable). }

    numeric lo = max(minSec, CADENCE_HARD_MIN_SEC);
    numeric hi = min(maxSec, CADENCE_HARD_MAX_SEC);
    if hi <= lo then
        DrawRandomInterval = lo;
        exit;
    endif;

    numeric span = hi - lo + 1;
    numeric draw = lo + (rand() % span);
    DrawRandomInterval = draw;
end;


function SeedSessionPRNG(numeric enumeratorId, numeric dateSession, numeric timeStart)
    { Derive a per-session seed from enumerator + date + start-time.
      Stored in g_session_seed so RI log occurrences can snapshot it.

      Determinism: same (enumerator, date, time-of-day) -> same seed
      sequence. That is intentional so the cadence is reproducible
      for desk-audit re-runs. The seed is NOT a security claim — it
      is an audit trail. }

    numeric s = (enumeratorId * 100000000) + dateSession + timeStart;
    { Fold to 32-bit unsigned range; CSPro seed() accepts any numeric. }
    g_session_seed = s % 4294967295;
    seed(g_session_seed);
end;


function NextCycle()
    { Increment cycle counter and return the new value. Caller writes it
      to RI_CYCLE_NO of the newly-added log occurrence. }
    g_cycle_no = g_cycle_no + 1;
    NextCycle = g_cycle_no;
end;


{ ---- Roster bookkeeping -------------------------------------------- }

function IncrementSessionCounter(string outcome)
    { Bump the session-header running counter that matches the cycle
      outcome. Counter names match REC_LISTING_CONTROL items. }

    if outcome = "listed" then
        LISTED_COUNT = LISTED_COUNT + 1;
    elseif outcome = "refused" then
        REFUSED_COUNT = REFUSED_COUNT + 1;
    elseif outcome = "excluded" then
        EXCLUDED_COUNT = EXCLUDED_COUNT + 1;
    endif;
end;


function ComputeBackupTarget(numeric facilityTarget)
    { BACKUP_TARGET := ceil(0.5 * facilityTarget), minimum 1.
      Implemented without floor() reliance — CSPro's div() truncates
      toward zero, so we add 1 unless the half was exact. }

    numeric half = facilityTarget / 2;
    numeric truncHalf = trunc(half);
    numeric backup = truncHalf;
    if (truncHalf * 2) < facilityTarget then
        backup = truncHalf + 1;
    endif;
    if backup < 1 then
        backup = 1;
    endif;
    ComputeBackupTarget = backup;
end;


PROC PATIENTLISTING_LEVEL
{ Level-scope preproc: load per-facility settings via loadsetting()
  before the listing-control form opens. Settings populated by 101_login
  at sign-in time include FACILITY_TARGET, CADENCE_MIN_MIN, CADENCE_MAX_MIN,
  f3_seq_lo, f3_seq_hi, f4_seq_lo, f4_seq_hi (commit 9 / user_roster.xlsx). }


PROC REC_LISTING_CONTROL
preproc
    { Default SURVEY_CODE for routing in paradata. }
    SURVEY_CODE = "F3L";

    { Initialize counters to zero. }
    LISTED_COUNT   = 0;
    REFUSED_COUNT  = 0;
    EXCLUDED_COUNT = 0;

    { Backup target computed from operator-entered FACILITY_TARGET in
      onfocus of FACILITY_TARGET below; placeholder set here so the form
      shows a sensible value if the operator never edits. }
    BACKUP_TARGET = 1;

    SESSION_STATUS = 1;   { In progress }


PROC FACILITY_TARGET
onfocus
    { Recompute BACKUP_TARGET whenever the operator edits FACILITY_TARGET. }
    BACKUP_TARGET = ComputeBackupTarget(FACILITY_TARGET);


PROC TIME_SESSION_START
onfocus
    { Seed the session PRNG when the operator confirms session start. }
    SeedSessionPRNG(ENUMERATOR_ID, DATE_SESSION, TIME_SESSION_START);


PROC REC_RANDOM_INTERVAL_LOG
preproc
    { Each new occurrence is one wait-and-list cycle. }
    RI_CYCLE_NO   = NextCycle();
    RI_SEED_USED  = g_session_seed;
    { RI_INTERVAL_SEC drawn in onfocus of the interval item once the
      operator confirms the cycle has begun. }


PROC RI_INTERVAL_SEC
onfocus
    { Draw the random interval for this cycle. Cadence min/max come from
      the session header (set per-facility-tier by 101_login). }
    RI_INTERVAL_SEC = DrawRandomInterval(CADENCE_MIN_MIN * 60,
                                         CADENCE_MAX_MIN * 60);


PROC RI_OUTCOME
postproc
    { Bump the matching session counter when the operator confirms outcome. }
    if RI_OUTCOME = 1 then
        IncrementSessionCounter("listed");
    elseif RI_OUTCOME = 2 then
        IncrementSessionCounter("refused");
    elseif RI_OUTCOME = 3 then
        IncrementSessionCounter("excluded");
    endif;
    { RI_OUTCOME = 4 (timeout) does NOT increment any counter — the
      cycle produced no patient and no refusal to log. }


PROC REC_PATIENT_ROSTER
preproc
    { Defaults for a new roster occurrence. }
    F3_STATUS = 0;   { Pending }
    F4_STATUS = 0;   { Pending — overridden to 9 when LISTING_TAG = 1 or 3 }
    ROSTER_SEQ = totocc(REC_PATIENT_ROSTER);

    { ASSIGNED_F3_CASE_SEQ / ASSIGNED_F4_CASE_SEQ remain 0 until F3/F4
      preproc consumes this roster occurrence and stamps the assigned
      slot back. }

    { LISTING_TAG computed by PROC LISTING_TAG in commit 8 — invoked
      from postproc of CONTACT_VERIFIED once all triage inputs are
      captured. Until commit 8 lands, LISTING_TAG must be entered
      manually by the operator as a temporary fallback. }
'''


def main():
    (HERE / "PatientListing.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote PatientListing.ent.apc ({len(APC)} chars; cadence engine + roster preproc)")


if __name__ == "__main__":
    main()
