import { describe, expect, it } from 'vitest';
import { emitItems } from './emit-items';
import type { ParseResult } from './types';

const dual = (en: string) => ({ en, fil: en });

describe('emitItems', () => {
  it('emits a module that exports sectionA and sections', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: dual('Healthcare Worker Profile'),
          preamble: dual('A preamble'),
          items: [
            {
              id: 'Q3',
              section: 'A',
              type: 'single',
              required: true,
              label: dual('What is your sex at birth?'),
              hasOtherSpecify: false,
              choices: [
                { label: dual('Male'), value: 'Male' },
                { label: dual('Female'), value: 'Female' },
              ],
            },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);

    expect(code).toContain('// AUTOGENERATED — do not edit by hand.');
    expect(code).toContain("import type { Section } from '@/types/survey';");
    expect(code).toContain('export const sectionA: Section = {');
    expect(code).toContain("id: 'A'");
    expect(code).toContain(
      "title: { en: 'Healthcare Worker Profile', fil: 'Healthcare Worker Profile' }",
    );
    expect(code).toContain("preamble: { en: 'A preamble', fil: 'A preamble' }");
    expect(code).toContain("id: 'Q3'");
    expect(code).toContain(
      "label: { en: 'What is your sex at birth?', fil: 'What is your sex at birth?' }",
    );
    expect(code).toContain('export const sections: Section[] = [sectionA];');
  });

  it('escapes single quotes and backslashes in labels', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: dual("Mark's section"),
          items: [
            {
              id: 'Q1',
              section: 'A',
              type: 'short-text',
              required: true,
              label: dual("Don't answer if C:\\Windows"),
            },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);
    expect(code).toContain("title: { en: 'Mark\\'s section', fil: 'Mark\\'s section' }");
    expect(code).toContain(
      "label: { en: 'Don\\'t answer if C:\\\\Windows', fil: 'Don\\'t answer if C:\\\\Windows' }",
    );
  });

  it('omits optional fields when absent', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: dual('A'),
          items: [
            { id: 'Q1', section: 'A', type: 'short-text', required: false, label: dual('Plain') },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);
    expect(code).not.toContain('preamble:');
    expect(code).not.toContain('choices:');
    expect(code).not.toContain('hasOtherSpecify:');
    expect(code).not.toContain('legacyId:');
  });

  it('emits items: [] (not [,]) for sections with zero supported items', () => {
    const result: ParseResult = {
      sections: [{ id: 'J', title: dual('Job Satisfaction'), items: [] }],
      unsupported: [],
    };
    const code = emitItems(result);
    expect(code).toContain('items: []');
    expect(code).not.toContain('items: [,]');
  });

  it('includes an unsupported block as a comment when items are skipped', () => {
    const result: ParseResult = {
      sections: [{ id: 'A', title: dual('A'), items: [] }],
      unsupported: [{ id: 'Q1', section: 'A', rawType: 'section-break', reason: 'section break' }],
    };
    const code = emitItems(result);
    expect(code).toContain('// unsupported items (skipped):');
    expect(code).toContain('// - A.Q1 (section-break): section break');
  });

  // aug17 migration (Task 3.1): the Aug-17 instrument renumbers Q1–Q124
  // continuously — the Apr-20 PDF's Q108 numbering gap no longer exists.
  // No id should ever get a displayNumber override now; the renderer falls
  // back to the item's own id for display.
  it('emits no displayNumber override for an id above the old numbering gap', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'J',
          title: dual('Job Satisfaction'),
          items: [
            {
              id: 'Q109',
              section: 'J',
              type: 'multi',
              required: true,
              label: dual('What additional resources do you need to perform well in this job?'),
              hasOtherSpecify: true,
              choices: [{ label: dual('Better compensation policies'), value: 'Better compensation policies' }],
            },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);
    expect(code).toContain("id: 'Q109'");
    expect(code).not.toContain('displayNumber:');
  });

  it('serialises subFields onto multi-field items', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: dual('A'),
          items: [
            {
              id: 'Q1',
              section: 'A',
              type: 'multi-field',
              required: true,
              label: dual('name'),
              subFields: [
                { id: 'Q1_1', label: dual('Last'), kind: 'short-text' },
                { id: 'Q1_2', label: dual('First'), kind: 'short-text' },
              ],
            },
          ],
        },
      ],
      unsupported: [],
    };
    const out = emitItems(result);
    expect(out).toContain(
      "subFields: [{ id: 'Q1_1', label: { en: 'Last', fil: 'Last' }, kind: 'short-text' }, { id: 'Q1_2', label: { en: 'First', fil: 'First' }, kind: 'short-text' }]",
    );
  });
});
