import type { Item, ParseResult, Section } from './types';

export function emitSchema(result: ParseResult): string {
  const header = [
    '// AUTOGENERATED — do not edit by hand.',
    '// Regenerate via `npm run generate`.',
    "import { z } from 'zod';",
    '',
  ].join('\n');

  const body = result.sections.map(emitSectionSchema).join('\n\n');
  return [header, body, ''].join('\n');
}

function emitSectionSchema(section: Section): string {
  const fieldLines = section.items.flatMap(emitFieldEntries).map((l) => `  ${l}`);
  const objectLiteral = `z.object({\n${fieldLines.join('\n')}\n})`;
  const constName = `section${section.id}Schema`;
  const typeName = `Section${section.id}Values`;
  return [
    `export const ${constName} = ${objectLiteral};`,
    `export type ${typeName} = z.infer<typeof ${constName}>;`,
  ].join('\n');
}

function emitFieldEntries(item: Item): string[] {
  const primary = `${item.id}: ${fieldSchema(item)},`;
  if (item.hasOtherSpecify) {
    return [primary, `${item.id}_other: z.string().optional(),`];
  }
  return [primary];
}

function fieldSchema(item: Item): string {
  switch (item.type) {
    case 'short-text':
    case 'long-text':
      return item.required ? 'z.string().min(1)' : 'z.string().optional()';
    case 'number': {
      let expr = 'z.coerce.number()';
      if (item.min !== undefined) expr += `.min(${item.min})`;
      if (item.max !== undefined) expr += `.max(${item.max})`;
      if (!item.required) expr += '.optional()';
      return expr;
    }
    case 'single': {
      const values = (item.choices ?? []).map((c) => `'${c.value.replace(/'/g, "\\'")}'`);
      const base = `z.enum([${values.join(', ')}])`;
      return item.required ? base : `${base}.optional()`;
    }
  }
}
