import { describe, expect, it } from 'vitest';
import { emitItems } from './emit-items';
import type { ParseResult } from './types';

describe('emitItems', () => {
  it('emits a module that exports sectionA and sections', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: 'Healthcare Worker Profile',
          preamble: 'A preamble',
          items: [
            {
              id: 'Q3',
              section: 'A',
              type: 'single',
              required: true,
              label: 'What is your sex at birth?',
              hasOtherSpecify: false,
              choices: [
                { label: 'Male', value: 'Male' },
                { label: 'Female', value: 'Female' },
              ],
            },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);

    expect(code).toContain('// AUTOGENERATED — do not edit by hand.');
    expect(code).toContain("import type { Section } from '@/types/survey';");
    expect(code).toContain('export const sectionA: Section = {');
    expect(code).toContain("id: 'A'");
    expect(code).toContain("title: 'Healthcare Worker Profile'");
    expect(code).toContain("preamble: 'A preamble'");
    expect(code).toContain("id: 'Q3'");
    expect(code).toContain("label: 'What is your sex at birth?'");
    expect(code).toContain('export const sections: Section[] = [sectionA];');
  });

  it('escapes single quotes and backslashes in labels', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: "Mark's section",
          items: [
            {
              id: 'Q1',
              section: 'A',
              type: 'short-text',
              required: true,
              label: "Don't answer if C:\\Windows",
            },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);
    expect(code).toContain("title: 'Mark\\'s section'");
    expect(code).toContain("label: 'Don\\'t answer if C:\\\\Windows'");
  });

  it('omits optional fields when absent', () => {
    const result: ParseResult = {
      sections: [
        {
          id: 'A',
          title: 'A',
          items: [
            { id: 'Q1', section: 'A', type: 'short-text', required: false, label: 'Plain' },
          ],
        },
      ],
      unsupported: [],
    };

    const code = emitItems(result);
    expect(code).not.toContain('preamble:');
    expect(code).not.toContain('choices:');
    expect(code).not.toContain('hasOtherSpecify:');
    expect(code).not.toContain('legacyId:');
  });

  it('includes an unsupported block as a comment when items are skipped', () => {
    const result: ParseResult = {
      sections: [{ id: 'A', title: 'A', items: [] }],
      unsupported: [{ id: 'Q1', section: 'A', rawType: 'short-text ×3', reason: 'multi-field' }],
    };
    const code = emitItems(result);
    expect(code).toContain('// unsupported items (skipped):');
    expect(code).toContain('// - A.Q1 (short-text ×3): multi-field');
  });
});
