import type { Item, LocalizedString, ParseResult, Section } from './types';

export function emitItems(result: ParseResult): string {
  const header = [
    '// AUTOGENERATED — do not edit by hand.',
    '// Regenerate via `npm run generate`.',
    "import type { Section } from '@/types/survey';",
    '',
  ].join('\n');

  const sectionConsts = result.sections.map(emitSectionConst).join('\n\n');
  const sectionsArrayName = result.sections.map((s) => `section${s.id}`).join(', ');
  const sectionsArray = `export const sections: Section[] = [${sectionsArrayName}];`;

  const unsupportedBlock =
    result.unsupported.length > 0
      ? [
          '',
          '// unsupported items (skipped):',
          ...result.unsupported.map((u) => `// - ${u.section}.${u.id} (${u.rawType}): ${u.reason}`),
        ].join('\n')
      : '';

  return [header, sectionConsts, '', sectionsArray, unsupportedBlock, ''].join('\n');
}

function emitSectionConst(section: Section): string {
  const parts: string[] = [`  id: '${section.id}'`, `  title: ${quoteLocalized(section.title)}`];
  if (section.preamble) parts.push(`  preamble: ${quoteLocalized(section.preamble)}`);
  if (section.items.length === 0) {
    parts.push(`  items: []`);
  } else {
    const itemsLiteral = section.items.map(emitItem).join(',\n    ');
    parts.push(`  items: [\n    ${itemsLiteral},\n  ]`);
  }

  return `export const section${section.id}: Section = {\n${parts.join(',\n')},\n};`;
}

// #519 (retired 2026-08-19, aug17 migration Task 3.1): the Apr-20 PDF numbered
// items Q1–Q125 but omitted Q108 (the numbering jumped Q107→Q109), so `id`
// carried that gap and DISPLAY subtracted one above it. The Aug-17 instrument
// renumbers Q1–Q124 continuously — there is no gap anymore, `id` IS the
// printed number for every item — so this always returns undefined and the
// renderer falls back to the item's own id (see emitItem below). Kept as a
// named function (rather than deleted outright) so a future gap, if the
// paper ever reintroduces one, has an obvious place to land.
function displayNumberFor(_id: string): string | undefined {
  return undefined;
}

function emitItem(item: Item): string {
  const fields: string[] = [`id: '${item.id}'`];
  const dn = displayNumberFor(item.id);
  if (dn) fields.push(`displayNumber: '${dn}'`);
  fields.push(
    `section: '${item.section}'`,
    `type: '${item.type}'`,
    `required: ${item.required}`,
    `label: ${quoteLocalized(item.label)}`,
  );
  if (item.conditional) fields.push(`conditional: true`);
  if (item.legacyId) fields.push(`legacyId: '${item.legacyId}'`);
  if (item.preamble) fields.push(`preamble: ${quoteLocalized(item.preamble)}`);
  if (item.inputLabel) fields.push(`inputLabel: ${quoteLocalized(item.inputLabel)}`);
  if (item.emphasis) fields.push(`emphasis: ${quote(item.emphasis)}`);
  if (item.help) fields.push(`help: ${quoteLocalized(item.help)}`);
  if (item.min !== undefined) fields.push(`min: ${item.min}`);
  if (item.max !== undefined) fields.push(`max: ${item.max}`);
  if (item.hasOtherSpecify) fields.push(`hasOtherSpecify: true`);
  if (item.choices) {
    const choicesLiteral = item.choices
      .map((c) => {
        const flags = [
          c.isOtherSpecify ? ', isOtherSpecify: true' : '',
          c.isExclusive ? ', isExclusive: true' : '',
          c.isSelectAll ? ', isSelectAll: true' : '',
        ].join('');
        return `{ label: ${quoteLocalized(c.label)}, value: ${quote(c.value)}${flags} }`;
      })
      .join(', ');
    fields.push(`choices: [${choicesLiteral}]`);
  }
  if (item.subFields) {
    const subFieldsLiteral = item.subFields
      .map((sf) => {
        const parts = [
          `id: '${sf.id}'`,
          `label: ${quoteLocalized(sf.label)}`,
          `kind: '${sf.kind}'`,
        ];
        if (sf.min !== undefined) parts.push(`min: ${sf.min}`);
        if (sf.max !== undefined) parts.push(`max: ${sf.max}`);
        if (sf.required === false) parts.push(`required: false`);
        return `{ ${parts.join(', ')} }`;
      })
      .join(', ');
    fields.push(`subFields: [${subFieldsLiteral}]`);
  }
  return `{ ${fields.join(', ')} }`;
}

function quote(s: string): string {
  // #826: real newlines (multi-line help) must emit as \n escapes — AFTER the
  // backslash escape so the sequence isn't doubled.
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

// Serialize a LocalizedString, emitting only the locale keys that are present
// (English is always present; dialects appear only when a translation exists).
// Fixed key order keeps generated output stable/diffable across runs.
const LOCALE_KEY_ORDER = ['en', 'fil', 'ceb', 'bis', 'ilo', 'hil', 'war', 'bcl'] as const;
function quoteLocalized(s: LocalizedString): string {
  const parts = LOCALE_KEY_ORDER.filter((k) => typeof s[k] === 'string').map(
    (k) => `${k}: ${quote(s[k] as string)}`,
  );
  return `{ ${parts.join(', ')} }`;
}
