import type { Item, ParseResult, Section } from './types';

const REQUIRED_MESSAGE = 'This field is required.';

export function emitSchema(result: ParseResult): string {
  const header = [
    '// AUTOGENERATED — do not edit by hand.',
    '// Regenerate via `npm run generate`.',
    "import { z } from 'zod';",
    '',
  ].join('\n');

  const body = result.sections.map(emitSectionSchema).join('\n\n');
  return [header, body, ''].join('\n');
}

function emitSectionSchema(section: Section): string {
  const fieldLines = section.items.flatMap(emitFieldEntries).map((l) => `  ${l}`);
  const objectLiteral = `z.object({\n${fieldLines.join('\n')}\n})`;
  const refinement = emitOtherSpecifyRefinement(section);
  const expr = refinement ? `${objectLiteral}${refinement}` : objectLiteral;
  const constName = `section${section.id}Schema`;
  const typeName = `Section${section.id}Values`;
  return [
    `export const ${constName} = ${expr};`,
    `export type ${typeName} = z.infer<typeof ${constName}>;`,
  ].join('\n');
}

function emitOtherSpecifyRefinement(section: Section): string | null {
  const clauses: string[] = [];
  for (const item of section.items) {
    if (!item.hasOtherSpecify || !item.choices) continue;
    // R3 #302: an item can carry MORE THAN ONE "specify other" option
    // (e.g. Q13–Q24 have both "Yes, specify other reason ___" and
    // "No, specify other reason ___", sharing one _other text field).
    // .find() only enforced the first, so picking the other one let the
    // respondent proceed with no reason. Gate on ANY of them.
    const otherChoices = item.choices.filter((c) => c.isOtherSpecify);
    if (otherChoices.length === 0) continue;
    const parentKey = jsAccess(item.id);
    const otherKey = jsAccess(`${item.id}_other`);
    const otherValues = otherChoices.map((c) => c.value.replace(/'/g, "\\'"));
    const single = otherValues.length === 1;
    const valueList = otherValues.map((v) => `'${v}'`).join(', ');
    const condition =
      item.type === 'multi'
        ? single
          ? `Array.isArray(data${parentKey}) && data${parentKey}.includes('${otherValues[0]}')`
          : `Array.isArray(data${parentKey}) && [${valueList}].some((o) => data${parentKey}.includes(o))`
        : single
          ? `data${parentKey} === '${otherValues[0]}'`
          : `[${valueList}].some((o) => data${parentKey} === o)`;
    const filledCheck = `typeof data${otherKey} === 'string' && data${otherKey}.trim().length > 0`;
    const pathLiteral = `['${item.id}_other']`;
    clauses.push(
      [
        `  if (${condition} && !(${filledCheck})) {`,
        `    ctx.addIssue({ code: z.ZodIssueCode.custom, path: ${pathLiteral}, message: 'Please specify' });`,
        `  }`,
      ].join('\n'),
    );
  }
  if (clauses.length === 0) return null;
  return `.superRefine((data, ctx) => {\n${clauses.join('\n')}\n})`;
}

function jsAccess(id: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(id) ? `.${id}` : `['${id}']`;
}

// Conditional items are required-when-shown but absent when hidden, so the schema must
// accept undefined. The runtime (getSectionStatus) blocks completion via item.required.
function isSchemaOptional(item: Item): boolean {
  return !item.required || item.conditional === true;
}

function emitFieldEntries(item: Item): string[] {
  if (item.type === 'multi-field' && item.subFields) {
    const itemOptional = isSchemaOptional(item);
    return item.subFields.map((sf) => {
      // A subfield is schema-optional if (a) the parent is optional, OR
      // (b) the subfield's own required flag is explicitly false.
      const optional = itemOptional || sf.required === false;
      const schema =
        sf.kind === 'short-text'
          ? optional
            ? 'z.string().optional()'
            : 'z.string().min(1)'
          : (() => {
              let expr = `z.coerce.number({ invalid_type_error: '${REQUIRED_MESSAGE}' })`;
              if (sf.min !== undefined) expr += `.min(${sf.min})`;
              if (sf.max !== undefined) expr += `.max(${sf.max})`;
              if (optional) expr += '.optional()';
              return expr;
            })();
      return `${fieldKey(sf.id)}: ${schema},`;
    });
  }
  const key = fieldKey(item.id);
  const primary = `${key}: ${fieldSchema(item)},`;
  if (item.hasOtherSpecify) {
    return [primary, `${fieldKey(`${item.id}_other`)}: z.string().optional(),`];
  }
  return [primary];
}

function fieldKey(id: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(id) ? id : `'${id}'`;
}

function fieldSchema(item: Item): string {
  const optional = isSchemaOptional(item);
  switch (item.type) {
    case 'short-text':
    case 'long-text':
      return optional ? 'z.string().optional()' : 'z.string().min(1)';
    case 'number': {
      let expr = `z.coerce.number({ invalid_type_error: '${REQUIRED_MESSAGE}' })`;
      if (item.min !== undefined) expr += `.min(${item.min})`;
      if (item.max !== undefined) expr += `.max(${item.max})`;
      if (optional) expr += '.optional()';
      return expr;
    }
    case 'single': {
      const values = (item.choices ?? []).map((c) => `'${c.value.replace(/'/g, "\\'")}'`);
      const base = `z.enum([${values.join(', ')}])`;
      return optional ? `${base}.optional()` : base;
    }
    case 'multi': {
      const values = (item.choices ?? []).map((c) => `'${c.value.replace(/'/g, "\\'")}'`);
      const base = `z.array(z.enum([${values.join(', ')}]))`;
      return optional ? `${base}.optional()` : `${base}.min(1)`;
    }
    case 'date': {
      const base = String.raw`z.string().regex(/^\d{4}-\d{2}-\d{2}$/)`;
      return optional ? `${base}.optional()` : base;
    }
    // ISO-8601 variable precision: 'YYYY' | 'YYYY-MM' | 'YYYY-MM-DD'. Year is
    // always required (the leading \d{4}); month + day each optional. Month/day
    // RANGE is constrained by the UI (number inputs 1–12 / 1–31), same trust
    // model as `date` above (whose regex also doesn't range-check). R3 #306.
    case 'partial-date': {
      const base = String.raw`z.string().regex(/^\d{4}(-\d{2}(-\d{2})?)?$/, 'Enter the year (4 digits). Month and day are optional.')`;
      return optional ? `${base}.optional()` : base;
    }
    case 'multi-field':
      throw new Error(
        `multi-field items must be handled in emitFieldEntries, not fieldSchema (item ${item.id})`,
      );
  }
}
