import type { Item, ParseResult, Section } from './types';

export function emitItems(result: ParseResult): string {
  const header = [
    '// AUTOGENERATED — do not edit by hand.',
    '// Regenerate via `npm run generate`.',
    "import type { Section } from '@/types/survey';",
    '',
  ].join('\n');

  const sectionConsts = result.sections.map(emitSectionConst).join('\n\n');
  const sectionsArrayName = result.sections.map((s) => `section${s.id}`).join(', ');
  const sectionsArray = `export const sections: Section[] = [${sectionsArrayName}];`;

  const unsupportedBlock =
    result.unsupported.length > 0
      ? [
          '',
          '// unsupported items (skipped):',
          ...result.unsupported.map((u) => `// - ${u.section}.${u.id} (${u.rawType}): ${u.reason}`),
        ].join('\n')
      : '';

  return [header, sectionConsts, '', sectionsArray, unsupportedBlock, ''].join('\n');
}

function emitSectionConst(section: Section): string {
  const parts: string[] = [`  id: '${section.id}'`, `  title: ${quote(section.title)}`];
  if (section.preamble) parts.push(`  preamble: ${quote(section.preamble)}`);
  if (section.items.length === 0) {
    parts.push(`  items: []`);
  } else {
    const itemsLiteral = section.items.map(emitItem).join(',\n    ');
    parts.push(`  items: [\n    ${itemsLiteral},\n  ]`);
  }

  return `export const section${section.id}: Section = {\n${parts.join(',\n')},\n};`;
}

function emitItem(item: Item): string {
  const fields: string[] = [
    `id: '${item.id}'`,
    `section: '${item.section}'`,
    `type: '${item.type}'`,
    `required: ${item.required}`,
    `label: ${quote(item.label)}`,
  ];
  if (item.legacyId) fields.push(`legacyId: '${item.legacyId}'`);
  if (item.help) fields.push(`help: ${quote(item.help)}`);
  if (item.min !== undefined) fields.push(`min: ${item.min}`);
  if (item.max !== undefined) fields.push(`max: ${item.max}`);
  if (item.hasOtherSpecify) fields.push(`hasOtherSpecify: true`);
  if (item.choices) {
    const choicesLiteral = item.choices
      .map(
        (c) =>
          `{ label: ${quote(c.label)}, value: ${quote(c.value)}${c.isOtherSpecify ? ', isOtherSpecify: true' : ''} }`,
      )
      .join(', ');
    fields.push(`choices: [${choicesLiteral}]`);
  }
  if (item.subFields) {
    const subFieldsLiteral = item.subFields
      .map((sf) => {
        const parts = [`id: '${sf.id}'`, `label: ${quote(sf.label)}`, `kind: '${sf.kind}'`];
        if (sf.min !== undefined) parts.push(`min: ${sf.min}`);
        if (sf.max !== undefined) parts.push(`max: ${sf.max}`);
        return `{ ${parts.join(', ')} }`;
      })
      .join(', ');
    fields.push(`subFields: [${subFieldsLiteral}]`);
  }
  return `{ ${fields.join(', ')} }`;
}

function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}
