import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const ORDER = [
  'src/Schema.js',
  'src/Util.js',
  'src/Auth.js',
  'src/Idempotency.js',
  'src/Handlers.js',
  'src/AdminHandlers.js',
  'src/AdminEncoder.js',
  'src/AdminData.js',
  'src/AdminReports.js',
  'src/AdminUsers.js',
  'src/AdminRoles.js',
  'src/AdminFiles.js',
  'src/Router.js',
  'apps-script/Setup.js',
  // apps-script/AdminGlue.js was removed in PR #31 (auth re-arch).
  'apps-script/Migrations.js',
  'apps-script/AdminAudit.js',
  'apps-script/AdminHCWs.js',
  'apps-script/Code.js',
];

function stripCjsExport(source) {
  return source.replace(/\n?if \(typeof module !== ['"]undefined['"]\)[\s\S]*$/, '\n');
}

async function main() {
  const parts = [];
  parts.push('// AUTOGENERATED by scripts/build.mjs — do not edit by hand.');
  parts.push('// Regenerate with `npm run build` inside deliverables/F2/PWA/backend/.');
  parts.push(`// Built: ${new Date().toISOString()}`);
  parts.push('');

  for (const rel of ORDER) {
    const abs = resolve(root, rel);
    if (!existsSync(abs)) throw new Error(`Missing source file: ${rel}`);
    const source = await readFile(abs, 'utf8');
    parts.push(`// ===== ${rel} =====`);
    parts.push(stripCjsExport(source).trim());
    parts.push('');
  }

  const distDir = resolve(root, 'dist');
  await mkdir(distDir, { recursive: true });
  const outPath = resolve(distDir, 'Code.gs');
  await writeFile(outPath, parts.join('\n'), 'utf8');

  const manifest = await readFile(resolve(root, 'apps-script/appsscript.json'), 'utf8');
  await writeFile(resolve(distDir, 'appsscript.json'), manifest, 'utf8');

  // Admin.html was removed in PR #31 (auth re-arch — admin UI moved to the
  // Cloudflare Worker / Pages frontend). The copy step is a no-op now.

  console.log(`Wrote ${outPath} (${parts.join('\n').length} chars)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
