<?php
/**
 * Who is signed in, and what can they reach.        Carl; reshimmed 2026-08-09
 * Deploy to /opt/app/lamp/www/docs/whoami.php
 *
 * The gated surfaces (dashboard, map, data room) are static HTML regenerated by
 * cron, so they cannot know the viewer at build time. They fetch this to fill
 * the "signed in as … · Sign out" chip in the topbar.
 *
 * E9-ADMIN-032 — WHY THIS IS NOW A SHIM
 * This file has a second job that is easy to miss: it is the `/_capi_auth`
 * subrequest target for `location /` in the capi vhost, so its status code is
 * what gates the whole static portal. It used to answer purely from
 * REMOTE_USER / PHP_AUTH_USER, both of which go EMPTY the moment mod_auth_form
 * is retired — at which point it would 401 forever and bounce every visitor to
 * a sign-in page in a loop.
 *
 * So it now answers from the identity provider first and the legacy variables
 * second. That makes it correct before the cutover (nobody has an IdP session
 * yet, so the fallback answers, exactly as today) and correct after it (the
 * fallback is empty, so the provider answers). No flag day, and the file can
 * be deleted later once every generated page fetches /docs/idp/me instead.
 *
 * Tier is the same admin > staff > field precedence as before, but derived
 * from permissions rather than from `Require user` lines in .htaccess — those
 * lines are deleted at cutover, and a tier derived from a file nothing reads
 * is a tier that silently becomes "none" for everybody.
 */
declare(strict_types=1);
ini_set('display_errors', '0');

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');

$LIB = is_dir('/var/www/private/capi-auth') ? '/var/www/private/capi-auth' : __DIR__;

// ---------------------------------------------------------------------------
// 1. The identity provider, if it has a session for this cookie.
// ---------------------------------------------------------------------------
if (is_file($LIB . '/lib.php')) {
    try {
        require_once $LIB . '/lib.php';
        $sess = auth_session_resolve($_COOKIE[AUTH_COOKIE] ?? null);
        if ($sess !== null) {
            $perms = $sess['perms'];
            $can = [
                'monitoring'  => in_array('monitoring.view', $perms, true),
                'cases'       => in_array('case.view', $perms, true),
                'data_room'   => in_array('data.export', $perms, true),
                'tabulations' => in_array('tabulations.view', $perms, true),
                'admin'       => in_array('admin.system', $perms, true)
                              || in_array('admin.users', $perms, true),
                'audit'       => in_array('audit.view', $perms, true),
            ];
            $tier = 'none';
            if ($can['monitoring']) { $tier = 'field'; }
            if ($can['data_room'])  { $tier = 'staff'; }
            if ($can['admin'])      { $tier = 'admin'; }

            echo json_encode([
                'signed_in' => true,
                'user'      => $sess['username'],
                'tier'      => $tier,
                'can'       => $can,
                // Stays the legacy path on purpose: it is baked into every
                // generated topbar, is PUBLIC in the ACL, and becomes a 302 to
                // /docs/idp/logout at cutover. Nothing needs regenerating.
                'logout'    => '/docs/auth/logout',
                'source'    => 'idp',
            ], JSON_UNESCAPED_SLASHES);
            exit;
        }
    } catch (Throwable $e) {
        // Provider unreachable. Fall through to the legacy path rather than
        // 401ing — while mod_auth_form is still live that is a real answer,
        // and this endpoint gates the entire static portal.
        error_log('capi-whoami: provider unavailable: ' . $e->getMessage());
    }
}

// ---------------------------------------------------------------------------
// 2. Legacy: mod_auth_form / basic auth. Empty after cutover, by design.
// ---------------------------------------------------------------------------
$user = $_SERVER['REMOTE_USER'] ?? $_SERVER['PHP_AUTH_USER'] ?? '';
if ($user === '') {
    http_response_code(401);
    echo json_encode(['user' => null, 'signed_in' => false]);
    exit;
}

/** Pull the usernames off every `Require user` line in a gate file. */
function gate_users(string $path): array {
    $raw = @file_get_contents($path);
    if (!is_string($raw) || $raw === '') { return []; }
    $out = [];
    foreach (preg_split('/\R/', $raw) as $line) {
        // NOTE: these lines are written with two leading spaces by the admin
        // console, so anchoring on ^Require would silently miss them.
        if (preg_match('/^\s*Require\s+user\s+(.+)$/i', $line, $m)) {
            foreach (preg_split('/\s+/', trim($m[1])) as $u) {
                if ($u !== '') { $out[] = $u; }
            }
        }
    }
    return $out;
}

$root = '/var/www/html/docs';
$monitoring = gate_users($root . '/.htaccess');
$dataRoom   = gate_users($root . '/data/.htaccess');
$adminC     = gate_users($root . '/admin/.htaccess');

$can = [
    'monitoring' => in_array($user, $monitoring, true),
    'data_room'  => in_array($user, $dataRoom, true),
    'admin'      => in_array($user, $adminC, true),
];

if ($can['admin'])          { $tier = 'admin'; }
elseif ($can['data_room'])  { $tier = 'staff'; }
elseif ($can['monitoring']) { $tier = 'field'; }
else                        { $tier = 'none'; }

echo json_encode([
    'signed_in' => true,
    'user'      => $user,
    'tier'      => $tier,
    'can'       => $can,
    'logout'    => '/docs/auth/logout',
    'source'    => 'htaccess',
], JSON_UNESCAPED_SLASHES);
