* 00_import.do - bring the harmonization-ETL CSVs into Stata 12 .dta files
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
* WHY insheet: the ETL (transform.py) does not emit .dta yet (transform.py section 0.3
* TODO); and Stata 13+'s newer delimited importer does NOT exist in Stata 12,
* so -insheet- is the Stata-12-native path.
version 12

* ================= EDIT ME =================
* Point ETL_DIR at the harmonization ETL output snapshot you want to tabulate:
*   deliverables/data-harmonization/etl/out/<date>
global ETL_DIR "../../data-harmonization/etl/out/2026-06-12"
* ===========================================

insheet using "$ETL_DIR/f1_clean.csv", comma names case clear
save "$DATA_DIR/f1.dta", replace

insheet using "$ETL_DIR/f3_clean.csv", comma names case clear
save "$DATA_DIR/f3.dta", replace

insheet using "$ETL_DIR/f4_clean.csv", comma names case clear
save "$DATA_DIR/f4.dta", replace

insheet using "$ETL_DIR/f4_roster_clean.csv", comma names case clear
save "$DATA_DIR/f4_roster.dta", replace

insheet using "$ETL_DIR/shared_dimensions.csv", comma names case clear
save "$DATA_DIR/shared_dimensions.dta", replace

* ---- TODO: not in the ETL yet - stubbed with capture guards ----
* F2 (HCW census) clean extract does not exist in the ETL yet:
capture confirm file "$ETL_DIR/f2_clean.csv"
if _rc == 0 {
    insheet using "$ETL_DIR/f2_clean.csv", comma names case clear
    save "$DATA_DIR/f2.dta", replace
}
else {
    display as error "TODO: f2_clean.csv not in ETL output yet - Annex 4 will be skipped"
}

* F3 pay/expenditure roster extracts do not exist in the ETL yet:
capture confirm file "$ETL_DIR/f3_roster_clean.csv"
if _rc == 0 {
    insheet using "$ETL_DIR/f3_roster_clean.csv", comma names case clear
    save "$DATA_DIR/f3_roster.dta", replace
}
else {
    display as error "TODO: f3 roster extract not in ETL output yet - roster tables stay stubbed"
}
