* 01_svyset.do - per-instrument survey designs (SSRCS Annex A)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
version 12

* ============================ LOUD TODO =====================================
* WEIGHTS DO NOT EXIST YET. Sampling weights (wf) are computed POST-COLLECTION
* from the realized sample. Until then run UNWEIGHTED via the NOWEIGHT toggle
* in run.do (global NOWEIGHT 1), which svysets each file as SRS (_n) so every
* svy: command still runs. When wf lands: merge it onto each .dta, construct
* the strata/fpc variables flagged below, set NOWEIGHT 0, and re-run.
* ============================================================================

* ---------------- F1 - facility survey ----------------
* SSRCS Annex A design: STRATIFIED SINGLE-STAGE sample of facilities;
* strata = facility-type x province; with finite-population correction.
use "$DATA_DIR/f1.dta", clear
if "$NOWEIGHT" == "1" {
    svyset _n
}
else {
    * TODO construct before use:  egen strata_f1 = group(f_type province_huc)
    * TODO construct before use:  fpc_f1 = facilities in stratum (master list)
    svyset facility_id [pweight=wf], strata(strata_f1) fpc(fpc_f1)
}
save "$DATA_DIR/f1.dta", replace

* ---------------- F3 - patient exit survey ----------------
* SSRCS Annex A design: TWO-STAGE; PSU = facility, patients sampled within.
use "$DATA_DIR/f3.dta", clear
if "$NOWEIGHT" == "1" {
    svyset _n
}
else {
    * TODO construct before use:  egen strata_f3 = group(f_type province_huc)
    svyset facility_id [pweight=wf], strata(strata_f3) || _n
}
save "$DATA_DIR/f3.dta", replace

* ---------------- F4 - household survey ----------------
* SSRCS Annex A design: TWO-STAGE; PSU = barangay, households sampled within.
use "$DATA_DIR/f4.dta", clear
if "$NOWEIGHT" == "1" {
    svyset _n
}
else {
    * TODO construct before use: barangay_psu (PSGC barangay code) + strata_f4
    svyset barangay_psu [pweight=wf], strata(strata_f4) || _n
}
save "$DATA_DIR/f4.dta", replace

* ---------------- F2 - health-care worker survey ----------------
* SSRCS Annex A design: CENSUS of HCWs within sampled facilities - no
* second-phase sampling, so self-weighting (wf=1); svyset as SRS.
capture confirm file "$DATA_DIR/f2.dta"
if _rc == 0 {
    use "$DATA_DIR/f2.dta", clear
    svyset _n
    save "$DATA_DIR/f2.dta", replace
}
else {
    display as error "f2.dta missing (ETL f2_clean.csv TODO) - skipping F2 svyset"
}
