* 10_annex1.do - Annex 1 - F1 facility survey table skeletons (Stata 12)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
version 12

capture erase "$OUT_DIR/annex1_tables.xls"
use "$DATA_DIR/f1.dta", clear

*----- Table 1.1 - Percentage distribution of facility head respondents' who have ever
*       heard of the process to apply for PhilHealth YAKAP/Konsulta accreditation, by facility
*       type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: partial
* PARTIAL: No 'heard of process' item; Q81=know-how-to-start (non-accred only). Fac type
*   all 1.x: F_TYPE+F_OWNERSHIP join on 9-digit facility_id
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q81_know_how_start f_type, col percent
* capture noisily tabout q81_know_how_start f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.2 - Percentage distribution of facility head respondents' reported
*       support from LGU to implement UHC reforms, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q148_lgu_support f_type, col percent
capture noisily tabout q148_lgu_support f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.3 - Percentage distribution of facility head respondents reported type of
*       support from LGU to implement UHC reforms, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* note: Checkbox: one alpha multi-code field; split to dummies in Stata
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q149_lgu_support_forms_XX = strpos(q149_lgu_support_forms, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q149_lgu_support_forms f_type, col percent
* capture noisily tabout q149_lgu_support_forms f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.4 - Percentage distribution of facility head respondents perceived
*       satisfaction with the support received from LGU to implement UHC reforms, by facility
*       type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q150_lgu_satisfied f_type, col percent
capture noisily tabout q150_lgu_satisfied f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.5 - Percentage distribution of facility head respondents reported reasons
*       for dissatisfaction of support from LGU to implement UHC reforms -----
* universe: facility heads dissatisfied with LGU support | breakdown: none stated | status: mapped
* note: Checkbox multi; universe skip-gated to Q150_LGU_SATISFIED=No
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q151_lgu_not_sat_why_XX = strpos(q151_lgu_not_sat_why, "XX") > 0  // one per code
* capture noisily svy: tab q151_lgu_not_sat_why, percent
* capture noisily tabout q151_lgu_not_sat_why using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.6 - Percentage distribution of facility head respondents who have ever
*       heard of the process to apply for DOH licensing, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: gap
* GAP - no source in instrument: No DOH-licensing process-awareness item in F1; nearest
*   are Q118 (licensed status) and Q121 (difficult requirements)

*----- Table 1.7 - Percentage distribution of facility head respondents reported that
*       the facility is currently PhilHealth YAKAP/Konsulta accredited, by facility type
*       (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q51_yk_accred f_type, col percent
capture noisily tabout q51_yk_accred f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.8 - Percentage distribution of facility head respondents identified top
*       barriers in facilities' accreditation to PhilHealth YAKAP/Konsulta, for the most recent
*       application, by type of facility (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* note: Checkbox: one alpha multi-code field, split; accredited/applied path - non-
*   accred reasons live in Q79
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q65_accred_difficult_XX = strpos(q65_accred_difficult, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q65_accred_difficult f_type, col percent
* capture noisily tabout q65_accred_difficult f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.8a - Percentage distribution of facility head respondents of rural health
*       unit reported reasons to barriers in facilities' accreditation to PhilHealth
*       YAKAP/Konsulta, for the most recent application (n=911) -----
* universe: facility heads of rural health units (n=911) | breakdown: none stated | status: mapped
* note: 9-item why-difficult battery, each one alpha multi-code field (split); filter
*   facility_type=RHU
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q66_why_diff_preventive_XX = strpos(q66_why_diff_preventive, "XX") > 0  // one per code
* gen byte q67_why_diff_lab_XX = strpos(q67_why_diff_lab, "XX") > 0  // one per code
* gen byte q68_why_diff_meds_XX = strpos(q68_why_diff_meds, "XX") > 0  // one per code
* gen byte q69_why_diff_infra_XX = strpos(q69_why_diff_infra, "XX") > 0  // one per code
* gen byte q70_why_diff_equipment_XX = strpos(q70_why_diff_equipment, "XX") > 0  // one per code
* gen byte q71_why_diff_hr_XX = strpos(q71_why_diff_hr, "XX") > 0  // one per code
* gen byte q72_why_diff_his_XX = strpos(q72_why_diff_his, "XX") > 0  // one per code
* gen byte q73_why_diff_docs_XX = strpos(q73_why_diff_docs, "XX") > 0  // one per code
* gen byte q74_why_diff_doh_lic_XX = strpos(q74_why_diff_doh_lic, "XX") > 0  // one per code
* capture noisily {
* foreach v in q66_why_diff_preventive q67_why_diff_lab q68_why_diff_meds q69_why_diff_infra q70_why_diff_equipment q71_why_diff_hr q72_why_diff_his q73_why_diff_docs q74_why_diff_doh_lic {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 1.8b - Percentage distribution of facility head respondents of government
*       hospitals reported reasons to barriers in facilities' accreditation to PhilHealth
*       YAKAP/Konsulta, for the most recent application (n=244) -----
* universe: facility heads of government hospitals (n=244) | breakdown: none stated | status:
*   mapped
* note: Same Q66-Q74 battery; filter facility_type=hospital & F_OWNERSHIP=public (gov)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q66_why_diff_preventive_XX = strpos(q66_why_diff_preventive, "XX") > 0  // one per code
* gen byte q67_why_diff_lab_XX = strpos(q67_why_diff_lab, "XX") > 0  // one per code
* gen byte q68_why_diff_meds_XX = strpos(q68_why_diff_meds, "XX") > 0  // one per code
* gen byte q69_why_diff_infra_XX = strpos(q69_why_diff_infra, "XX") > 0  // one per code
* gen byte q70_why_diff_equipment_XX = strpos(q70_why_diff_equipment, "XX") > 0  // one per code
* gen byte q71_why_diff_hr_XX = strpos(q71_why_diff_hr, "XX") > 0  // one per code
* gen byte q72_why_diff_his_XX = strpos(q72_why_diff_his, "XX") > 0  // one per code
* gen byte q73_why_diff_docs_XX = strpos(q73_why_diff_docs, "XX") > 0  // one per code
* gen byte q74_why_diff_doh_lic_XX = strpos(q74_why_diff_doh_lic, "XX") > 0  // one per code
* capture noisily {
* foreach v in q66_why_diff_preventive q67_why_diff_lab q68_why_diff_meds q69_why_diff_infra q70_why_diff_equipment q71_why_diff_hr q72_why_diff_his q73_why_diff_docs q74_why_diff_doh_lic {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 1.8c - Percentage distribution of facility head respondents of private
*       hospitals reported reasons to barriers in facilities' accreditation to PhilHealth
*       YAKAP/Konsulta, for the most recent application (n=366) -----
* universe: facility heads of private hospitals (n=366) | breakdown: none stated | status: mapped
* note: Same Q66-Q74 battery; filter facility_type=hospital & F_OWNERSHIP=private
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q66_why_diff_preventive_XX = strpos(q66_why_diff_preventive, "XX") > 0  // one per code
* gen byte q67_why_diff_lab_XX = strpos(q67_why_diff_lab, "XX") > 0  // one per code
* gen byte q68_why_diff_meds_XX = strpos(q68_why_diff_meds, "XX") > 0  // one per code
* gen byte q69_why_diff_infra_XX = strpos(q69_why_diff_infra, "XX") > 0  // one per code
* gen byte q70_why_diff_equipment_XX = strpos(q70_why_diff_equipment, "XX") > 0  // one per code
* gen byte q71_why_diff_hr_XX = strpos(q71_why_diff_hr, "XX") > 0  // one per code
* gen byte q72_why_diff_his_XX = strpos(q72_why_diff_his, "XX") > 0  // one per code
* gen byte q73_why_diff_docs_XX = strpos(q73_why_diff_docs, "XX") > 0  // one per code
* gen byte q74_why_diff_doh_lic_XX = strpos(q74_why_diff_doh_lic, "XX") > 0  // one per code
* capture noisily {
* foreach v in q66_why_diff_preventive q67_why_diff_lab q68_why_diff_meds q69_why_diff_infra q70_why_diff_equipment q71_why_diff_hr q72_why_diff_his q73_why_diff_docs q74_why_diff_doh_lic {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 1.9 - Percentage distribution of the average number of days to PhilHealth
*       YAKAP/Konsulta accreditation for the facility's most recent application, by facility
*       type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* note: Q63 captures wait in MONTHS, not days (table title says days) - report months or
*   convert
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q63_accred_wait f_type, col percent
capture noisily tabout q63_accred_wait f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.10 - Percentage distribution of basic services outsourced by
*       YAKAP/Konsulta provider or primary care providers, over the past 6 months, by facility
*       type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: partial
* PARTIAL: No 'services outsourced' item; Q160=where patients go for unavailable
*   services is nearest proxy; no 6-mo window
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q160_external_services_go_XX = strpos(q160_external_services_go, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q160_external_services_go f_type, col percent
* capture noisily tabout q160_external_services_go f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.11 - Percentage distribution of top methods of outbound referral, by
*       facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* note: Checkbox multi; split to dummies
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q155_send_referral_how_XX = strpos(q155_send_referral_how, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q155_send_referral_how f_type, col percent
* capture noisily tabout q155_send_referral_how f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.12 - Percentage distribution of top methods of inbound referral of
*       hospitals, by facility type (n=1,521) -----
* universe: hospitals | breakdown: by facility type | status: mapped
* note: Checkbox multi; inbound-referral question; universe=hospitals
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q159_receive_referral_how_XX = strpos(q159_receive_referral_how, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q159_receive_referral_how f_type, col percent
* capture noisily tabout q159_receive_referral_how f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.13 - Percent distribution of primary care providers who have a network of
*       specialist providers or referral health facilities to refer patients to, by facility
*       type (n=1,521) -----
* universe: primary care providers | breakdown: by facility type | status: mapped
* note: Universe=primary care providers (Q8_SERVICE_LEVEL=1)
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q157_specialist_network f_type, col percent
capture noisily tabout q157_specialist_network f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.14 - Percent distribution of the facility head respondents' satisfaction
*       rate for the referral system over the past 6 months, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q161_ref_satisfaction f_type, col percent
capture noisily tabout q161_ref_satisfaction f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.15 - Percent distribution of top challenges for facilities in the
*       referral system, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: partial
* PARTIAL: No direct referral-challenges battery; Q162=why not satisfied, asked only if
*   Q161 dissatisfied - biased universe
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q162_not_satisfied_why_XX = strpos(q162_not_satisfied_why, "XX") > 0  // one per code
* f_type comes from the facility master-list join (see plan notes)
* capture noisily svy: tab q162_not_satisfied_why f_type, col percent
* capture noisily tabout q162_not_satisfied_why f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.16 - Percent distribution of facilities that are DOH licensed, at the
*       point of survey, by facility type (n=1,521) -----
* universe: all facilities (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q118_doh_licensed f_type, col percent
capture noisily tabout q118_doh_licensed f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.17a - Percent distribution of top barriers in DOH licensing for
*       rural/city health unit, for the most recent application (n=911) -----
* universe: rural/city health units (n=911) | breakdown: none stated | status: mapped
* note: no parent Table 1.17 printed; only 1.17a/1.17b | Checkbox multi; filter
*   facility_type=RHU/CHO
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q121_doh_lic_difficult_XX = strpos(q121_doh_lic_difficult, "XX") > 0  // one per code
* capture noisily svy: tab q121_doh_lic_difficult, percent
* capture noisily tabout q121_doh_lic_difficult using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.17b - Percent distribution of top barriers in DOH licensing for
*       hospitals, for the most recent application -----
* universe: hospitals | breakdown: none stated | status: mapped
* note: no n= printed (cf. 1.17a n=911) | Checkbox multi; filter facility_type=hospital
*   (L1-L3)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q121_doh_lic_difficult_XX = strpos(q121_doh_lic_difficult, "XX") > 0  // one per code
* capture noisily svy: tab q121_doh_lic_difficult, percent
* capture noisily tabout q121_doh_lic_difficult using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.18 - Percentage distribution of the average number of days to DOH
*       licensing for the facility's most recent application, by facility type (n=1,521) -----
* universe: all facility heads (n=1,521) | breakdown: by facility type | status: mapped
* f_type comes from the facility master-list join (see plan notes)
capture noisily svy: tab q120_lic_days f_type, col percent
capture noisily tabout q120_lic_days f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)

*----- Table 1.19 - Percentage distribution of facilities who provide NBB to 100% of
*       eligible patients, over the past 6 months, by facility type -----
* universe: facilities | breakdown: by facility type | status: mapped
* note: Indicator: Q136=Yes among Q135=Yes (implements NBB for all patients, last 6 mo)
* f_type comes from the facility master-list join (see plan notes)
capture noisily {
foreach v in q135_nbb_curr q136_nbb_all_patients {
    svy: tab `v' f_type, col percent
    tabout `v' f_type using "$OUT_DIR/annex1_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 1.20 - Percentage distribution of primary care facilities experiencing
*       stock-outs of tracer essential medicines (e.g., antihypertensives, antibiotics) for more
*       than 7 days in the past quarter -----
* universe: primary care facilities | breakdown: none stated | status: mapped
* DERIVED: Flag derived: Q112=1 & Q114>7 days (past 3 mo=quarter); Q113 free-text med
*   list; universe primary care (Q8=1)
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* capture noisily {
* foreach v in q112_stockout q113_stockout_meds q114_stockout_duration q115_stockout_avg {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 1.21 - Percentage distribution of primary care facilities experiencing
*       stock-outs of tracer essential medicines (e.g., antihypertensives, antibiotics) for more
*       than 7 days in the past quarter (continued) -----
* universe: primary care facilities | breakdown: none stated | status: mapped
* note: printed as (continued) of Table 1.20 | Split pair with 1.20 - same Q112-Q115
*   stock-out battery, continued panel
capture noisily {
foreach v in q112_stockout q113_stockout_meds q114_stockout_duration q115_stockout_avg {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 1.22 - Percentage distribution of patients successfully referred to a
*       higher-level facility within the network (HCPN) who received care -----
* universe: patients referred to higher-level facility within HCPN | breakdown: none stated |
*   status: partial
* PARTIAL: F1 has only outbound referral count Q154 (past 6 mo); no received-care
*   outcome in F1 - numerator is patient-side (F3)
* capture noisily svy: tab q154_num_referred_out, percent
* capture noisily tabout q154_num_referred_out using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.23 - Percentage distribution of facilities submitting routine health and
*       financial data to DOH Information System and/or PhilHealth Dashboard -----
* universe: facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q32_data_submit, percent
capture noisily tabout q32_data_submit using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.24 - Percentage distribution on the frequency of health and financial
*       data submissions to DOH Information System and/or PhilHealth Dashboard -----
* universe: facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q33_data_freq, percent
capture noisily tabout q33_data_freq using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.25 - Percentage distribution of the submitted health and financial data
*       reports used for decision-making -----
* universe: facilities | breakdown: none stated | status: mapped
* note: Checkbox multi; split to dummies
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q34_data_reports_used_XX = strpos(q34_data_reports_used, "XX") > 0  // one per code
* capture noisily svy: tab q34_data_reports_used, percent
* capture noisily tabout q34_data_reports_used using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.26 - Percentage distribution of facility head respondents who report
*       clearly defined roles and autonomy vis-?-vis the LGU/Provincial Health Office -----
* universe: facility heads | breakdown: none stated | status: mapped
* note: Q152=clarity rating of PHO-vs-facility decision protocols
capture noisily svy: tab q152_pho_protocol_clarity, percent
capture noisily tabout q152_pho_protocol_clarity using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.27 - Percentage distribution of facility head respondents who reported
*       delays in receiving capitation tranches -----
* universe: facility heads | breakdown: none stated | status: mapped
capture noisily svy: tab q61_tranche_delay, percent
capture noisily tabout q61_tranche_delay using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.28 - Percentage distribution on the average time interval between
*       tranches releases to the facility -----
* universe: facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q62_tranche_interval, percent
capture noisily tabout q62_tranche_interval using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.29 - Percentage distribution of facility heads by role in the health
*       facility -----
* universe: facility heads | breakdown: by role in the health facility | status: mapped
* TODO breakdown dim(s) with no standard bygroup var yet: role in the health facility
capture noisily svy: tab q2_facility_role, percent
capture noisily tabout q2_facility_role using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.30 - Percentage distribution of facility heads by age group -----
* universe: facility heads | breakdown: by age group | status: mapped
* DERIVED: Age bands derived from continuous Q3_AGE
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* TODO breakdown dim(s) with no standard bygroup var yet: age group
* capture noisily svy: tab q3_age, percent
* capture noisily tabout q3_age using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.31 - Percentage distribution of facility heads by sex at birth -----
* universe: facility heads | breakdown: by sex at birth | status: mapped
* TODO breakdown dim(s) with no standard bygroup var yet: sex at birth
capture noisily svy: tab q4_sex, percent
capture noisily tabout q4_sex using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 1.32 - Percentage distribution of health facilities by service capacity
*       level -----
* universe: health facilities | breakdown: by service capacity level | status: mapped
* TODO breakdown dim(s) with no standard bygroup var yet: service capacity level
capture noisily svy: tab q8_service_level, percent
capture noisily tabout q8_service_level using "$OUT_DIR/annex1_tables.xls", append svy oneway percent cells(cell) f(1)

