* 20_annex2.do - Annex 2 - F3 patient exit survey table skeletons (Stata 12)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
version 12

capture erase "$OUT_DIR/annex2_tables.xls"
use "$DATA_DIR/f3.dta", clear

*----- Table 2.1 - Percent of inpatient and outpatient respondents who have heard about
*       UHC, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: PATIENT_TYPE=in(2)/out(1) split used by ALL a/b tables; province
*   dim=PROVINCE_HUC_CODE (PSGC, see codebook)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily {
foreach v in q35_uhc_heard patient_type {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.2a - Percent distribution of source of information about UHC of inpatient
*       respondents, by province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: (checkbox multi) UAT-converted tick-all; in/out split via PATIENT_TYPE (see 2.1)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q36_uhc_source_XX = strpos(q36_uhc_source, "XX") > 0  // one per code
* capture noisily svy: tab q36_uhc_source province_huc, col percent
* capture noisily tabout q36_uhc_source province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.2b - Percent distribution of source of information about UHC of
*       outpatient respondents, by province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: (checkbox multi) UAT-converted tick-all; in/out split via PATIENT_TYPE (see 2.1)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q36_uhc_source_XX = strpos(q36_uhc_source, "XX") > 0  // one per code
* capture noisily svy: tab q36_uhc_source province_huc, col percent
* capture noisily tabout q36_uhc_source province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.3 - Percent distribution of inpatient and outpatient respondents who
*       identify as registered to PhilHealth, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: reinstated Q38_1_PIN_WHEN adds when-registered detail; split via PATIENT_TYPE
*   (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily svy: tab q38_philhealth_reg province_huc, col percent
capture noisily tabout q38_philhealth_reg province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.4 - Percentage distribution of unregistered inpatient and outpatient who
*       know where to seek assistance for the registration process, by province -----
* universe: unregistered inpatients+outpatients | breakdown: by province x in/outpatient | status:
*   mapped
* note: universe filter Q38=No; Q44_WHERE_ASSIST gives where; split via PATIENT_TYPE
*   (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily {
foreach v in q43_knows_assist q38_philhealth_reg {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.5a - Percentage distribution of inpatient respondents' source of
*       information on PhilHealth registration, by province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: single-select source of info on PhilHealth registration
capture noisily svy: tab q39_how_find_out province_huc, col percent
capture noisily tabout q39_how_find_out province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.5b - Percentage distribution of outpatient respondents' source of
*       information on PhilHealth registration, by province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: single-select source of info on PhilHealth registration
capture noisily svy: tab q39_how_find_out province_huc, col percent
capture noisily tabout q39_how_find_out province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.6a - Percentage distribution of inpatient respondents who can correctly
*       list PhilHealth benefits under UHC reforms, by province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: (checkbox multi) correctness scored from codes 01-03 vs 04/90
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q46_benefits_XX = strpos(q46_benefits, "XX") > 0  // one per code
* capture noisily svy: tab q46_benefits province_huc, col percent
* capture noisily tabout q46_benefits province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.6b - Percentage distribution of outpatient respondents who can correctly
*       list PhilHealth benefits under UHC reforms, by province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: (checkbox multi) correctness scored from codes 01-03 vs 04/90
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q46_benefits_XX = strpos(q46_benefits, "XX") > 0  // one per code
* capture noisily svy: tab q46_benefits province_huc, col percent
* capture noisily tabout q46_benefits province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.7 - Percentage distribution of inpatient and outpatient respondents who
*       have heard about YAKAP/Konsulta provider assignment under UHC, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: split via PATIENT_TYPE (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily svy: tab q74_kon_heard province_huc, col percent
capture noisily tabout q74_kon_heard province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.8a - Percentage distribution of inpatient respondents who can identify
*       the benefits under the PhilHealth YAKAP/Konsulta package -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) benefit identification scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q76_kon_understand_XX = strpos(q76_kon_understand, "XX") > 0  // one per code
* capture noisily svy: tab q76_kon_understand, percent
* capture noisily tabout q76_kon_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.8b - Percentage distribution of outpatient respondents who can identify
*       the benefits under the PhilHealth YAKAP/Konsulta package -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) benefit identification scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q76_kon_understand_XX = strpos(q76_kon_understand, "XX") > 0  // one per code
* capture noisily svy: tab q76_kon_understand, percent
* capture noisily tabout q76_kon_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.9a - Percentage distribution of inpatient respondents who state that they
*       would visit the YAKAP/Konsulta provider or primary care provider as their first point of
*       contact, by province -----
* universe: inpatients | breakdown: by province | status: partial
* PARTIAL: no direct first-point-of-contact item on F3; proxy=Q80 (knows to book
*   Konsulta when sick)+Q53 has PCP
* capture noisily {
* foreach v in q80_kon_knows_booking q53_has_pcp {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.9b - Percentage distribution of outpatient respondents who state that
*       they would visit the YAKAP/Konsulta provider or primary care provider as their first
*       point of contact, by province -----
* universe: outpatients | breakdown: by province | status: partial
* PARTIAL: no direct first-point-of-contact item on F3; proxy=Q80 (knows to book
*   Konsulta when sick)+Q53 has PCP
* capture noisily {
* foreach v in q80_kon_knows_booking q53_has_pcp {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.10a - Percentage distribution of inpatient respondents' top challenges in
*       registration to PhilHealth for those who have undergone the registration process
*       (including those who did not register successfully) in the past year, by province -----
* universe: inpatients who have undergone the registration process | breakdown: by province |
*   status: mapped
* note: (checkbox multi) Q42=registered path; reinstated Q38_2 tick-all covers
*   unregistered/unsuccessful
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q42_difficulty_XX = strpos(q42_difficulty, "XX") > 0  // one per code
* gen byte q41_reg_difficulty_XX = strpos(q41_reg_difficulty, "XX") > 0  // one per code
* gen byte q38_2_why_not_reg_XX = strpos(q38_2_why_not_reg, "XX") > 0  // one per code
* capture noisily {
* foreach v in q42_difficulty q41_reg_difficulty q38_2_why_not_reg {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.10b - Percentage distribution of outpatient respondents' top challenges
*       in registration to PhilHealth for those who have undergone the registration process
*       (including those who did not register successfully) in the past year, by province -----
* universe: outpatients who have undergone the registration process | breakdown: by province |
*   status: mapped
* note: (checkbox multi) Q42=registered path; reinstated Q38_2 tick-all covers
*   unregistered/unsuccessful
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q42_difficulty_XX = strpos(q42_difficulty, "XX") > 0  // one per code
* gen byte q41_reg_difficulty_XX = strpos(q41_reg_difficulty, "XX") > 0  // one per code
* gen byte q38_2_why_not_reg_XX = strpos(q38_2_why_not_reg, "XX") > 0  // one per code
* capture noisily {
* foreach v in q42_difficulty q41_reg_difficulty q38_2_why_not_reg {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.11a - Percent distribution of inpatient respondents by type of PhilHealth
*       member who self-report to have struggled to pay premiums in the past year, by province
*       -----
* universe: inpatient PhilHealth members | breakdown: by PhilHealth member type x province |
*   status: mapped
* note: member type=Q45; struggled=Q49 (filter Q48=pays premiums)
* TODO breakdown dim(s) with no standard bygroup var yet: PhilHealth member type
capture noisily {
foreach v in q45_category q49_premium_difficult q48_premium_pay {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.11b - Percent distribution of outpatient respondents by type of
*       PhilHealth member who self-report to have struggled to pay premiums in the past year, by
*       province -----
* universe: outpatient PhilHealth members | breakdown: by PhilHealth member type x province |
*   status: mapped
* note: member type=Q45; struggled=Q49 (filter Q48=pays premiums)
* TODO breakdown dim(s) with no standard bygroup var yet: PhilHealth member type
capture noisily {
foreach v in q45_category q49_premium_difficult q48_premium_pay {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.12 - Percent distribution of inpatient and outpatient respondents that
*       have registered to a YAKAP/Konsulta provider, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: split via PATIENT_TYPE (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily svy: tab q77_kon_registered province_huc, col percent
capture noisily tabout q77_kon_registered province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.13 - Percent distribution of inpatient and outpatient respondents who
*       have consulted their assigned YAKAP/Konsulta provider since registering, by province
*       -----
* universe: inpatients+outpatients registered to a YAKAP/Konsulta provider | breakdown: by
*   province x in/outpatient | status: mapped
* note: universe filter Q77=Yes; split via PATIENT_TYPE (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily {
foreach v in q79_kon_had_appt q77_kon_registered {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.14 - Percent distribution of inpatient and outpatient respondents in HCPN
*       that were referred from YAKAP/Konsulta provider or primary care provider, for most
*       recent interaction, by province -----
* universe: inpatients+outpatients in HCPN | breakdown: by province x in/outpatient | status:
*   partial
* PARTIAL: referral-from-PCP/Konsulta=Q172; 'in HCPN' universe has no F3 flag - define
*   analytically
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
* capture noisily svy: tab q172_pcp_referral province_huc, col percent
* capture noisily tabout q172_pcp_referral province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.15 - Percent distribution of inpatient and outpatient respondents that
*       received assistance in making the appointment for that visit, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: referral path Q167; PCP path Q175; split via PATIENT_TYPE (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily {
foreach v in q167_helped_appt q175_pcp_helped_appt {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.16 - Percent distribution of inpatient and outpatient respondents that
*       received assistance by discussing with them the different places they could visit to
*       address their health problem, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: referral path Q166; PCP path Q174; split via PATIENT_TYPE (see 2.1)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily {
foreach v in q166_discussed_options q174_pcp_discussed {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 2.17a - Percentage distribution of inpatient respondents' overall
*       satisfaction rate with the referral system process for most recent interaction at the
*       time of survey, by province -----
* universe: inpatients | breakdown: by province | status: mapped
capture noisily svy: tab q178_sat_referral province_huc, col percent
capture noisily tabout q178_sat_referral province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.17b - Percentage distribution of outpatient respondents' overall
*       satisfaction rate with the referral system process for most recent interaction at the
*       time of survey, by province -----
* universe: outpatients | breakdown: by province | status: mapped
capture noisily svy: tab q178_sat_referral province_huc, col percent
capture noisily tabout q178_sat_referral province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.18 - Percent distribution of inpatient and outpatient respondents who can
*       correctly define a generic drug, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: partial
* PARTIAL: self-reported knows-difference only; no open definition item to score
*   'correctly define'
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
* capture noisily svy: tab q158_brand_gen_know province_huc, col percent
* capture noisily tabout q158_brand_gen_know province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.19 - Percentage distribution of inpatient and outpatient respondents who
*       chose a generic drug when buying medication, for last interaction, by province -----
* universe: inpatients+outpatients | breakdown: by province x in/outpatient | status: mapped
* note: asked for meds bought outside GAMOT pharmacy, last purchase
* TODO extra breakdown dim(s) mapped but not in this two-way tab: patient_type (run as subpop or second pass)
capture noisily svy: tab q159_brand_gen_bought province_huc, col percent
capture noisily tabout q159_brand_gen_bought province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.20a - Percentage distribution of inpatient respondents' reasons to
*       purchase generic options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q160_why_generic_XX = strpos(q160_why_generic, "XX") > 0  // one per code
* capture noisily svy: tab q160_why_generic province_huc, col percent
* capture noisily tabout q160_why_generic province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.20b - Percentage distribution of outpatient respondents' reasons to
*       purchase generic options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q160_why_generic_XX = strpos(q160_why_generic, "XX") > 0  // one per code
* capture noisily svy: tab q160_why_generic province_huc, col percent
* capture noisily tabout q160_why_generic province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.21a - Percentage distribution of inpatient respondents' reasons to
*       purchase branded options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q161_why_branded_XX = strpos(q161_why_branded, "XX") > 0  // one per code
* capture noisily svy: tab q161_why_branded province_huc, col percent
* capture noisily tabout q161_why_branded province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.21b - Percentage distribution of outpatient respondents' reasons to
*       purchase branded options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q161_why_branded_XX = strpos(q161_why_branded, "XX") > 0  // one per code
* capture noisily svy: tab q161_why_branded province_huc, col percent
* capture noisily tabout q161_why_branded province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)

*----- Table 2.22a - Percent distribution of inpatient respondents that accessed
*       medications for free or subsidized, in the last 6 months, by province -----
* universe: inpatients | breakdown: by province | status: partial
* PARTIAL: no single free/subsidized-meds item; derive from free/donation codes in meds
*   pay sources + GAMOT receipt (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q109_sources_XX = strpos(q109_sources, "XX") > 0  // one per code
* gen byte q96_sources_XX = strpos(q96_sources, "XX") > 0  // one per code
* gen byte q155_gamot_got_meds_XX = strpos(q155_gamot_got_meds, "XX") > 0  // one per code
* gen byte q157_where_rest_XX = strpos(q157_where_rest, "XX") > 0  // one per code
* capture noisily {
* foreach v in q109_sources q96_sources q155_gamot_got_meds q157_where_rest {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.22b - Percent distribution of outpatient respondents that accessed
*       medications for free or subsidized, in the last 6 months, by province -----
* universe: outpatients | breakdown: by province | status: partial
* PARTIAL: no single free/subsidized-meds item; derive from free/donation codes in meds
*   pay sources + GAMOT receipt (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q96_sources_XX = strpos(q96_sources, "XX") > 0  // one per code
* gen byte q109_sources_XX = strpos(q109_sources, "XX") > 0  // one per code
* gen byte q155_gamot_got_meds_XX = strpos(q155_gamot_got_meds, "XX") > 0  // one per code
* gen byte q157_where_rest_XX = strpos(q157_where_rest, "XX") > 0  // one per code
* capture noisily {
* foreach v in q96_sources q109_sources q155_gamot_got_meds q157_where_rest {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex2_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 2.23a - Percent distribution of inpatient respondents' top sources of
*       medicine subsidization (i.e., LGU, employer, etc.) in the past 6 months -----
* universe: inpatients | breakdown: none stated | status: partial
* PARTIAL: no LGU/employer subsidy-source battery; nearest=Q157 free-source codes 05-08
*   + free/donation pay codes (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q157_where_rest_XX = strpos(q157_where_rest, "XX") > 0  // one per code
* gen byte q109_sources_XX = strpos(q109_sources, "XX") > 0  // one per code
* gen byte q96_sources_XX = strpos(q96_sources, "XX") > 0  // one per code
* capture noisily {
* foreach v in q157_where_rest q109_sources q96_sources {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.23b - Percent distribution of outpatient respondents' top sources of
*       medicine subsidization (i.e., LGU, employer, etc.) in the past 6 months -----
* universe: outpatients | breakdown: none stated | status: partial
* PARTIAL: no LGU/employer subsidy-source battery; nearest=Q157 free-source codes 05-08
*   + free/donation pay codes (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q157_where_rest_XX = strpos(q157_where_rest, "XX") > 0  // one per code
* gen byte q96_sources_XX = strpos(q96_sources, "XX") > 0  // one per code
* gen byte q109_sources_XX = strpos(q109_sources, "XX") > 0  // one per code
* capture noisily {
* foreach v in q157_where_rest q96_sources q109_sources {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.24a - Percentage distribution of inpatient respondents' that have
*       accessed to alternate financial assistance program/s to help cover medical costs, for
*       most recent interaction, out of all patients -----
* universe: all inpatients | breakdown: none stated | status: partial
* PARTIAL: derived from assistance codes 04-07 of Q113 (checkbox multi) + MAIFIP Q126;
*   no direct fin-assist item
* DERIVED: derived from assistance codes 04-07 of Q113 (checkbox multi) + MAIFIP Q126;
*   no direct fin-assist item
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q113_sources_XX = strpos(q113_sources, "XX") > 0  // one per code
* gen byte q126_maifip_availed_XX = strpos(q126_maifip_availed, "XX") > 0  // one per code
* capture noisily {
* foreach v in q113_sources q126_maifip_availed {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.24b - Percentage distribution of outpatient respondents' that have
*       accessed to alternate financial assistance program/s to help cover medical costs, for
*       most recent interaction, out of all patients -----
* universe: all outpatients | breakdown: none stated | status: partial
* PARTIAL: derived from assistance codes 04-06,09 of Q98 (checkbox multi); no direct
*   fin-assist item
* DERIVED: derived from assistance codes 04-06,09 of Q98 (checkbox multi); no direct
*   fin-assist item
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q98_sources_XX = strpos(q98_sources, "XX") > 0  // one per code
* capture noisily svy: tab q98_sources, percent
* capture noisily tabout q98_sources using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.25a - Percentage distribution of inpatient respondents' that have
*       accessed to alternate financial assistance program/s to help cover medical costs, for
*       most recent interaction, out of billed patients -----
* universe: billed inpatients | breakdown: none stated | status: partial
* PARTIAL: as 2.24a; 'billed' universe inferred from bill items/final cash - no explicit
*   billed flag
* capture noisily {
* foreach v in q113_sources q126_maifip_availed q115_final_cash {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.25b - Percentage distribution of outpatient respondents' that have
*       accessed to alternate financial assistance program/s to help cover medical costs, for
*       most recent interaction, out of billed patients -----
* universe: billed outpatients | breakdown: none stated | status: partial
* PARTIAL: as 2.24b; 'billed' universe inferred from bill/final amount - no explicit
*   billed flag
* capture noisily {
* foreach v in q98_sources q97_final_amount {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.26 - Percentage distribution of inpatient and outpatient respondents'
*       NBB-eligible who received NBB for most recent interaction -----
* universe: NBB-eligible inpatients+outpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator: NBB eligibility from Q45 member category; receipt inferred
*   from zero cash at discharge/PhilHealth-covered codes
* DERIVED: derived indicator: NBB eligibility from Q45 member category; receipt inferred
*   from zero cash at discharge/PhilHealth-covered codes
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* capture noisily {
* foreach v in q45_category q115_final_cash q113_sources q107_sources {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.27 - Percentage distribution of inpatient and outpatient respondents'
*       NBB-eligible who received ZBB for most recent interaction -----
* universe: NBB-eligible inpatients+outpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator: eligibility via Q45; no direct received-ZBB item - infer
*   from Q122/Q123
* DERIVED: derived indicator: eligibility via Q45; no direct received-ZBB item - infer
*   from Q122/Q123
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* capture noisily {
* foreach v in q45_category q122_zbb_informed q123_zbb_extent {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.28a - Summary of alternate financial assistance program/s covering the
*       inpatients' medical costs, in their most recent interaction -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (roster) assistance rows=codes 04-07 of Q113 with amounts
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* stat_type 'summary': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q113_pay_src q113_pay_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.28b - Summary of alternate financial assistance program/s covering the
*       outpatients' medical costs, in their most recent interaction -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (roster) assistance rows=codes 04-06,09 of Q98 with amounts
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* stat_type 'summary': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q98_pay_src q98_pay_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.29 - Catastrophic health expenditure at the 25% and 40% thresholds across
*       different subgroups among patients within UHC-IS and Non-UHC-IS -----
* universe: inpatients+outpatients (UHC-IS and Non-UHC-IS) | breakdown: by subgroup x UHC-IS/Non-
*   UHC-IS | status: partial
* PARTIAL: derived indicator (CHE 25%/40%): OOP summed from expenditure rosters (roster)
*   vs income Q18; UHC-IS flag=CLASSIFICATION
* DERIVED: derived indicator (CHE 25%/40%): OOP summed from expenditure rosters (roster)
*   vs income Q18; UHC-IS flag=CLASSIFICATION
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* TODO breakdown dim(s) with no standard bygroup var yet: subgroup; UHC-IS/Non-UHC-IS
* capture noisily {
* foreach v in q18_income_amount classification q92_pay_amt q94_lab_amt q96_pay_amt q97_final_amount q971_pay_amt q972_pay_amt q107_pay_amt q109_pay_amt q112_pay_amt q113_pay_amt q115_final_cash {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.30 - Percentage distribution of inpatient and outpatient respondents that
*       use loan/mortgage to pay for medical costs, for most recent interaction -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Loan/Mortgage=code 02 in both; amounts in Q98/Q113 rosters
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q98_sources_XX = strpos(q98_sources, "XX") > 0  // one per code
* gen byte q113_sources_XX = strpos(q113_sources, "XX") > 0  // one per code
* capture noisily {
* foreach v in q98_sources q113_sources {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.31 - Percentage distribution of inpatient and outpatient respondents that
*       use sale of assets to pay for medical costs, for most recent interaction -----
* universe: inpatients+outpatients | breakdown: none stated | status: partial
* PARTIAL: (checkbox multi) Sale of Assets=Q98 code 07 (outpatient only); inpatient Q113
*   has no asset-sale code
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q98_sources_XX = strpos(q98_sources, "XX") > 0  // one per code
* capture noisily svy: tab q98_sources, percent
* capture noisily tabout q98_sources using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.32 - Percentage distribution of inpatient and outpatient respondents that
*       experience incidence of reduced care due to financial reasons among the population, for
*       most recent interaction -----
* universe: inpatients+outpatients | breakdown: none stated | status: partial
* PARTIAL: no direct reduced-care item; proxies=Q130 reduced essential spending + Q90
*   codes 02/03 (cost) for forgone admission
* capture noisily {
* foreach v in q130_reduced_spend q90_not_confined {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.33a - Health care expenditures of inpatient respondents by type of
*       facility, for the most recent interaction, by province -----
* universe: inpatients | breakdown: by facility type x province | status: partial
* PARTIAL: (roster) sum inpatient expenditure rosters + 115.1/115.2 amounts; facility-
*   type dim from sample frame, not an F3 item
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* f_type comes from the facility master-list join (see plan notes)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: province_huc (run as subpop or second pass)
* stat_type 'summary': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q107_pay_amt q109_pay_amt q112_pay_amt q113_pay_amt q115_final_cash, over(f_type)
* capture noisily tabout f_type using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q107_pay_amt mean q109_pay_amt mean q112_pay_amt mean q113_pay_amt mean q115_final_cash) f(2)

*----- Table 2.33b - Health care expenditures of outpatient respondents by type of
*       facility, for the most recent interaction, by province -----
* universe: outpatients | breakdown: by facility type x province | status: partial
* PARTIAL: (roster) sum outpatient expenditure rosters; facility-type dim from sample
*   frame, not an F3 item
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* f_type comes from the facility master-list join (see plan notes)
* TODO extra breakdown dim(s) mapped but not in this two-way tab: province_huc (run as subpop or second pass)
* stat_type 'summary': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q92_pay_amt q94_lab_amt q96_pay_amt q97_final_amount q971_pay_amt q972_pay_amt, over(f_type)
* capture noisily tabout f_type using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q92_pay_amt mean q94_lab_amt mean q96_pay_amt mean q97_final_amount mean q971_pay_amt mean q972_pay_amt) f(2)

*----- Table 2.34a - Average time (in minutes) of inpatient respondents to access
*       nearest health facility for the latest visit, by province -----
* universe: inpatients | breakdown: by province | status: mapped
* note: F3 asks nearest primary care facility; convert HH+MM to minutes
capture noisily svy: mean q72_nearest_travel_hh q72_nearest_travel_mm, over(province_huc)
capture noisily tabout province_huc using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q72_nearest_travel_hh mean q72_nearest_travel_mm) f(2)

*----- Table 2.34b - Average time (in minutes) of outpatient respondents to access
*       nearest health facility for the latest visit, by province -----
* universe: outpatients | breakdown: by province | status: mapped
* note: F3 asks nearest primary care facility; convert HH+MM to minutes
capture noisily svy: mean q72_nearest_travel_hh q72_nearest_travel_mm, over(province_huc)
capture noisily tabout province_huc using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q72_nearest_travel_hh mean q72_nearest_travel_mm) f(2)

*----- Table 2.35a - Average costs spent of inpatient respondents on going to the
*       nearest health facility for the latest visit, by level of care -----
* universe: inpatients | breakdown: by level of care | status: partial
* PARTIAL: no transport-cost-to-nearest-facility item; proxy=visit transport spend
*   115.2; level-of-care dim from frame
* TODO breakdown dim(s) with no standard bygroup var yet: level of care
* capture noisily svy: mean q1142_4_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.35b - Average costs spent of outpatient respondents on going to the
*       nearest health facility for the latest visit, by level of care -----
* universe: outpatients | breakdown: by level of care | status: partial
* PARTIAL: (roster) no transport-cost-to-nearest-facility item; proxy=travel rows (code
*   05) of Q97.2; level-of-care dim from frame
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* TODO breakdown dim(s) with no standard bygroup var yet: level of care
* capture noisily svy: mean q972_pay_src q972_pay_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.36a - Percentage distribution of inpatient respondents that walk as mode
*       of transportation used on going to the nearest health facility for the latest visit
*       -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Walk=code 01 of ONE multi-select Q73; same source var for all
*   of 2.36-2.46
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.36b - Percentage distribution of outpatient respondents that walk as mode
*       of transportation used on going to the nearest health facility for the latest visit
*       -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Walk=code 01 of ONE multi-select Q73; same source var for all
*   of 2.36-2.46
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.37a - Percentage distribution of inpatient respondents that ride a bike
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Bike=code 02 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.37b - Percentage distribution of outpatient respondents that ride a bike
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Bike=code 02 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.38a - Percentage distribution of inpatient respondents that ride a public
*       bus as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Public Bus=code 03 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.38b - Percentage distribution of outpatient respondents that ride a
*       public bus as mode of transportation used on going to the nearest health facility for
*       the latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Public Bus=code 03 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.39a - Percentage distribution of inpatient respondents that ride a
*       jeepney as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Jeepney=code 04 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.39b - Percentage distribution of outpatient respondents that ride a
*       jeepney as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Jeepney=code 04 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.40a - Percentage distribution of inpatient respondents that ride a
*       tricycle as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Tricycle=code 05 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.40b - Percentage distribution of outpatient respondents that ride a
*       tricycle as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Tricycle=code 05 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.41a - Percentage distribution of inpatient respondents that ride a car as
*       mode of transportation used on going to the nearest health facility for the latest visit
*       -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Car incl. private taxi=code 06 of ONE multi-select Q73 (see
*   2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.41b - Percentage distribution of outpatient respondents that ride a car
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Car incl. private taxi=code 06 of ONE multi-select Q73 (see
*   2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.42a - Percentage distribution of inpatient respondents that ride a
*       motorcycle as mode of transportation used on going to the nearest health facility for
*       the latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Motorcycle=code 07 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.42b - Percentage distribution of outpatient respondents that ride a
*       motorcycle as mode of transportation used on going to the nearest health facility for
*       the latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Motorcycle=code 07 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.43a - Percentage distribution of inpatient respondents that ride a boat
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Boat=code 08 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.43b - Percentage distribution of outpatient respondents that ride a boat
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Boat=code 08 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.44a - Percentage distribution of inpatient respondents that ride a taxi
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Taxi=code 09 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.44b - Percentage distribution of outpatient respondents that ride a taxi
*       as mode of transportation used on going to the nearest health facility for the latest
*       visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Taxi=code 09 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.45a - Percentage distribution of inpatient respondents that ride a
*       pedicab as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Pedicab=code 10 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.45b - Percentage distribution of outpatient respondents that ride a
*       pedicab as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) Pedicab=code 10 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.46a - Percentage distribution of inpatient respondents that ride an
*       E-bike as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) E-bike=code 11 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.46b - Percentage distribution of outpatient respondents that ride an
*       E-bike as mode of transportation used on going to the nearest health facility for the
*       latest visit -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) E-bike=code 11 of ONE multi-select Q73 (see 2.36)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q73_nearest_transport_XX = strpos(q73_nearest_transport, "XX") > 0  // one per code
* capture noisily svy: tab q73_nearest_transport, percent
* capture noisily tabout q73_nearest_transport using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.47a - Responsiveness score summary for inpatient respondents -----
* universe: inpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator (responsiveness score) from Section J items; Q134
*   rooms=inpatient only
* DERIVED: derived indicator (responsiveness score) from Section J items; Q134
*   rooms=inpatient only
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q131_amen_waiting q132_amen_bathrooms q133_amen_consult_rooms q134_amen_rooms q135_sat_overall_time q136_staff_courtesy q137_staff_listen q138_staff_explain q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.47b - Responsiveness score summary for outpatient respondents -----
* universe: outpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator (responsiveness score) from Section J items; Q134 rooms
*   excluded for outpatients
* DERIVED: derived indicator (responsiveness score) from Section J items; Q134 rooms
*   excluded for outpatients
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q131_amen_waiting q132_amen_bathrooms q133_amen_consult_rooms q135_sat_overall_time q136_staff_courtesy q137_staff_listen q138_staff_explain q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.48a - Respect for Persons Domains: Dignity, Autonomy, Confidentiality for
*       inpatient respondents -----
* universe: inpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator: dignity=Q136/Q142, autonomy=Q139/Q140,
*   confidentiality=Q141
* DERIVED: derived indicator: dignity=Q136/Q142, autonomy=Q139/Q140,
*   confidentiality=Q141
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q136_staff_courtesy q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.48b - Respect for Persons Domains: Dignity, Autonomy, Confidentiality for
*       outpatient respondents -----
* universe: outpatients | breakdown: none stated | status: partial
* PARTIAL: derived indicator: dignity=Q136/Q142, autonomy=Q139/Q140,
*   confidentiality=Q141
* DERIVED: derived indicator: dignity=Q136/Q142, autonomy=Q139/Q140,
*   confidentiality=Q141
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q136_staff_courtesy q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.49a - Respect for Persons Domains: Dignity, Autonomy, Confidentiality for
*       inpatient respondents -----
* universe: inpatients | breakdown: none stated | status: partial
* PARTIAL: duplicate description as printed (same as Table 2.48a) | as printed,
*   duplicates 2.48; derived indicator (see 2.48)
* DERIVED: duplicate description as printed (same as Table 2.48a) | as printed,
*   duplicates 2.48; derived indicator (see 2.48)
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q136_staff_courtesy q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.49b - Respect for Persons Domains: Dignity, Autonomy, Confidentiality for
*       outpatient respondents -----
* universe: outpatients | breakdown: none stated | status: partial
* PARTIAL: duplicate description as printed (same as Table 2.48b) | as printed,
*   duplicates 2.48; derived indicator (see 2.48)
* DERIVED: duplicate description as printed (same as Table 2.48b) | as printed,
*   duplicates 2.48; derived indicator (see 2.48)
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q136_staff_courtesy q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.50a - Overall inpatient experience score across levels of facility,
*       socioeconomic status, place of residence, and sex, for their most recent encounter -----
* universe: inpatients | breakdown: by facility level x SES x residence x sex | status: partial
* PARTIAL: derived indicator (experience score) from Section J; dims: SES=Q29_SEC_CLASS,
*   sex=Q7_SEX, residence=P_* geo, facility level=frame
* DERIVED: derived indicator (experience score) from Section J; dims: SES=Q29_SEC_CLASS,
*   sex=Q7_SEX, residence=P_* geo, facility level=frame
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* f_type comes from the facility master-list join (see plan notes)
* TODO breakdown dim(s) with no standard bygroup var yet: SES; residence; sex
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q135_sat_overall_time q136_staff_courtesy q137_staff_listen q138_staff_explain q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy q143_recommend q144_quality, over(f_type)
* capture noisily tabout f_type using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q135_sat_overall_time mean q136_staff_courtesy mean q137_staff_listen mean q138_staff_explain mean q139_staff_decide mean q140_staff_consent mean q141_confidentiality mean q142_privacy mean q143_recommend mean q144_quality) f(2)

*----- Table 2.50b - Overall outpatient experience score across levels of facility,
*       socioeconomic status, place of residence, and sex, for their most recent encounter -----
* universe: outpatients | breakdown: by facility level x SES x residence x sex | status: partial
* PARTIAL: derived indicator (experience score) from Section J; dims: SES=Q29_SEC_CLASS,
*   sex=Q7_SEX, residence=P_* geo, facility level=frame
* DERIVED: derived indicator (experience score) from Section J; dims: SES=Q29_SEC_CLASS,
*   sex=Q7_SEX, residence=P_* geo, facility level=frame
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* f_type comes from the facility master-list join (see plan notes)
* TODO breakdown dim(s) with no standard bygroup var yet: SES; residence; sex
* stat_type 'score': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean q135_sat_overall_time q136_staff_courtesy q137_staff_listen q138_staff_explain q139_staff_decide q140_staff_consent q141_confidentiality q142_privacy q143_recommend q144_quality, over(f_type)
* capture noisily tabout f_type using "$OUT_DIR/annex2_tables.xls", append svy sum cells(mean q135_sat_overall_time mean q136_staff_courtesy mean q137_staff_listen mean q138_staff_explain mean q139_staff_decide mean q140_staff_consent mean q141_confidentiality mean q142_privacy mean q143_recommend mean q144_quality) f(2)

*----- Table 2.51 - Average out-of-pocket payments on rooms of inpatient and outpatient
*       respondents -----
* universe: inpatients+outpatients | breakdown: none stated | status: gap
* GAP - no source in instrument: no room/board OOP item on F3; 115.1/97.1 bill
*   itemizations lack rooms; bill rosters are by pay source not line item

*----- Table 2.52 - Average out-of-pocket payments on consultation of inpatient and
*       outpatient respondents -----
* universe: inpatients+outpatients | breakdown: none stated | status: partial
* PARTIAL: (roster) OPD direct=OOP rows of Q92 roster; inpatient proxy=115.1 doctor's PF
*   amount
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* capture noisily svy: mean q92_pay_src q92_pay_amt q1141_1_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.53 - Average out-of-pocket payments on laboratory tests of inpatient and
*       outpatient respondents -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: (roster) OPD per-test Q94; IPD=115.1 diagnostics + outside-services Q112 OOP
*   rows
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* capture noisily svy: mean q94_lab_pay q94_lab_amt q1141_4_amt q112_pay_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.54 - Average out-of-pocket payments on prescribed medicines of inpatient
*       and outpatient respondents -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: (roster) OPD Q96; IPD outside-meds Q109 + 115.1 in-bill medicines; OOP rows only
* ROSTER: this table reads the F3 pay/expenditure roster extract, a separate
* long-format dataset (one row per bill line / pay source).
* use "$DATA_DIR/f3_roster.dta", clear   // TODO - roster extract not in ETL yet
* ... (tab/collapse the roster, then:  use "$DATA_DIR/f3.dta", clear )
* capture noisily svy: mean q96_pay_src q96_pay_amt q109_pay_src q109_pay_amt q1141_5_amt
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

*----- Table 2.55 - Percentage distribution of inpatient and outpatient respondents who
*       have heard about ZBB -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: split via PATIENT_TYPE (see 2.1)
capture noisily svy: tab q119_zbb_heard, percent
capture noisily tabout q119_zbb_heard using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.56a - Percentage distribution of inpatient respondents' top information
*       sources about ZBB -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q120_zbb_source_XX = strpos(q120_zbb_source, "XX") > 0  // one per code
* capture noisily svy: tab q120_zbb_source, percent
* capture noisily tabout q120_zbb_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.56b - Percentage distribution of outpatient respondents' top information
*       sources about ZBB -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q120_zbb_source_XX = strpos(q120_zbb_source, "XX") > 0  // one per code
* capture noisily svy: tab q120_zbb_source, percent
* capture noisily tabout q120_zbb_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.57a - Percentage distribution of inpatient respondents who can correctly
*       identify the benefits under ZBB -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) correctness scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q121_zbb_understand_XX = strpos(q121_zbb_understand, "XX") > 0  // one per code
* capture noisily svy: tab q121_zbb_understand, percent
* capture noisily tabout q121_zbb_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.57b - Percentage distribution of outpatient respondents who can correctly
*       identify the benefits under ZBB -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) correctness scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q121_zbb_understand_XX = strpos(q121_zbb_understand, "XX") > 0  // one per code
* capture noisily svy: tab q121_zbb_understand, percent
* capture noisily tabout q121_zbb_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.58 - Percentage distribution of inpatient and outpatient respondents who
*       have heard about BUCAS -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: asked only where AREA_HAS_BUCAS=1; split via PATIENT_TYPE (see 2.1)
capture noisily svy: tab q99_bucas_heard, percent
capture noisily tabout q99_bucas_heard using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.59a - Percentage distribution of inpatient respondents' top information
*       sources about BUCAS -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q100_bucas_source_XX = strpos(q100_bucas_source, "XX") > 0  // one per code
* capture noisily svy: tab q100_bucas_source, percent
* capture noisily tabout q100_bucas_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.59b - Percentage distribution of outpatient respondents' top information
*       sources about BUCAS -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q100_bucas_source_XX = strpos(q100_bucas_source, "XX") > 0  // one per code
* capture noisily svy: tab q100_bucas_source, percent
* capture noisily tabout q100_bucas_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.60a - Percentage distribution of inpatient respondents who can identify
*       the benefits under BUCAS -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) benefit identification scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q101_bucas_understand_XX = strpos(q101_bucas_understand, "XX") > 0  // one per code
* capture noisily svy: tab q101_bucas_understand, percent
* capture noisily tabout q101_bucas_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.60b - Percentage distribution of outpatient respondents who can identify
*       the benefits under BUCAS -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) benefit identification scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q101_bucas_understand_XX = strpos(q101_bucas_understand, "XX") > 0  // one per code
* capture noisily svy: tab q101_bucas_understand, percent
* capture noisily tabout q101_bucas_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.61a - Percentage distribution of inpatient respondents' most commonly
*       accessed services in BUCAS -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) universe filter Q102=Yes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q103_bucas_services_XX = strpos(q103_bucas_services, "XX") > 0  // one per code
* gen byte q102_bucas_accessed_XX = strpos(q102_bucas_accessed, "XX") > 0  // one per code
* capture noisily {
* foreach v in q103_bucas_services q102_bucas_accessed {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.61b - Percentage distribution of outpatient respondents' most commonly
*       accessed services in BUCAS -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) universe filter Q102=Yes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q103_bucas_services_XX = strpos(q103_bucas_services, "XX") > 0  // one per code
* gen byte q102_bucas_accessed_XX = strpos(q102_bucas_accessed, "XX") > 0  // one per code
* capture noisily {
* foreach v in q103_bucas_services q102_bucas_accessed {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 2.62 - Percentage distribution of inpatient and outpatient respondents who
*       have heard about GAMOT -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: asked only where AREA_HAS_GAMOT=1; split via PATIENT_TYPE (see 2.1)
capture noisily svy: tab q152_gamot_heard, percent
capture noisily tabout q152_gamot_heard using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.63a - Percentage distribution of inpatient respondents' top information
*       sources about GAMOT -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q153_gamot_source_XX = strpos(q153_gamot_source, "XX") > 0  // one per code
* capture noisily svy: tab q153_gamot_source, percent
* capture noisily tabout q153_gamot_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.63b - Percentage distribution of outpatient respondents' top information
*       sources about GAMOT -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q153_gamot_source_XX = strpos(q153_gamot_source, "XX") > 0  // one per code
* capture noisily svy: tab q153_gamot_source, percent
* capture noisily tabout q153_gamot_source using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.64a - Percentage distribution of inpatient respondents who can correctly
*       identify the benefits under GAMOT -----
* universe: inpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) correctness scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q154_gamot_understand_XX = strpos(q154_gamot_understand, "XX") > 0  // one per code
* capture noisily svy: tab q154_gamot_understand, percent
* capture noisily tabout q154_gamot_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.64b - Percentage distribution of outpatient respondents who can correctly
*       identify the benefits under GAMOT -----
* universe: outpatients | breakdown: none stated | status: mapped
* note: (checkbox multi) correctness scored from codes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q154_gamot_understand_XX = strpos(q154_gamot_understand, "XX") > 0  // one per code
* capture noisily svy: tab q154_gamot_understand, percent
* capture noisily tabout q154_gamot_understand using "$OUT_DIR/annex2_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 2.65 - Descriptive statistics of socio-demographic characteristics of the
*       inpatient and outpatient respondents -----
* universe: inpatients+outpatients | breakdown: none stated | status: mapped
* note: Section B profile battery; add Q8_LGBTQIA/asset items Q22-Q28 as needed
* stat_type 'descriptive stats': skeleton uses svy: mean over the component items; composite recipe TBD
capture noisily svy: mean q6_age q7_sex q9_group q10_civil_status q11_pwd q15_education q16_employment q17_income_source q18_income_bracket q19_hh_size q29_sec_class q30_ip q32_4ps
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

