* 30_annex3.do - Annex 3 - F4 household survey table skeletons (Stata 12)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
version 12

capture erase "$OUT_DIR/annex3_tables.xls"
use "$DATA_DIR/f4.dta", clear

*----- Table 3.1 - Percent of household respondents who have heard about UHC, by
*       province -----
* universe: households | breakdown: by province | status: mapped
* note: 'By province' for all Annex-3 tables = PSGC geo block PROVINCE_HUC (codebook
*   province_code); id-block PROVINCE_HUC_CODE equivalent
capture noisily {
foreach v in q51_uhc_heard province_huc {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 3.2 - Percent distribution of source of information about UHC of household
*       respondents, by province -----
* universe: households | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q52_uhc_source_XX = strpos(q52_uhc_source, "XX") > 0  // one per code
* gen byte q52_uhc_source_other_txt_XX = strpos(q52_uhc_source_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q52_uhc_source q52_uhc_source_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.3 - Percent distribution of household respondents who identify as
*       registered to PhilHealth, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Q45 is roster-level; use respondent's own roster row (ambiguous respondent vs
*   all-member rate)
capture noisily svy: tab q45_philhealth_reg province_huc, col percent
capture noisily tabout q45_philhealth_reg province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)

*----- Table 3.4 - Percentage distribution of household respondents that are
*       unregistered who know where to seek assistance for the registration process, by province
*       -----
* universe: unregistered households | breakdown: by province | status: mapped
* note: Unregistered universe = respondent roster row Q45=02 No; Q84_WHERE_ASSIST gives
*   where
capture noisily {
foreach v in q83_knows_assist q45_philhealth_reg {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 3.5 - Percentage distribution of household respondents' source of
*       information on PhilHealth registration, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Single-select (numeric), not checkbox
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q79_reg_source_XX = strpos(q79_reg_source, "XX") > 0  // one per code
* gen byte q79_reg_source_other_txt_XX = strpos(q79_reg_source_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q79_reg_source q79_reg_source_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.6 - Percentage distribution of household respondents who can correctly
*       list PhilHealth benefits under UHC reforms, by province -----
* universe: households | breakdown: by province | status: mapped
* DERIVED: (checkbox multi); 'correctly list' scoring derived at analysis vs codes 01-03
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q85_benefits_XX = strpos(q85_benefits, "XX") > 0  // one per code
* gen byte q85_benefits_other_txt_XX = strpos(q85_benefits_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q85_benefits q85_benefits_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.7 - Percentage distribution of household respondents who have heard about
*       YAKAP/Konsulta provider assignment under UHC, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Q54 asks package awareness; 'provider assignment' wording not asked verbatim
capture noisily svy: tab q54_yakap_heard province_huc, col percent
capture noisily tabout q54_yakap_heard province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)

*----- Table 3.8 - Percentage distribution of household respondents who can identify the
*       benefits under the PhilHealth YAKAP/Konsulta package -----
* universe: households | breakdown: none stated | status: mapped
* DERIVED: (checkbox multi); correct-benefit scoring derived at analysis
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q56_yakap_understand_XX = strpos(q56_yakap_understand, "XX") > 0  // one per code
* gen byte q56_yakap_understand_other_txt_XX = strpos(q56_yakap_understand_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q56_yakap_understand q56_yakap_understand_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.9 - Percentage distribution of household respondents' top challenges in
*       registration to PhilHealth for those who have undergone the registration process
*       (including those who did not register successfully) in the past year, by province -----
* universe: households who have undergone the registration process | breakdown: by province |
*   status: partial
* PARTIAL: (checkbox multi); no 'underwent registration in past yr incl unsuccessful'
*   flag; approx universe via Q45_1_PIN_REG_WHEN
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q81_reg_difficulty_XX = strpos(q81_reg_difficulty, "XX") > 0  // one per code
* gen byte q82_difficulty_reasons_XX = strpos(q82_difficulty_reasons, "XX") > 0  // one per code
* gen byte q82_difficulty_reasons_other_txt_XX = strpos(q82_difficulty_reasons_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q81_reg_difficulty q82_difficulty_reasons q82_difficulty_reasons_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.10 - Percent distribution of household respondents by type of PhilHealth
*       membership who self-report to have struggled to pay premiums in the past year, by
*       province -----
* universe: household PhilHealth members | breakdown: by PhilHealth membership type x province |
*   status: mapped
* note: Membership type Q46 is roster-level (respondent row); Q86 premium-pay gate; Q88
*   reasons
* TODO breakdown dim(s) with no standard bygroup var yet: PhilHealth membership type
capture noisily {
foreach v in q87_premium_difficult q46_member_category {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 3.11 - Percentage distribution of household respondents in HCPN that were
*       referred from YAKAP/Konsulta provider or primary care provider, for most recent
*       interaction, by province -----
* universe: households in HCPN | breakdown: by province | status: partial
* PARTIAL: No HCPN-membership flag; Q119 = referral from primary care facility, most
*   recent visit; YAKAP-provider referral not distinguished
* capture noisily {
* foreach v in q108_referred q119_pcf_referral {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.12 - Percent distribution of household respondents that received
*       assistance in making the appointment for that visit, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Two paths: referral chain Q115 vs non-referral PCP chain Q123; Section K gated
*   on Q108=Yes
capture noisily {
foreach v in q115_helped_appt q123_pcp_helped_appt {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 3.13 - Percent distribution of household respondents that received
*       assistance by discussing with them the different places they could visit to address
*       their health problem, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Two paths: Q114 (referral) vs Q122 (PCP); Section K gated on Q108=Yes
capture noisily {
foreach v in q114_discussed_places q122_pcp_discussed_places {
    svy: tab `v' province_huc, col percent
    tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
}
}

*----- Table 3.14 - Households' overall satisfaction rate with the referral system
*       process for most recent interaction at the time of survey -----
* universe: households | breakdown: none stated | status: mapped
* note: Two 5-pt satisfaction items: referral path Q118, non-referral PCP path Q125
capture noisily {
foreach v in q118_sat_referral_process q125_sat_referral_exp {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 3.15 - Percentage distribution of household respondents who can correctly
*       define a generic drug, by province -----
* universe: households | breakdown: by province | status: partial
* PARTIAL: Self-reported Y/N knowledge only; no scored 'define a generic drug' item to
*   verify correctness
* capture noisily svy: tab q75_brand_gen_knows province_huc, col percent
* capture noisily tabout q75_brand_gen_knows province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)

*----- Table 3.16 - Percentage distribution of household respondents who chose a generic
*       drug when buying medication, for last interaction, by province -----
* universe: households | breakdown: by province | status: mapped
* note: Scope = meds bought outside GAMOT pharmacy; code 3 = both branded and generic
capture noisily svy: tab q76_brand_or_gen province_huc, col percent
capture noisily tabout q76_brand_or_gen province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)

*----- Table 3.17 - Percentage distribution of household respondents' reasons to
*       purchase generic options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: households | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q77_why_generic_XX = strpos(q77_why_generic, "XX") > 0  // one per code
* gen byte q77_why_generic_other_txt_XX = strpos(q77_why_generic_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q77_why_generic q77_why_generic_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.18 - Percentage distribution of household respondents' reasons to
*       purchase branded options (prescribed by doctor, cheaper, etc.) in the past 6 months, by
*       province -----
* universe: households | breakdown: by province | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q78_why_branded_XX = strpos(q78_why_branded, "XX") > 0  // one per code
* gen byte q78_why_branded_other_txt_XX = strpos(q78_why_branded_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q78_why_branded q78_why_branded_other_txt {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.19 - Percent distribution of household respondents that accessed
*       medications for free or subsidized, in the last 6 months, by province -----
* universe: households | breakdown: by province | status: partial
* PARTIAL: No direct free/subsidized item; derive from Q72 (GAMOT free meds) + Q74 codes
*   05-08 'received for free' (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q72_gamot_obtained_XX = strpos(q72_gamot_obtained, "XX") > 0  // one per code
* gen byte q74_where_rest_XX = strpos(q74_where_rest, "XX") > 0  // one per code
* capture noisily {
* foreach v in q72_gamot_obtained q74_where_rest {
*     svy: tab `v' province_huc, col percent
*     tabout `v' province_huc using "$OUT_DIR/annex3_tables.xls", append svy percent cells(col) f(1)
* }
* }

*----- Table 3.20 - Percent distribution of household respondents' top sources of
*       medicine subsidization (i.e., LGU, employer, etc.) in the past 6 months -----
* universe: households | breakdown: none stated | status: partial
* PARTIAL: Free-source codes cover PCP/LGU/public/private hospital only; no employer or
*   dedicated subsidy-source item (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q74_where_rest_XX = strpos(q74_where_rest, "XX") > 0  // one per code
* gen byte q74_where_rest_other_txt_XX = strpos(q74_where_rest_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q74_where_rest q74_where_rest_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.21 - Percentage distribution of household respondents that have accessed
*       alternate financial assistance program/s to help cover medical costs, for most recent
*       interaction, out of all patients -----
* universe: households (all patients) | breakdown: none stated | status: partial
* PARTIAL: No direct assistance-program item; derive Q143 codes 06-08 (+04/05 coping);
*   MAIFIP use not asked; all-patient base via Q103
* capture noisily {
* foreach v in q143_how_paid q103_care_type {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.22 - Percentage distribution of household respondents that have accessed
*       alternate financial assistance program/s to help cover medical costs, for most recent
*       interaction, out of billed patients -----
* universe: households (billed patients) | breakdown: none stated | status: partial
* PARTIAL: Same Q143 derivation as 3.21; billed universe derived via Q139>0/Q140;
*   Q142=No skips Q143
* DERIVED: Same Q143 derivation as 3.21; billed universe derived via Q139>0/Q140;
*   Q142=No skips Q143
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* capture noisily {
* foreach v in q143_how_paid q139_final_amount_php q140_recall_breakdown {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.23 - Percentage distribution of household respondents that experience
*       incidence of reduced care due to financial reasons, for most recent interaction -----
* universe: households | breakdown: none stated | status: mapped
* note: 'Reduced care' = P block: delayed care Q197 + not-fully-followed advice Q198
*   (financial reasons); distinct from forgone 3.24/3.25
capture noisily {
foreach v in q197_delayed_care q198_not_followed {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 3.24 - Percentage distribution of household respondents that experience
*       incidence of forgone care due to financial reasons, for most recent interaction -----
* universe: households | breakdown: none stated | status: mapped
* note: printed with identical description to Table 3.25 | Financial-reason filter via
*   Q106 code 02 'too expensive'; Q196_FOREGONE gives type of care foregone
capture noisily {
foreach v in q105_forgone_care q106_forgone_why {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 3.25 - Percentage distribution of household respondents that experience
*       incidence of forgone care due to financial reasons, for most recent interaction -----
* universe: households | breakdown: none stated | status: mapped
* note: printed with identical description to Table 3.24 | As printed, identical to 3.24
*   - same source mapping
capture noisily {
foreach v in q105_forgone_care q106_forgone_why {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 3.26 - Percentage distribution of household respondents who have heard
*       about ZBB -----
* universe: households | breakdown: none stated | status: mapped
capture noisily svy: tab q132_zbb_heard, percent
capture noisily tabout q132_zbb_heard using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 3.27 - Percentage distribution of household respondents' top information
*       sources about ZBB -----
* universe: households | breakdown: none stated | status: mapped
* note: (checkbox multi); gated on Q132=Yes
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q133_zbb_source_XX = strpos(q133_zbb_source, "XX") > 0  // one per code
* gen byte q133_zbb_source_other_txt_XX = strpos(q133_zbb_source_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q133_zbb_source q133_zbb_source_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.28 - Percentage distribution of household respondents who can correctly
*       identify the benefits under ZBB -----
* universe: households | breakdown: none stated | status: mapped
* DERIVED: (checkbox multi); correct-benefit scoring derived at analysis
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q134_zbb_understand_XX = strpos(q134_zbb_understand, "XX") > 0  // one per code
* gen byte q134_zbb_understand_other_txt_XX = strpos(q134_zbb_understand_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q134_zbb_understand q134_zbb_understand_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.29 - Percentage distribution of household respondents who have heard
*       about BUCAS -----
* universe: households | breakdown: none stated | status: mapped
* note: Block gated on AREA_HAS_BUCAS - denominator excludes non-BUCAS areas
capture noisily svy: tab q57_bucas_heard, percent
capture noisily tabout q57_bucas_heard using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 3.30 - Percentage distribution of household respondents' top information
*       sources about BUCAS -----
* universe: households | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q58_bucas_source_XX = strpos(q58_bucas_source, "XX") > 0  // one per code
* gen byte q58_bucas_source_other_txt_XX = strpos(q58_bucas_source_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q58_bucas_source q58_bucas_source_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.31 - Percentage distribution of household respondents who can correctly
*       identify the benefits under BUCAS -----
* universe: households | breakdown: none stated | status: mapped
* DERIVED: (checkbox multi); correct-benefit scoring derived at analysis
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q59_bucas_understand_XX = strpos(q59_bucas_understand, "XX") > 0  // one per code
* gen byte q59_bucas_understand_other_txt_XX = strpos(q59_bucas_understand_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q59_bucas_understand q59_bucas_understand_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.32 - Percentage distribution of household respondents' mostly accessed
*       services in BUCAS centers -----
* universe: households | breakdown: none stated | status: mapped
* note: (checkbox multi); universe = Q60=Yes accessors, last 6 months
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q60_bucas_accessed_XX = strpos(q60_bucas_accessed, "XX") > 0  // one per code
* gen byte q61_bucas_services_XX = strpos(q61_bucas_services, "XX") > 0  // one per code
* gen byte q61_bucas_services_other_txt_XX = strpos(q61_bucas_services_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q60_bucas_accessed q61_bucas_services q61_bucas_services_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.33 - Percentage distribution of household respondents who have heard
*       about GAMOT -----
* universe: households | breakdown: none stated | status: mapped
* note: Block gated on AREA_HAS_GAMOT - denominator excludes non-GAMOT areas
capture noisily svy: tab q69_gamot_heard, percent
capture noisily tabout q69_gamot_heard using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 3.34 - Percentage distribution of household respondents' top information
*       sources about GAMOT -----
* universe: households | breakdown: none stated | status: mapped
* note: (checkbox multi)
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q70_gamot_source_XX = strpos(q70_gamot_source, "XX") > 0  // one per code
* gen byte q70_gamot_source_other_txt_XX = strpos(q70_gamot_source_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q70_gamot_source q70_gamot_source_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.35 - Percentage distribution of household respondents who can correctly
*       identify the benefits under GAMOT -----
* universe: households | breakdown: none stated | status: mapped
* DERIVED: (checkbox multi); correct-benefit scoring derived at analysis
* gen <derived_var> = ...   // TODO derive per recipe above, then tab it
* CHECKBOX: split alpha multi-code field into dummies before tab:
* gen byte q71_gamot_understand_XX = strpos(q71_gamot_understand, "XX") > 0  // one per code
* gen byte q71_gamot_understand_other_txt_XX = strpos(q71_gamot_understand_other_txt, "XX") > 0  // one per code
* capture noisily {
* foreach v in q71_gamot_understand q71_gamot_understand_other_txt {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex3_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 3.36 - Descriptive statistics of socio-demographic characteristics of the
*       household sample -----
* universe: households | breakdown: none stated | status: mapped
* note: Respondent B-block + roster C-block; Q3_SEX has extra 'Other' code (codebook
*   15.A sex_other flag)
* stat_type 'descriptive stats': skeleton uses svy: mean over the component items; composite recipe TBD
capture noisily svy: mean q2_1_age q3_sex q4_lgbtqia q5_group q6_civil_status q7_is_pwd q11_education q12_employment q13_income_source q14_ip_member q16_4ps q18_income_bracket q19_hh_size_total q20_hh_children q21_hh_seniors q29_socioeconomic_class q32_age q33_sex q34_relationship q40_education q41_employment
* no breakdown var: tabout sum needs a row variable - read the svy: mean results from the log

