* 40_annex4.do - Annex 4 - F2 health-care worker survey table skeletons (Stata 12)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
version 12

capture erase "$OUT_DIR/annex4_tables.xls"
capture confirm file "$DATA_DIR/f2.dta"
if _rc {
    display as error "f2.dta missing (ETL f2_clean.csv TODO) - skipping Annex 4"
    exit
}
use "$DATA_DIR/f2.dta", clear

*----- Table 4.1 - Number of healthcare workers per facility at point of survey, across
*       level of facility and type of worker -----
* universe: facilities | breakdown: by facility level x worker type | status: partial
* PARTIAL: no headcount item in F2/F1; derive respondent count per facility_id x Q5.
*   F2=census in facilities; wt=facility base wt x NR (SSRCS A-d)
* f_type comes from the facility master-list join (see plan notes)
* TODO breakdown dim(s) with no standard bygroup var yet: worker type
* stat_type 'summary': skeleton uses svy: mean over the component items; composite recipe TBD
* capture noisily svy: mean facility_id q5, over(f_type)
* capture noisily tabout f_type using "$OUT_DIR/annex4_tables.xls", append svy sum cells(mean facility_id mean q5) f(2)

*----- Table 4.2 - Average gap (%) in health workers per facility over the past year at
*       the time of survey, across level of facility and type of worker -----
* universe: facilities | breakdown: by facility level x worker type | status: gap
* GAP - no source in instrument: no vacancy/plantilla item in F2 or F1 (F1 Q35/Q36
*   staffing items are qualitative); needs admin/HRH source (e.g. DOH HRH deployment
*   reports)

*----- Table 4.3 - Percentage distribution of healthcare worker respondents who have
*       ever heard about UHC -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q12, percent
capture noisily tabout q12 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.4 - Percentage distribution of healthcare worker respondents who reported
*       doing tasks that could be completed by a more junior staff -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: printed with identical description to Table 4.5 | same source as 4.5 (as
*   printed, identical)
capture noisily {
foreach v in q91 q92 q93 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.5 - Percentage distribution of healthcare worker respondents who reported
*       doing tasks that could be completed by a more junior staff -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: printed with identical description to Table 4.4 | same source as 4.4 (as
*   printed, identical)
capture noisily {
foreach v in q91 q92 q93 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.6 - Percentage distribution of healthcare worker respondents' reasons for
*       taking on tasks that should be performed by a different role -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q94, percent
capture noisily tabout q94 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.7 - Percentage distribution of healthcare worker respondents' views on
*       Task Sharing across roles -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
capture noisily svy: tab q95, percent
capture noisily tabout q95 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.8 - Percentage distribution of healthcare worker respondents who reported
*       receiving adequate support from their facilities to implement changes related to UHC, in
*       the past year -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
capture noisily {
foreach v in q96 q97 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.9 - Percentage distribution of healthcare worker respondents who reported
*       receiving adequate support from their facilities to implement changes related to UHC, in
*       the past year (continued) -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: printed as (continued) of Table 4.8 | same source battery as 4.8
capture noisily {
foreach v in q96 q97 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.10 - Percentage distribution of healthcare worker respondents who would
*       consider becoming YAKAP/Konsulta providers, if not already registered -----
* universe: HCWs not already registered as YAKAP/Konsulta providers | breakdown: none stated |
*   status: mapped
* note: Q38 would-consider distribution; universe filter Q34 != Yes (not already
*   accredited)
capture noisily {
foreach v in q38 q34 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.11 - Percentage distribution of healthcare worker respondents'
*       satisfaction on compensation, over the past 6 months -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: Grid#1 compensation rows, 6-month recall
capture noisily {
foreach v in q98 q99 q100 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.12 - Percent of facilities who provide adequate professional development
*       opportunities for healthcare workers, over the past 6 months -----
* universe: facilities | breakdown: none stated | status: partial
* PARTIAL: facility-level % from HCW-level Q112 ('None'=not provided) aggregated by
*   facility_id; aggregation rule needs DOH sign-off
* capture noisily {
* foreach v in q112 facility_id {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 4.13 - Percentage distribution of healthcare worker respondents'
*       satisfaction on available professional development/training opportunities, over the past
*       6 months -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: Grid#1 prof-dev satisfaction row; provision side = Q112/Q113
capture noisily svy: tab q107, percent
capture noisily tabout q107 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.14 - Percentage distribution of healthcare worker respondents rating on
*       the intensity of workload based on amount of overtime, over the past 6 months -----
* universe: HCWs in selected facilities | breakdown: none stated | status: mapped
* note: Q114 Grid#2 overtime frequency; Q122 overtime amount (asked unless Q114=Never)
capture noisily {
foreach v in q114 q122 {
    svy: tab `v', percent
    tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
}
}

*----- Table 4.15 - Percentage distribution of healthcare worker respondents'
*       satisfaction rating, over the past 6 months -----
* universe: HCWs in selected facilities | breakdown: none stated | status: partial
* PARTIAL: no single overall-satisfaction item; Grid#1 agreement battery -
*   composite/derivation rule needed
* capture noisily svy: tab q98-q107, percent
* capture noisily tabout q98-q107 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.16 - Percentage distribution of healthcare worker respondents on top
*       factors for job satisfaction and dissatisfaction, over the last 6 months -----
* universe: HCWs in selected facilities | breakdown: none stated | status: partial
* PARTIAL: no direct top-factors item; derive factor ranking from Grid#1/Grid#2
*   batteries - derivation rule needs DOH sign-off
* capture noisily {
* foreach v in q98-q107 q114-q121 {
*     svy: tab `v', percent
*     tabout `v' using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)
* }
* }

*----- Table 4.17 - Percentage distribution of healthcare worker respondents who
*       intended to leave current post in the next year -----
* universe: HCWs in selected facilities | breakdown: none stated | status: partial
* PARTIAL: Q123 captures intent strength but no explicit next-year horizon
* capture noisily svy: tab q123, percent
* capture noisily tabout q123 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.18 - Percentage distribution of healthcare worker respondents on top
*       reasons for healthcare workers who intend to leave in less than a year -----
* universe: HCWs who intend to leave in less than a year | breakdown: none stated | status:
*   partial
* PARTIAL: Q124 reasons; universe Q123=any yes - '<1 year' horizon not captured by Q123
* capture noisily svy: tab q124, percent
* capture noisily tabout q124 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.19 - Percentage distribution of healthcare workers by role in the health
*       facility -----
* universe: HCWs in selected facilities | breakdown: by role in the health facility | status:
*   mapped
* TODO breakdown dim(s) with no standard bygroup var yet: role in the health facility
capture noisily svy: tab q5, percent
capture noisily tabout q5 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

*----- Table 4.20 - Percentage distribution of healthcare workers by specialization in
*       the health facility -----
* universe: HCWs in selected facilities | breakdown: by specialization in the health facility |
*   status: mapped
* TODO breakdown dim(s) with no standard bygroup var yet: specialization in the health
*   facility
capture noisily svy: tab q6, percent
capture noisily tabout q6 using "$OUT_DIR/annex4_tables.xls", append svy oneway percent cells(cell) f(1)

