* run.do - UHC Y2 tabulation plan, master runner (Stata 12)
* GENERATED by build_dofiles.py - do NOT hand-edit; edit the generator and re-run.
* Batch run:  "C:\Users\analy\Downloads\Stata 12\StataSE.exe" /e do run.do
version 12
clear all
set more off
set linesize 120
capture log close

* ---------------- globals ----------------
global DATA_DIR "data"
global OUT_DIR  "out"
* NOWEIGHT toggle: 1 = run UNWEIGHTED (weights wf arrive post-collection);
*                  0 = use the real svyset designs with [pweight=wf].
global NOWEIGHT 1

capture mkdir "$DATA_DIR"
capture mkdir "$OUT_DIR"
capture mkdir "logs"

log using "logs/run.log", text replace

do 00_import.do
do 01_svyset.do
do 10_annex1.do
do 20_annex2.do
do 30_annex3.do
do 40_annex4.do

log close
