"""generate_apc.py — emit FacilityHeadSurvey.ent.apc.

Phase 1 minimal F1 logic: no skip-logic / validations / GPS / photo / PSGC
cascade (all deferred to Phase 2 spec-driven build). No sync logic either —
syncing F1 case data to CSWeb is handled natively by CSPro Android's
Synchronize -> Send data UI (no custom syncdata in F1's logic). Per spec
2026-05-11-uhc-phase-1-f1-native-sync-design.md. F1 is pure data entry.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'FacilityHeadSurvey' logic file generated by CSPro }
{ Phase 1: minimal — pure data entry. Skip-logic + validations + GPS + photo
  + PSGC cascade all deferred to Phase 2 spec-driven build. Sync is handled
  natively by CSPro Android (Synchronize -> Send data UI); no custom syncdata
  in F1's logic. Per spec 2026-05-11-uhc-phase-1-f1-native-sync-design.md. }

PROC GLOBAL


PROC FACILITYHEADSURVEY_LEVEL
'''


def main():
    (HERE / "FacilityHeadSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote FacilityHeadSurvey.ent.apc ({len(APC)} chars; pure data entry, native sync)")


if __name__ == "__main__":
    main()
