"""generate_apc.py — emit FacilityHeadSurvey.ent.apc.

Phase 1 minimal F1 logic: no skip-logic / validations / GPS / photo / PSGC
cascade (all deferred to Phase 2 spec-driven build). No sync logic either —
syncing F1 case data to CSWeb is the job of the separate 109_sync app
(E3-F1-088 Fix B1), launched from menu_app's "Sync data to server" choice.
F1 is now pure data entry.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'FacilityHeadSurvey' logic file generated by CSPro }
{ Phase 1: minimal — pure data entry. Skip-logic + validations + GPS + photo
  + PSGC cascade all deferred to Phase 2 spec-driven build. Sync handled by
  the separate 109_sync entry app per E3-F1-088 Fix B1. }

PROC GLOBAL


PROC FACILITYHEADSURVEY_LEVEL
'''


def main():
    (HERE / "FacilityHeadSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote FacilityHeadSurvey.ent.apc ({len(APC)} chars; pure data entry, sync deferred to 109_sync)")


if __name__ == "__main__":
    main()
