"""generate_apc.py — emit FacilityHeadSurvey.ent.apc.

Phase 1 strategy:
  1. Read the existing F1 .apc from the main checkout (Carl's working logic).
  2. Prepend #include directives for Sync-Helpers.apc + Expiration-Guard.apc.
  3. Write into 107_F1/.

Phase 2 will refactor to fully spec-driven generation (skip-logic from
F1-Skip-Logic-and-Validations.md emitted as PROC blocks).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEGACY_APC = Path(
    r"C:\Users\analy\Documents\analytiflow\1_Projects\ASPSI-DOH-CAPI-CSPro-Development"
    r"\deliverables\CSPro\F1\FacilityHeadSurvey.ent.apc"
)

def main():
    """Phase 1: emit minimal F1.ent.apc matching legacy shape (1-line comment).
    F1's existing logic (skip-logic, validations, GPS, photo, PSGC) was never
    coded in the legacy .apc and lives only in F1-Skip-Logic-and-Validations.md.
    Phase 2 will spec-drive PROC blocks from that doc."""
    body = "﻿{ Application 'FacilityHeadSurvey' logic file generated by CSPro }\n"
    (HERE / "FacilityHeadSurvey.ent.apc").write_text(body, encoding="utf-8")
    print(f"wrote FacilityHeadSurvey.ent.apc ({len(body)} chars, minimal Phase 1)")


if __name__ == "__main__":
    main()
