"""generate_apc.py — emit HouseholdSurvey.ent.apc.

F4 Household Survey logic. Implements F4-Skip-Logic-and-Validations.md.

Commits in the F4 quartet build:
  - commit 3 (this commit): GLOBAL + FIELD_CONTROL + Sections A-C
                            (Q1 IS_HH_HEAD, Section B Q4-Q14 demographics,
                            Section C household roster gating, Section C
                            private-insurance gate).
  - commit 4: Sections D-G (UHC awareness, YAKAP/Konsulta, BUCAS
              settings-gate, Access to Medicines + GAMOT settings-gate +
              brand/generic).
  - commit 5: Sections H-K (PhilHealth registration, Primary Care
              Utilization, Health-Seeking Behavior, Referrals).
  - commit 6: Sections L-M (NBB + Q130 hospital-type gate, ZBB + MAIFIP +
              Q136 transcription-artifact handling).
  - commit 7: Section N expenditure quads + 4 computed-totals
              (Q157/Q177/Q182/Q185).
  - commit 8: Sections O-Q + HARD edits + range checks + SOFT warnings +
              end-of-survey terminators.
  - commit 9: Household-pick stub PROC + respondent-row-1 auto-fill in
              C_HOUSEHOLD_ROSTER.preproc.

Reference: F4-Skip-Logic-and-Validations.md (this folder).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'HouseholdSurvey' logic file generated by CSPro }
{ F4 Household Survey CAPI app -- skip-logic + validations per             }
{ F4-Skip-Logic-and-Validations.md.                                         }
{                                                                           }
{ Commit 3 of 9 (F4 quartet build): GLOBAL + FIELD_CONTROL + Sections A-C. }
{ Commits 4-9 will append D-Q + edits + household-pick stub + roster auto- }
{ fill.                                                                    }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Income bracket boundaries (validation H4) ----------------------- }
{                                                                       }
{ Six brackets from Q18_INCOME_BRACKET value set in HouseholdSurvey.dcf.}
{ Used by the Q18 postproc consistency check and held here as named     }
{ constants so the bracket cutoffs are auditable without scrolling into }
{ the PROC body.                                                        }

numeric BRACKET_1_HI =    39999;   { Under 40,000          }
numeric BRACKET_2_LO =    40000;
numeric BRACKET_2_HI =    59999;   { 40,000 - 59,999       }
numeric BRACKET_3_LO =    60000;
numeric BRACKET_3_HI =    99999;   { 60,000 - 99,999       }
numeric BRACKET_4_LO =   100000;
numeric BRACKET_4_HI =   249999;   { 100,000 - 249,999     }
numeric BRACKET_5_LO =   250000;
numeric BRACKET_5_HI =   499999;   { 250,000 - 499,999     }
numeric BRACKET_6_LO =   500000;   { 500,000 and over      }


{ ---- AAPOR sentinel + visit-result codes ---------------------------- }
{                                                                       }
{ Mirrored from shared/cspro_helpers.py::AAPOR_DISPOSITION_OPTIONS and  }
{ ENUM_RESULT_OPTIONS. Held as APC constants so end-of-case dispositions}
{ are readable in the PROC code without consulting the DCF value sets.  }

numeric AAPOR_IN_PROGRESS         =   0;   { 000 - In Progress (initial)    }
numeric AAPOR_COMPLETE            = 110;   { 1.1 - Complete interview        }
numeric AAPOR_REFUSED             = 220;   { 2.20 - Refusal / break-off      }

numeric VISIT_RESULT_COMPLETED            = 1;
numeric VISIT_RESULT_WITHDRAW_CONSENT     = 6;


{ ---- Helper: end-of-section terminator ------------------------------ }

function CloseCaseAsComplete()
    { Set the closing AAPOR + visit-result codes when a respondent
      completes through the final terminus item. Wired from Section Q
      Q201_WORRIED_FINANCES and the early-exit Q200 Refused path.

      Unlike F3, F4 has no listing-roster write-back (the
      113_F4_listing app is not yet built; when it lands, this function
      is updated to stamp F4_STATUS on the household-roster row -- see
      commit 9 stub). }
    AAPOR_DISPOSITION        = AAPOR_COMPLETE;
    ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_COMPLETED;
    DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
end;


{ ===================================================================== }
{  Household-pick stub -- activated when 113_F4_listing app lands       }
{ ===================================================================== }
{ STUB: Until 113_F4_listing exists, HH_LISTING_NO is populated by the  }
{ enumerator manually in the FIELD_CONTROL form. The stub PROC below   }
{ stays in place so the wiring activates without surgery when the      }
{ listing app lands; see commit 9 (household-pick stub) for the         }
{ load-bearing preproc declaration.                                    }


PROC HOUSEHOLDSURVEY_LEVEL
preproc
    { STUB: When 113_F4_listing app lands (task #7 of the F4 rebuild
      plan), this preproc will:
        1. Call PickHousehold() to query F4LISTING_DICT for eligible
           households at this barangay listing.
        2. Stamp CASE_SEQ from the enumerator's f4_seq_lo..hi range.
        3. Stamp REGION_CODE..FACILITY_NO from login settings.
        4. Stamp HH_LISTING_NO from the chosen roster row.
        5. Stamp F4_STATUS = 2 (in-progress) on the listing roster.

      Until then: enumerator enters HH_LISTING_NO manually in the
      FIELD_CONTROL form. F4_PARENT_F3_CASE_SEQ defaults to 999 (NA per
      F-series convention) -- the protocol-conformant barangay-listing
      sampling path. }


{ ===================================================================== }
{  FIELD_CONTROL -- case-start setup                                     }
{ ===================================================================== }

PROC FIELD_CONTROL
preproc
    SURVEY_CODE        = "F4";
    DATE_STARTED       = SYSDATE("YYYYMMDD");
    TIME_STARTED       = SYSTIME("HHMMSS");
    AAPOR_DISPOSITION  = AAPOR_IN_PROGRESS;

    { DATE_FIRST_VISITED defaults to today if the operator does not
      override on the first visit. }
    if DATE_FIRST_VISITED = 0 then
        DATE_FIRST_VISITED = SYSDATE("YYYYMMDD");
    endif;

    { F4_PARENT_F3_CASE_SEQ defaults to 999 (NA per F-series convention)
      when the F4 case was sampled via barangay listing -- the protocol-
      conformant path. Set only on the 110_F3_listing patient interval-
      walk path (LISTING_TAG=2 listing); not implemented yet. }
    if F4_PARENT_F3_CASE_SEQ = 0 then
        F4_PARENT_F3_CASE_SEQ = 999;
    endif;


PROC HH_LISTING_NO
postproc
    { Required (Option C dual-linkage rule): HH_LISTING_NO must always
      be populated and never default to 0 or 9999 (NA). When the
      113_F4_listing app lands, this value is auto-stamped by the
      household-pick PROC; the manual-entry path runs until then. }
    if HH_LISTING_NO = 0 or HH_LISTING_NO = 9999 then
        errmsg("HH_LISTING_NO must be a valid barangay-listing roster "
               "reference (1-9998). 0 / 9999 are not acceptable. Please "
               "re-check the household listing form before proceeding.");
        reenter;
    endif;


PROC CONSENT_GIVEN
postproc
    { Hard terminator: if the household withdraws consent at the
      read-out, mark the case withdrawn and end the interview. The
      operator is expected to save the partial case so the disposition
      is preserved for paradata. Per F4-Skip-Logic-and-Validations.md
      §2 Section A ("Terminate interview" rule). }
    if CONSENT_GIVEN = 2 then   { 2 = No }
        AAPOR_DISPOSITION        = AAPOR_REFUSED;
        ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_WITHDRAW_CONSENT;
        DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
        endcase;
    endif;


{ ===================================================================== }
{  Section A -- Introduction and Informed Consent (Q1)                  }
{ ===================================================================== }

PROC Q1_IS_HH_HEAD
postproc
    { Per spec §2 Section A: Q1 = No (2) triggers locate-HH-head
      handler. If unable to locate, set ENUM_RESULT_FINAL_VISIT = 4
      (Refused / No HH head available) and terminate.

      For MVP: errmsg the operator to attempt locating the HH head.
      The operator can then either:
        - re-answer Q1 = Yes once the head is located, OR
        - press Stop-case to abort if not locatable.

      Open question #4 in spec -- definitive routing pending Myra's
      Survey Manual edit pass. }
    if Q1_IS_HH_HEAD = 2 then   { 2 = No }
        errmsg("Respondent is not the household head. Per Protocol "
               "Section 3, attempt to locate the household head before "
               "proceeding. If not locatable, press Stop-case to "
               "terminate (visit-result will be set to 'No HH head "
               "available').");
        { soft -- operator confirms by accepting; no reenter. }
    endif;


{ ===================================================================== }
{  Section B -- Respondent Profile (Q2-Q29)                              }
{ ===================================================================== }

PROC Q2_BIRTH_MONTH
postproc
    { Range check: month 1..12 (per spec §3 Range Checks). }
    if Q2_BIRTH_MONTH < 1 or Q2_BIRTH_MONTH > 12 then
        errmsg("Birth month must be between 1 and 12. Please re-check.");
        reenter;
    endif;


PROC Q2_BIRTH_YEAR
postproc
    { Range check: year 1900..current_year (per spec §3 Range Checks). }
    numeric this_year = tonumber(SYSDATE("YYYY"));
    if Q2_BIRTH_YEAR < 1900 or Q2_BIRTH_YEAR > this_year then
        errmsg("Birth year must be between 1900 and %v. Please re-check.",
               this_year);
        reenter;
    endif;


PROC Q2_1_AGE
postproc
    { Age range + age-vs-birth-year consistency (HARD edit H1 per spec
      §3). Allow off-by-one on calendar-rollover edge case. }
    if Q2_1_AGE < 0 or Q2_1_AGE > 130 then
        errmsg("Age must be between 0 and 130. Please re-check.");
        reenter;
    endif;

    numeric calc_age = tonumber(SYSDATE("YYYY")) - Q2_BIRTH_YEAR;
    if abs(calc_age - Q2_1_AGE) > 1 then
        errmsg("Age (%v) inconsistent with birth year %v (computed "
               "%v). Please re-check.",
               Q2_1_AGE, Q2_BIRTH_YEAR, calc_age);
        reenter;
    endif;


PROC Q4_LGBTQIA
postproc
    { Per spec §2 Section B: Q4 in (2,3,4,5) -> Q6 (skip Q5).
      Only Q4 = 1 (Yes) routes through Q5. }
    if Q4_LGBTQIA in 2, 3, 4, 5 then
        skip to Q6_CIVIL_STATUS;
    endif;


PROC Q5_GROUP_OTHER_TXT
preproc
    { Other-specify gate: only ask the txt field when Q5 = 8 (Other). }
    if Q5_GROUP <> 8 then
        skip to Q6_CIVIL_STATUS;
    endif;
postproc
    if Q5_GROUP = 8 and strlen(strip(Q5_GROUP_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' LGBTQIA group.");
        reenter;
    endif;


PROC Q7_PWD
postproc
    { Per spec §2 Section B: Q7 = No -> Q11 (skip Q8, Q9, Q10). }
    if Q7_PWD = 2 then   { 2 = No }
        skip to Q11_EDUCATION;
    endif;


PROC Q8_PWD_SPECIFY
postproc
    { Per spec §2 Section B: Q8 = No -> Q11 (skip Q9, Q10). }
    if Q8_PWD_SPECIFY = 2 then   { 2 = No }
        skip to Q11_EDUCATION;
    endif;


PROC Q9_PWD_CARD
postproc
    { Card-gate (per spec §3 HARD consistency: PWD card gating):
      Q10 only when Q9 = 1 (Yes -- card presented and verified).
      Otherwise skip to Q11. }
    if Q9_PWD_CARD <> 1 then
        skip to Q11_EDUCATION;
    endif;


PROC Q10_DISABILITY_OTHER_TXT
preproc
    if Q10_DISABILITY_TYPE <> 8 then   { 8 = Other disability (specify) }
        skip to Q11_EDUCATION;
    endif;
postproc
    if Q10_DISABILITY_TYPE = 8 and
       strlen(strip(Q10_DISABILITY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' disability type.");
        reenter;
    endif;


PROC Q14_IP
postproc
    { Per spec §2 Section B: Q14 = No -> Q16 (skip Q15). }
    if Q14_IP = 2 then   { 2 = No }
        skip to Q16_4PS;
    endif;


PROC Q17_DECISION_MAKER_OTHER_TXT
preproc
    { Per Q17 value set -- "Other (specify)" likely a high code. The DCF
      generator's value set fixes the code; for now treat code = 5 as
      Other based on the archived F4 generator. PROC will be re-pointed
      if Q17 value set changes. }
    if Q17_DECISION_MAKER <> 5 then
        skip to Q18_INCOME_AMOUNT;
    endif;
postproc
    if Q17_DECISION_MAKER = 5 and
       strlen(strip(Q17_DECISION_MAKER_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' household decision-maker.");
        reenter;
    endif;


PROC Q18_INCOME_BRACKET
postproc
    { HARD edit: Q18_INCOME_AMOUNT must fall in Q18_INCOME_BRACKET range
      (per spec §3 HARD consistency: Income amount vs bracket). }
    numeric lo;
    numeric hi;

    if      Q18_INCOME_BRACKET = 1 then lo = 0;              hi = BRACKET_1_HI;
    elseif  Q18_INCOME_BRACKET = 2 then lo = BRACKET_2_LO;   hi = BRACKET_2_HI;
    elseif  Q18_INCOME_BRACKET = 3 then lo = BRACKET_3_LO;   hi = BRACKET_3_HI;
    elseif  Q18_INCOME_BRACKET = 4 then lo = BRACKET_4_LO;   hi = BRACKET_4_HI;
    elseif  Q18_INCOME_BRACKET = 5 then lo = BRACKET_5_LO;   hi = BRACKET_5_HI;
    elseif  Q18_INCOME_BRACKET = 6 then lo = BRACKET_6_LO;   hi = 9999999;
    endif;

    if not (Q18_INCOME_AMOUNT >= lo and Q18_INCOME_AMOUNT <= hi) then
        errmsg("Income amount %v is outside bracket %v (%v - %v). "
               "Please re-check.",
               Q18_INCOME_AMOUNT, Q18_INCOME_BRACKET, lo, hi);
        reenter;
    endif;


PROC Q19_HH_SIZE
postproc
    { Range check: 1..30 (per spec §3 Range Checks). }
    if Q19_HH_SIZE < 1 or Q19_HH_SIZE > 30 then
        errmsg("Household size must be between 1 and 30. Please re-check.");
        reenter;
    endif;

    { SOFT warning S1: HH size > 15 is unusual; ask to verify. }
    if Q19_HH_SIZE > 15 then
        errmsg("Household size %v is unusually large. Please confirm.",
               Q19_HH_SIZE);
        { soft -- no reenter. }
    endif;


PROC Q20_HH_CHILDREN
postproc
    { Range check: 0..Q19 (per spec §3 Range Checks). }
    if Q20_HH_CHILDREN < 0 or Q20_HH_CHILDREN > Q19_HH_SIZE then
        errmsg("HH children count must be between 0 and %v "
               "(the household size). Please re-check.",
               Q19_HH_SIZE);
        reenter;
    endif;


PROC Q21_HH_SENIORS
postproc
    { Range check: 0..Q19 (per spec §3 Range Checks). }
    if Q21_HH_SENIORS < 0 or Q21_HH_SENIORS > Q19_HH_SIZE then
        errmsg("HH seniors count must be between 0 and %v "
               "(the household size). Please re-check.",
               Q19_HH_SIZE);
        reenter;
    endif;

    { Composition sanity -- children + seniors cannot exceed total. }
    if Q20_HH_CHILDREN + Q21_HH_SENIORS > Q19_HH_SIZE then
        errmsg("Children %v + seniors %v exceeds total HH size %v. "
               "Please re-check.",
               Q20_HH_CHILDREN, Q21_HH_SENIORS, Q19_HH_SIZE);
        reenter;
    endif;


PROC Q23_WATER_OTHER_TXT
preproc
    if Q23_WATER <> 4 then   { 4 = Other (specify) }
        skip to Q24_FAUCET_OWN;
    endif;
postproc
    if Q23_WATER = 4 and strlen(strip(Q23_WATER_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' water source.");
        reenter;
    endif;


{ ===================================================================== }
{  Section C -- Household Roster + Private-Insurance Sub-Roster         }
{ ===================================================================== }
{ Note: Section C roster preproc (auto-fill respondent row 1 from        }
{ Q2_1_AGE / Q3_SEX / Q1_IS_HH_HEAD) lives in commit 9. Section C        }
{ post-section consistency check (totocc == Q19_HH_SIZE) also commit 9.  }

PROC C_HOUSEHOLD_ROSTER
preproc
    { STUB -- commit 9 fills the respondent-row-1 auto-fill logic:
        if curocc() = 1 then
            Q32_AGE          = Q2_1_AGE;
            Q33_SEX          = Q3_SEX;
            if Q1_IS_HH_HEAD = 1 then
                Q34_RELATIONSHIP = 1;   { 01 = Head }
            endif;
        endif;
      For commit 3 the preproc is empty so the .apc compiles. }


PROC Q47_HAS_PRIVATE_INS
postproc
    { Per spec §2 Section C: Q47 = No (2) -> Q51 (skip Section C
      private-insurance roster). The PROC routes past the
      C_PRIVATE_INSURANCE_ROSTER record by jumping to the Section D
      entry Q51_HEARD_UHC.

      When Q47 = Yes (1) the operator is taken into the private-
      insurance roster occurrences; max_occurs = 10 per the DCF. }
    if Q47_HAS_PRIVATE_INS = 2 then   { 2 = No }
        skip to Q51_HEARD_UHC;
    endif;


{ Sections D-Q + edits + household-pick stub + roster auto-fill land in }
{ commits 4-9. The .apc file ends here for commit 3.                     }
'''


def main():
    (HERE / "HouseholdSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote HouseholdSurvey.ent.apc ({len(APC)} chars; "
          f"commit 3/9 -- GLOBAL + FIELD_CONTROL + Sections A-C)")


if __name__ == "__main__":
    main()
