#!/usr/bin/env python3
"""SupervisorApp — CAPI logic (.ent.apc) generator.

Emits SupervisorVisitLog.ent.apc. The shared GPS + photo helpers are INLINED
into the single PROC GLOBAL (CSEntry forbids #include and any code before the
first PROC — verified 2026-06-08; same mechanism as F1 generate_apc._inline_shared).
Iron rule: never hand-edit the .ent.apc — edit this generator and rerun.

Invoke:  python generate_apc.py        # writes SupervisorVisitLog.ent.apc
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
SHARED_DIR = HERE.parent / "shared"
OUT = HERE / "SupervisorApp.ent.apc"


def _inline_shared(filename):
    """Return a shared helper module's body with its own 'PROC GLOBAL' header
    stripped, for pasting INSIDE the host's single PROC GLOBAL."""
    text = (SHARED_DIR / filename).read_text(encoding="utf-8")
    body, seen_global = [], False
    for ln in text.splitlines():
        if not seen_global:
            if ln.strip() == "PROC GLOBAL":
                seen_global = True
            continue
        body.append(ln)
    if not seen_global:
        raise RuntimeError(f"{filename}: expected a 'PROC GLOBAL' line to strip")
    return "\n".join(body)


def build_apc():
    return """\
{ ============================================================================
  SupervisorApp — CAPI logic   (AUTOGENERATED by generate_apc.py)
  Do NOT hand-edit: edit generate_apc.py and rerun.
  Phase-3 Supervisor App (Facility Visit Log). Spec:
  docs/superpowers/specs/2026-06-23-supervisor-app-phase3-facility-visit-log-design.md
  ============================================================================ }

PROC GLOBAL

{ Shared GPS + photo helpers inlined here (CSEntry forbids #include and any code
  before the first PROC; inlining into PROC GLOBAL is the only arrangement the
  Designer compiler and the CSEntry loader both accept — verified 2026-06-08). }
""" + _inline_shared("Capture-Helpers.apc") + """

PROC TP_LINE
preproc
  { Occurrence index, auto-set; not entered. }
  TP_LINE = curocc();
  noinput;

PROC TP_TYPE
postproc
  { Auto-stamp GPS + timestamp ONCE per touchpoint, right after the FS picks the
    type, then protect so the row is tamper-evident. TP_TIMESTAMP is the
    captured-once sentinel (it is always set, even when GPS fails on desktop /
    no signal, so the row still carries a time). Desktop has no GPS radio:
    ReadGPSReading returns 0 (getos 10:19 guard) and flows past with no modal. }
  if length(strip(TP_TIMESTAMP)) = 0 then
    if ReadGPSReading(120, 20) then
      TP_GPS_LATITUDE   = maketext("%f", gps(latitude));
      TP_GPS_LONGITUDE  = maketext("%f", gps(longitude));
      TP_GPS_ALTITUDE   = maketext("%f", gps(altitude));
      TP_GPS_ACCURACY   = gps(accuracy);
      TP_GPS_SATELLITES = gps(satellites);
      TP_GPS_READTIME   = maketext("%d", gps(readtime));
    endif;
    TP_TIMESTAMP = maketext("%08d %04d", sysdate("YYYYMMDD"), systime("HHMM"));  { both numeric }
    protect(TP_GPS_LATITUDE, true);
    protect(TP_GPS_LONGITUDE, true);
    protect(TP_GPS_ALTITUDE, true);
    protect(TP_GPS_ACCURACY, true);
    protect(TP_GPS_SATELLITES, true);
    protect(TP_GPS_READTIME, true);
    protect(TP_TIMESTAMP, true);
  endif;

PROC TP_OUTCOME_NOTE
postproc
  { An 'Other' (code 8) touchpoint must carry a note describing what it was. }
  if TP_TYPE = 8 and length(strip(TP_OUTCOME_NOTE)) = 0 then
    errmsg("Please describe the 'Other' touchpoint in the note.");
    reenter;
  endif;

PROC CAPTURE_VERIFICATION_PHOTO
onfocus
  { Optional HCW master-list photo. Reuses the proven binary-Image helper so the
    JPG bytes sync to CSWeb (#713). Only when the FS captured the HCW list. }
  if CC_HCW_LIST_CAPTURED = 1 then
    string fn = maketext("facility-%09d-hcwlist.jpg", FACILITY_CODE);
    if TakeVerificationPhoto(fn) then
      VERIFICATION_PHOTO_FILENAME = fn;
    endif;
  endif;
  CAPTURE_VERIFICATION_PHOTO = notappl;
"""


def main():
    text = build_apc()
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}  ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
