#!/usr/bin/env python3
"""
F4 Household Survey — CAPI logic (.ent.apc) generator.

Emits `HouseholdSurvey.ent.apc` from the reviewed spec
(`F4-Skip-Logic-and-Validations.md`). Same pattern as F1/F3 generate_apc.py.

Covers (generator side): roster loop + per-member skips, #168 roster-count vs
Q19, #167 first-member/cross-member SOFT check, Q47 auto-set, awareness skips
(D-F), Section I primary-care routing, #170 Section M bill-recall chain (gated
on Q129), #169 Section N expenditure consumed-gate (dcf-driven, all *_CONSUMED
items), consent terminator, GPS + photo, UHC9 'Other (specify)'.

  ⚠️  UNVERIFIED until compiled in CSPro Designer + run in CSEntry. Roster /
      occurrence logic (curocc/endocc/count) and skip targets especially need
      CSEntry verification against the generated FMF. Option codes marked
      "(verify)" must be checked against the dcf value sets on first compile.

Invoke:  python generate_apc.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from cspro_helpers import (
    other_specify_procs, select_all_validation_procs, range_check_proc,
)

# Per-item numeric range checks (spec §3.2/§3.6/§3.12). (field, lo, hi, soft_over)
RANGE_CHECKS = [
    ("Q18_INCOME_AMOUNT",      0, 99999999, None),
    ("Q67_TIME_TO_PHARMACY",   0, 1440,     None),
    ("TOTAL_NUMBER_OF_VISITS", 1, 10,       3),
    ("Q199_WTP_CONSULT",       0, 99999999, None),
]

# Cross-field validations needing a custom body (spec §3.1 date ordering).
CUSTOM_VALIDATION = [
    ("DATE_FINAL_VISIT",
     "PROC DATE_FINAL_VISIT\npostproc\n"
     "  if DATE_FINAL_VISIT < DATE_FIRST_VISITED then\n"
     "    errmsg(\"Final-visit date cannot be earlier than the first-visit date.\");\n    reenter;\n  endif;"),
]

HERE = Path(__file__).parent
OUT = HERE / "HouseholdSurvey.ent.apc"
DCF = HERE / "HouseholdSurvey.dcf"
SHARED_DIR = HERE.parent / "shared"


def _inline_shared(filename):
    """Return a shared helper module's body with its own 'PROC GLOBAL' header
    stripped, for pasting INSIDE the host's single PROC GLOBAL.

    Why inline instead of #include (verified 2026-06-08 against the CSEntry loader):
    CSPro forbids `#include` inside a PROC, and CSEntry forbids any code before the
    first PROC -- so an #include of a function library satisfies neither. Inlining
    the helper functions into PROC GLOBAL is the only arrangement both the Designer
    compiler and the CSEntry runtime loader accept.
    """
    text = (SHARED_DIR / filename).read_text(encoding="utf-8")
    body, seen_global = [], False
    for ln in text.splitlines():
        if not seen_global:
            if ln.strip() == "PROC GLOBAL":
                seen_global = True
            continue
        body.append(ln)
    if not seen_global:
        raise RuntimeError(f"{filename}: expected a 'PROC GLOBAL' line to strip")
    return "\n".join(body).strip("\n")


HEADER = """\
{ ============================================================================
  HouseholdSurvey (F4) — CAPI logic   (AUTOGENERATED by generate_apc.py)
  Do NOT hand-edit: edit generate_apc.py's tables and rerun.
  Spec: F4-Skip-Logic-and-Validations.md (reviewed 2026-04-21).
  ============================================================================ }

PROC GLOBAL
numeric currentYYYYMMDD;
numeric currentYear;
numeric currentMonth;

{ Shared helpers inlined into this single PROC GLOBAL (PSGC-Cascade first so its
  ROOT_PSGC_PARENT declaration precedes all functions). #include can't be used:
  CSPro forbids it inside a PROC, and CSEntry forbids code before the first PROC.
  Requires the 4 PSGC external dicts attached to the .ent. }
""" + _inline_shared("PSGC-Cascade.apc") + """

""" + _inline_shared("Capture-Helpers.apc") + """

PROC HOUSEHOLDSURVEY_FF
preproc
  currentYYYYMMDD = sysdate("YYYYMMDD");
  currentYear  = int(currentYYYYMMDD / 10000);
  currentMonth = int(currentYYYYMMDD / 100) % 100;

{ LANGUAGE_USED lives in the FIELD_CONTROL record, so it can't be set from the
  form-file/level preproc ("belongs to a record at a lower level"), and a record
  symbol can't have a PROC. Set it in the preproc of the first FIELD_CONTROL field
  (SURVEY_CODE) — same record, runs at case start. §15.E }
PROC SURVEY_CODE
preproc
  LANGUAGE_USED = getlanguage();
"""

CONTROL_PROCS = """\
{ ---- Informed consent: No (2) terminates the interview ---- }
PROC CONSENT_GIVEN
postproc
  if CONSENT_GIVEN = 2 then
    ENUM_RESULT_FINAL_VISIT = 4;   { Refused / withdrew consent (verify code) }
    errmsg("Respondent declined consent. Interview ends; case coded Refused.");
    endlevel;   { end the CASE on refusal (endgroup only skips this group). The case key
                  is now captured on FORM000 before consent, so the refused case saves. }
  endif;

{ ---- PSGC cascade (household geo-ID; verify item names match the F4 dcf) ---- }
PROC REGION
onfocus
  FillRegionValueSet();
PROC PROVINCE_HUC
onfocus
  FillProvinceValueSet(REGION);
PROC CITY_MUNICIPALITY
onfocus
  FillCityValueSet(PROVINCE_HUC);
PROC BARANGAY
onfocus
  FillBarangayValueSet(CITY_MUNICIPALITY);

{ ---- GPS + verification photo (helpers in Capture-Helpers.apc).
  F4 captures the HOUSEHOLD location: trigger CAPTURE_HH_GPS, fields
  LATITUDE/LONGITUDE + HH_GPS_* per the dcf (not the F1 FACILITY_* names). ---- }
PROC CAPTURE_HH_GPS
onfocus
  if ReadGPSReading(120, 20) then
    LATITUDE          = maketext("%f", gps(latitude));
    LONGITUDE         = maketext("%f", gps(longitude));
    HH_GPS_ALTITUDE   = maketext("%f", gps(altitude));
    HH_GPS_ACCURACY   = gps(accuracy);
    HH_GPS_SATELLITES = gps(satellites);
    HH_GPS_READTIME   = maketext("%d", gps(readtime));
  endif;
  CAPTURE_HH_GPS = notappl;

PROC CAPTURE_VERIFICATION_PHOTO
onfocus
  string fn = "case-" + maketext("%02d%02d%03d%02d%03d", REGION_CODE, PROVINCE_HUC_CODE, CITY_MUNICIPALITY_CODE, FACILITY_NO, CASE_SEQ) + "-verification.jpg";
  if TakeVerificationPhoto(fn) then
    VERIFICATION_PHOTO_FILENAME = fn;
  endif;
  CAPTURE_VERIFICATION_PHOTO = notappl;
"""

# Roster loop (spec 4.5): per-member skips + #167 first-member soft check +
# #168 roster-count = Q19 + Q47 auto-set from any member's private insurance.
ROSTER_PROCS = """\
{ ---- Household roster loop (C_HOUSEHOLD_ROSTER, max 20) ---- }
PROC Q34_RELATIONSHIP
postproc
  { #167: first roster entry is normally Self/Head (soft confirm) }
  if curocc() = 1 and not (Q34_RELATIONSHIP in 1,2) then   { 1=Self, 2=Head (verify codes) }
    errmsg("First roster entry is normally the respondent (Self) or HH head. Confirm.");
  endif;

PROC Q35_HAS_DISABILITY
postproc
  if Q35_HAS_DISABILITY = 2 then
    skip to Q39_CIVIL_STATUS;
  endif;

PROC Q37_PWD_CARD
postproc
  if Q37_PWD_CARD = 2 then
    skip to Q39_CIVIL_STATUS;
  endif;

PROC Q49_PRIVATE_INS
postproc
  if Q49_PRIVATE_INS = 2 then        { no private insurance -> skip Q50, advance to next member }
    skip to next;                    { 'next' = next roster occurrence; valid only inside the repeating group }
  endif;

PROC C_HOUSEHOLD_ROSTER_FORM
postproc
  { #168 roster-count sanity (spec finding #7). Attached to the roster GROUP
    (C_HOUSEHOLD_ROSTER_FORM), NOT the C_HOUSEHOLD_ROSTER record — a record symbol
    can't have a PROC (CSEntry, verified 2026-06-08). The group postproc fires once
    after all occurrences are entered. }
  if count(C_HOUSEHOLD_ROSTER) <> Q19_HH_SIZE_TOTAL then
    { soft warning: reenter is not available from a group postproc, so flag it and
      let the enumerator navigate back to fix the roster or Q19. }
    errmsg("Roster has %d members but Q19 says %d. Go back and reconcile.",
           count(C_HOUSEHOLD_ROSTER), Q19_HH_SIZE_TOTAL);
  endif;

PROC Q47_HH_HAS_PRIVATE_INS
preproc
  { Auto-set to Yes if any roster member reported private insurance (soft) }
  numeric anyPrivate = 0;
  numeric i = 1;
  do while i <= count(C_HOUSEHOLD_ROSTER)
    if Q49_PRIVATE_INS(i) = 1 then
      anyPrivate = 1;
    endif;
    i = i + 1;
  enddo;
  if anyPrivate = 1 then
    Q47_HH_HAS_PRIVATE_INS = 1;
    errmsg("Auto-set to Yes: a roster member has private insurance. Confirm.");
  endif;
"""

EXTRA_PROCS = """\
{ ---- Section G: branded/generic multi-branch (spec 2 Q76) ---- }
PROC Q76_BRAND_OR_GEN
postproc
  if Q76_BRAND_OR_GEN = 1    then  skip to Q78_WHY_BRANDED_O01; endif;  { Branded only -> why-branded (skip Q77) }
  if Q76_BRAND_OR_GEN in 3,4 then  skip to Q79_REG_SOURCE;      endif;  { Don't know / N/A -> exit Section G }
  { Generic (2) falls through to Q77 why-generic }

PROC Q78_WHY_BRANDED_O01
preproc
  if Q76_BRAND_OR_GEN <> 1 then   { only branded buyers answer why-branded }
    skip to Q79_REG_SOURCE;
  endif;

{ ---- Section H gate: skip entire Section H if NO roster member is PhilHealth-
  registered (Q45 = Yes anywhere in the roster). Spec 2 Section H note. ---- }
PROC Q79_REG_SOURCE
preproc
  numeric anyReg = 0;
  numeric i = 1;
  do while i <= count(C_HOUSEHOLD_ROSTER)
    if Q45_PHILHEALTH_REG(i) = 1 then
      anyReg = 1;
    endif;
    i = i + 1;
  enddo;
  if anyReg = 0 then
    skip to Q89_HAS_USUAL_FACILITY;   { no registered member -> skip Section H to Section I }
  endif;
"""

VALIDATION_PROCS = """\
{ ---- Validations: respondent demographics + household composition (spec 3.3) ---- }
PROC Q2_BIRTH_MONTH
postproc
  if Q2_BIRTH_MONTH < 1 or Q2_BIRTH_MONTH > 12 then
    errmsg("Birth month must be 1-12.");
    reenter;
  endif;

PROC Q2_BIRTH_YEAR
postproc
  if Q2_BIRTH_YEAR < 1900 or Q2_BIRTH_YEAR > currentYear then
    errmsg("Birth year must be between 1900 and %d.", currentYear);
    reenter;
  endif;

PROC Q2_1_AGE
postproc
  if Q2_1_AGE < 0 or Q2_1_AGE > 120 then
    errmsg("Age must be 0-120.");
    reenter;
  endif;
  if abs((currentYear - Q2_BIRTH_YEAR) - Q2_1_AGE) > 1 then
    errmsg("Age (%d) is inconsistent with birth year %d. Reenter.", Q2_1_AGE, Q2_BIRTH_YEAR);
    reenter;
  endif;

PROC Q19_HH_SIZE_TOTAL
postproc
  if Q19_HH_SIZE_TOTAL < 1 or Q19_HH_SIZE_TOTAL > 20 then
    errmsg("Household size must be 1-20.");
    reenter;
  endif;
  if Q19_HH_SIZE_TOTAL > 10 then
    errmsg("Household size %d is unusually large. Confirm.", Q19_HH_SIZE_TOTAL);
  endif;

PROC Q20_HH_CHILDREN
postproc
  if Q20_HH_CHILDREN > Q19_HH_SIZE_TOTAL then
    errmsg("Children (%d) cannot exceed household size (%d).", Q20_HH_CHILDREN, Q19_HH_SIZE_TOTAL);
    reenter;
  endif;

PROC Q21_HH_SENIORS
postproc
  if Q21_HH_SENIORS > Q19_HH_SIZE_TOTAL then
    errmsg("Seniors (%d) cannot exceed household size (%d).", Q21_HH_SENIORS, Q19_HH_SIZE_TOTAL);
    reenter;
  endif;
  if Q20_HH_CHILDREN + Q21_HH_SENIORS > Q19_HH_SIZE_TOTAL then
    errmsg("Children + seniors (%d) exceed household size (%d).",
           Q20_HH_CHILDREN + Q21_HH_SENIORS, Q19_HH_SIZE_TOTAL);
    reenter;
  endif;

{ ---- Roster per-member validations (spec 3.4) ---- }
PROC Q32_AGE
postproc
  if Q32_AGE < 0 or Q32_AGE > 120 then
    errmsg("Member age must be 0-120.");
    reenter;
  endif;

PROC Q39_CIVIL_STATUS
postproc
  if Q32_AGE < 15 and Q39_CIVIL_STATUS <> 1 then   { 1 = Single (verify code) }
    errmsg("Member is under 15 but civil status is not Single. Confirm.");
  endif;

{ ---- Income amount must fall within reported bracket (spec 3.2, HARD) ---- }
PROC Q18_INCOME_BRACKET
postproc
  numeric a = Q18_INCOME_AMOUNT;
  numeric ok = 0;
  if Q18_INCOME_BRACKET = 1 and a < 40000 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 2 and a >= 40000 and a <= 59999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 3 and a >= 60000 and a <= 99999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 4 and a >= 100000 and a <= 249999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 5 and a >= 250000 and a <= 499999 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 6 and a >= 500000 then ok = 1; endif;
  if Q18_INCOME_BRACKET = 7 then ok = 1; endif;   { 7 = Refuse to answer -> no amount check }
  if ok = 0 then
    errmsg("Income bracket does not match the reported amount (%d PHP). Reconcile.", a);
    reenter;
  endif;
"""

# Section D-F awareness + Section I primary-care + Section M bill-recall (spec 4.6-4.8)
SKIP_RULES = [
    # Section B — Respondent Profile
    ("Q7_IS_PWD",            "Q7_IS_PWD = 2",               "Q11_EDUCATION"),
    ("Q9_PWD_CARD",          "Q9_PWD_CARD = 2",             "Q11_EDUCATION"),
    ("Q14_IP_MEMBER",        "Q14_IP_MEMBER = 2",           "Q16_4PS"),
    # Section C roster — PhilHealth-registration detail
    ("Q45_PHILHEALTH_REG",   "Q45_PHILHEALTH_REG = 2",      "Q48_NAME_FIRST"),
    # Section G — Access to Medicines
    ("Q62_PURCHASE_FREQ",    "Q62_PURCHASE_FREQ = 5",       "Q69_GAMOT_HEARD"),   # Never -> skip Rx/where/travel
    ("Q69_GAMOT_HEARD",      "Q69_GAMOT_HEARD = 2",         "Q75_BRAND_GEN_KNOWS"),
    ("Q72_GAMOT_OBTAINED",   "Q72_GAMOT_OBTAINED = 2",      "Q75_BRAND_GEN_KNOWS"),
    ("Q75_BRAND_GEN_KNOWS",  "Q75_BRAND_GEN_KNOWS = 2",     "Q79_REG_SOURCE"),    # exit Section G
    # Section H — PhilHealth / Insurance
    ("Q81_REG_DIFFICULTY",   "Q81_REG_DIFFICULTY = 2",      "Q83_KNOWS_ASSIST"),
    ("Q83_KNOWS_ASSIST",     "Q83_KNOWS_ASSIST = 2",        "Q85_BENEFITS_O01"),
    ("Q86_PREMIUM_PAY",      "Q86_PREMIUM_PAY = 2",         "Q89_HAS_USUAL_FACILITY"),
    ("Q87_PREMIUM_DIFFICULT","Q87_PREMIUM_DIFFICULT = 2",   "Q89_HAS_USUAL_FACILITY"),
    # D-F awareness gates
    ("Q51_UHC_HEARD",        "Q51_UHC_HEARD in 2,3",        "Q54_YAKAP_HEARD"),
    ("Q54_YAKAP_HEARD",      "Q54_YAKAP_HEARD in 2,3",      "Q57_BUCAS_HEARD"),
    ("Q57_BUCAS_HEARD",      "Q57_BUCAS_HEARD in 2,3",      "Q62_PURCHASE_FREQ"),
    ("Q60_BUCAS_ACCESSED",   "Q60_BUCAS_ACCESSED = 2",      "Q62_PURCHASE_FREQ"),
    # Section I primary-care routing
    ("Q89_HAS_USUAL_FACILITY","Q89_HAS_USUAL_FACILITY = 2", "Q93_WHY_NOT_O01"),
    ("Q90_IS_USUAL_FOR_GENERAL","Q90_IS_USUAL_FOR_GENERAL = 1","Q94_TRANSPORT_O01"),
    ("Q97_KNOWS_BOOKING",    "Q97_KNOWS_BOOKING = 2",       "Q100_LEAVE_WORK_SCHOOL"),
    # Section M bill-recall chain (#170), gated on Q129 confinement
    ("Q129_HH_CONFINED",     "Q129_HH_CONFINED = 2",        "Q144_CEREALS_CONSUMED"),  # no confinement -> skip M -> Section N
    ("Q140_RECALL_BREAKDOWN","Q140_RECALL_BREAKDOWN = 2",   "Q142_RECALL_PAYMENT"),    # no breakdown -> skip Q141/Q141.1
    ("Q142_RECALL_PAYMENT",  "Q142_RECALL_PAYMENT = 2",     "Q144_CEREALS_CONSUMED"),  # no payment -> skip Q143 -> Section N
]

BILL_VALIDATION = """\
{ ---- Bill-recall cap (spec 4.8): no-receipt amount cannot exceed total bill ---- }
PROC Q141_1_NO_RECEIPT_AMT_PHP
postproc
  if Q141_1_NO_RECEIPT_AMT_PHP > Q139_FINAL_AMOUNT_PHP then
    errmsg("No-receipt amount (%d) exceeds total bill (%d). Verify.",
           Q141_1_NO_RECEIPT_AMT_PHP, Q139_FINAL_AMOUNT_PHP);
    reenter;
  endif;
"""

TODO_NOTE = """\
{ ============================================================================
  STILL OPEN (follow-up F4 pass):
    - Section N subtotals (Q157/Q177/Q182/Q185 _SUBTOTAL_TOTAL_PHP): auto-compute
      from each panel's _PURCHASED_PHP + _INKIND_PHP sums; make enumerator-readonly
      (spec finding #9 / §4.9). Needs the per-panel item membership.
    - Per-member sub-questionnaire loops conditional on age/relation (#166).
    - Q23 water-source multi-category branch (Q24/Q25/Q26) + non-UHC9 Other-specify.
    - Max-roster soft warning at unusual sizes (#168 second half).
    - Skip logic for the remaining sections + single/select-all Other-specify.
    - Verify ALL option codes + roster/occurrence flow (curocc/endocc/count) in
      CSEntry against the generated FMF — this is the riskiest part untested.
  ============================================================================ }
"""


def dcf_item_names():
    names = []
    dic = json.loads(DCF.read_text(encoding="utf-8"))
    for level in dic["levels"]:
        for rec in level.get("records", []):
            for it in rec.get("items", []):
                names.append(it["name"])
    return names


def dcf_items_map():
    """{name: item_dict} for every item in the dcf (for other-specify derivation)."""
    items = {}
    dic = json.loads(DCF.read_text(encoding="utf-8"))
    for level in dic["levels"]:
        for rec in level.get("records", []):
            for it in rec.get("items", []):
                items[it["name"]] = it
    return items


# Section N subtotal panels (spec finding #9 / §4.9, item ranges from §lines 549-552).
# Each subtotal auto-computes from its panel's _PURCHASED_PHP + _INKIND_PHP and is
# protected (enumerator cannot edit). Ranges are the AUTHORITATIVE spec ranges — NOT
# auto-derived by record order, because non-subtotaled items (Q158-Q172 restaurant /
# non-food) sit between the food and 12-month-health panels and must be excluded.
SUBTOTAL_PANELS = {
    "Q157_FOOD_SUBTOTAL_TOTAL_PHP":       (144, 156),
    "Q177_HEALTH_12M_SUBTOTAL_TOTAL_PHP": (173, 176),
    "Q182_HEALTH_6M_SUBTOTAL_TOTAL_PHP":  (178, 181),
    "Q185_HEALTH_1M_SUBTOTAL_TOTAL_PHP":  (183, 184),
}


def subtotal_procs(items):
    """Section N auto-computed subtotals (#9): subtotal = sum of its panel's
    _PURCHASED_PHP + _INKIND_PHP items (by spec Q-number range), then protect()."""
    import re as _re
    procs = {}
    qnum = _re.compile(r"^Q(\d+)_")
    for sub, (lo, hi) in SUBTOTAL_PANELS.items():
        if sub not in items:
            continue
        members = []
        for n in sorted(items):
            if not (n.endswith("_PURCHASED_PHP") or n.endswith("_INKIND_PHP")):
                continue
            m = qnum.match(n)
            if m and lo <= int(m.group(1)) <= hi:
                members.append(n)
        if not members:
            continue
        terms = "\n    + ".join(members)
        procs[sub] = (
            f"PROC {sub}\npreproc\n"
            f"  {sub} =\n    {terms};\n"
            f"  protect({sub});"
        )
    return procs


def expenditure_gate_procs(names):
    """#169 (spec 4.9): for each *_CONSUMED, if not consumed (No=2) zero + skip
    the matching *_PURCHASED_PHP and *_INKIND_PHP. dcf-driven so it scales to all
    Section N expenditure rows automatically."""
    procs = {}
    have = set(names)
    bases = [n[: -len("_CONSUMED")] for n in names if n.endswith("_CONSUMED")]
    for base in bases:
        for amt in (f"{base}_PURCHASED_PHP", f"{base}_INKIND_PHP"):
            if amt not in have:
                continue
            # zero + skip past this amount field. `skip to next` is illegal outside a
            # repeating group (CSEntry, verified 2026-06-08), so target the immediate
            # next dcf field (chains correctly: PURCHASED -> INKIND -> next item).
            idx = names.index(amt)
            target = names[idx + 1] if idx + 1 < len(names) else None
            skip = f"    skip to {target};\n" if target else ""
            procs[amt] = (
                f"PROC {amt}\n"
                f"preproc\n"
                f"  if {base}_CONSUMED = 2 then   {{ item not consumed -> no spend }}\n"
                f"    {amt} = 0;\n"
                f"{skip}"
                f"  endif;"
            )
    return procs


def uhc9_other_specify_procs(names):
    procs = {}
    for n in names:
        for suffix, code, lbl in (("_YES_OTHER_TXT", 4, "Yes, other reason"),
                                  ("_NO_OTHER_TXT", 7, "No, other reason")):
            if n.endswith(suffix):
                parent = n[: -len(suffix)]
                procs[n] = (
                    f"PROC {n}\npostproc\n"
                    f"  if {parent} = {code} and length(strip({n})) = 0 then\n"
                    f"    errmsg(\"'{lbl}' was selected for {parent}. Please specify.\");\n"
                    f"    reenter;\n  endif;"
                )
    return procs


def skip_proc(field, cond, target):
    return f"PROC {field}\npostproc\n  if {cond} then\n    skip to {target};\n  endif;"


def main():
    names = dcf_item_names()
    parts = [HEADER, "", CONTROL_PROCS, "", ROSTER_PROCS, "", BILL_VALIDATION, "",
             EXTRA_PROCS, "", VALIDATION_PROCS, ""]
    covered = {"Q34_RELATIONSHIP", "Q35_HAS_DISABILITY", "Q37_PWD_CARD",
               "Q49_PRIVATE_INS", "C_HOUSEHOLD_ROSTER_FORM", "Q47_HH_HAS_PRIVATE_INS",
               "Q141_1_NO_RECEIPT_AMT_PHP",
               "Q76_BRAND_OR_GEN", "Q78_WHY_BRANDED_O01", "Q79_REG_SOURCE",  # EXTRA_PROCS
               "Q2_BIRTH_MONTH", "Q2_BIRTH_YEAR", "Q2_1_AGE", "Q19_HH_SIZE_TOTAL",
               "Q20_HH_CHILDREN", "Q21_HH_SENIORS", "Q32_AGE", "Q39_CIVIL_STATUS",
               "Q18_INCOME_BRACKET"}  # VALIDATION_PROCS

    parts.append("{ ---- Skip logic: awareness / primary-care / bill-recall ---- }")
    for field, cond, target in SKIP_RULES:
        if field in covered:
            raise SystemExit(f"PROC collision: {field}")
        covered.add(field)
        parts.append(skip_proc(field, cond, target)); parts.append("")

    parts.append("{ ---- #169 Section N expenditure consumed-gate (dcf-driven) ---- }")
    for field, proc in sorted(expenditure_gate_procs(names).items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append("")

    parts.append("{ ---- 'Other (specify)' enforcement — UHC9 dual-other ---- }")
    for field, proc in sorted(uhc9_other_specify_procs(names).items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append("")

    # Auto-derived single-choice + select-all 'Other (specify)' enforcement (#148).
    os_procs, os_map, os_skipped = other_specify_procs(dcf_items_map())
    parts.append("{ ---- 'Other (specify)' enforcement — single-choice + select-all "
                 f"(auto-derived from dcf: {len(os_procs)} items) ---- }}")
    for field, proc in sorted(os_procs.items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append("")

    # Section N auto-computed subtotals (#9).
    st_procs = subtotal_procs(dcf_items_map())
    parts.append("{ ---- Section N subtotals — auto-compute + protect (#9, spec §4.9) ---- }")
    for field, proc in sorted(st_procs.items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append("")

    # Auto-derived select-all validation: >=1 option ticked.
    sa_procs, sa_bases = select_all_validation_procs(dcf_items_map())
    sa_emitted = 0
    parts.append("{ ---- Select-all validation — >=1 option ticked (auto-derived from dcf) ---- }")
    for field, proc in sorted(sa_procs.items()):
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append(""); sa_emitted += 1

    # Per-item numeric range checks + date-ordering cross-field (spec §3.1/§3.2/§3.6/§3.12).
    parts.append("{ ---- Range + cross-field validations (spec §3.1-§3.12) ---- }")
    rng_emitted = 0
    for field, lo, hi, soft in RANGE_CHECKS:
        if field in covered:
            continue
        covered.add(field)
        parts.append(range_check_proc(field, lo, hi, hard=True, soft_over=soft))
        parts.append(""); rng_emitted += 1
    for field, proc in CUSTOM_VALIDATION:
        if field in covered:
            continue
        covered.add(field); parts.append(proc); parts.append(""); rng_emitted += 1

    parts.append(TODO_NOTE)
    text = "\n".join(parts).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    procs = [l for l in text.splitlines() if l.startswith("PROC ")]
    assert len(procs) == len(set(procs)), "duplicate PROC names emitted"
    print(f"Wrote {OUT} ({len(text)} chars, {len(procs)} PROC blocks, no dup names).")
    print(f"  other-specify enforcement: {len(os_procs)} auto-derived "
          f"({sum(1 for _, d in os_map if d.startswith('single'))} single + "
          f"{sum(1 for _, d in os_map if d.startswith('select'))} select-all)")
    if os_skipped:
        print(f"  other-specify SKIPPED (manual review — no resolvable trigger): {', '.join(os_skipped)}")
    print(f"  select-all validation: {sa_emitted} groups got a '>=1 ticked' check (of {len(sa_bases)} detected)")
    print(f"  Section N subtotals: {len(st_procs)} auto-compute+protect procs")
    print(f"  range/cross-field: {rng_emitted} procs")
    print("  NEXT: create the F4 .ent in Designer (input dcf + generated.fmf), compile,")
    print("  then verify the ROSTER + expenditure flow in CSEntry (riskiest untested part).")


if __name__ == "__main__":
    main()
