<?php
/**
 * Who is signed in, and what can they reach.
 *
 * The gated surfaces (dashboard, map, data room) are static HTML regenerated by
 * cron, so they cannot know the viewer at build time. They fetch this instead to
 * fill the "signed in as … · Sign out" chip in the topbar.
 *
 * Tier is derived from the live `Require user` lines in the .htaccess gates
 * rather than a second list, so this can never disagree with what Apache
 * actually enforces.
 */
declare(strict_types=1);
ini_set('display_errors', '0');

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');

$user = $_SERVER['REMOTE_USER'] ?? $_SERVER['PHP_AUTH_USER'] ?? '';
if ($user === '') {
    http_response_code(401);
    echo json_encode(['user' => null, 'signed_in' => false]);
    exit;
}

/** Pull the usernames off every `Require user` line in a gate file. */
function gate_users(string $path): array {
    $raw = @file_get_contents($path);
    if (!is_string($raw) || $raw === '') { return []; }
    $out = [];
    foreach (preg_split('/\R/', $raw) as $line) {
        // NOTE: these lines are written with two leading spaces by the admin
        // console, so anchoring on ^Require would silently miss them.
        if (preg_match('/^\s*Require\s+user\s+(.+)$/i', $line, $m)) {
            foreach (preg_split('/\s+/', trim($m[1])) as $u) {
                if ($u !== '') { $out[] = $u; }
            }
        }
    }
    return $out;
}

$root = '/var/www/html/docs';
$monitoring = gate_users($root . '/.htaccess');
$dataRoom   = gate_users($root . '/data/.htaccess');
$adminC     = gate_users($root . '/admin/.htaccess');

$can = [
    'monitoring' => in_array($user, $monitoring, true),
    'data_room'  => in_array($user, $dataRoom, true),
    'admin'      => in_array($user, $adminC, true),
];

if ($can['admin'])          { $tier = 'admin'; }
elseif ($can['data_room'])  { $tier = 'staff'; }
elseif ($can['monitoring']) { $tier = 'field'; }
else                        { $tier = 'none'; }

echo json_encode([
    'signed_in' => true,
    'user'      => $user,
    'tier'      => $tier,
    'can'       => $can,
    'logout'    => '/docs/auth/logout',
], JSON_UNESCAPED_SLASHES);
