"""generate_apc.py — emit PatientSurvey.ent.apc.

F3 Patient Survey logic. Implements §4 of F3-Skip-Logic-and-Validations.md.

Commits in the F3 quartet build:
  - PROC GLOBAL — named constants + helper-function declarations.
  - PROC PATIENTSURVEY_LEVEL — level-scope placeholder (filled by commit 5
    with the patient-pick LEVEL.preproc + listing roster write-back logic).
  - PROC FIELD_CONTROL — case-start setup (template 4.14 from spec).
  - Section A — Q1 IS_PATIENT branching (template 4.4).
  - Section B — PWD gates (Q11/Q12/Q13/Q14), age/birth consistency
    (template 4.7), income amount-in-bracket consistency (template 4.8),
    HH composition consistency (validation H5/H6), Q33 decision-maker
    routing (template 4.5), Other-specify enforcement (template 4.6).
  - Section C — Q35 UHC_HEARD skip pattern (template 4.1).
  - Section D — PhilHealth registration + insurance skip chain (Q38-Q52).
  - Section E — Primary care utilization + Konsulta gates (Q53-Q82).
  - Section F — service-type routing to G/H/I (Q84 SERVICE_TYPE).
  - Section G — outpatient care chain (Q89/Q93/Q95/Q99/Q102/Q104).
  - Section H — inpatient care chain (Q108/Q110/Q113/Q114).
  - Section I — Financial Risk Protection (Q116/Q119/Q124/Q126/Q127).
  - Section J — inpatient-gated amenity questions (Q134/Q135).
  - Section K — Access to Medicines + brand/generic branching (Q152/Q155/Q159).
  - Section L — referrals + end-of-survey terminator (Q162/Q169/Q172/Q178).
  - Payment-matrix totals — Q97/Q115 reconciliation (validation H8/S3).

Reference: F3-Skip-Logic-and-Validations.md (this folder).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'PatientSurvey' logic file generated by CSPro }
{ F3 Patient Survey CAPI app — skip-logic + validations per                 }
{ F3-Skip-Logic-and-Validations.md.                                          }
{                                                                             }
{ Commit 3 of 6 (F3 quartet build): control + sections A-C.                  }
{ Commits 4-5 will append sections D-L + patient-pick preproc.               }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Income bracket boundaries (validation H4) ----------------------- }
{                                                                       }
{ Six brackets from Q18_INCOME_BRACKET value set in PatientSurvey.dcf.  }
{ Used by the Q18 postproc consistency check (template 4.8) and held   }
{ here as named constants so the bracket cutoffs are auditable without  }
{ scrolling into the PROC body.                                         }

numeric BRACKET_1_HI =    39999;   { Under 40,000          }
numeric BRACKET_2_LO =    40000;
numeric BRACKET_2_HI =    59999;   { 40,000 - 59,999       }
numeric BRACKET_3_LO =    60000;
numeric BRACKET_3_HI =    99999;   { 60,000 - 99,999       }
numeric BRACKET_4_LO =   100000;
numeric BRACKET_4_HI =   249999;   { 100,000 - 249,999     }
numeric BRACKET_5_LO =   250000;
numeric BRACKET_5_HI =   499999;   { 250,000 - 499,999     }
numeric BRACKET_6_LO =   500000;   { 500,000 and over      }

{ ---- AAPOR sentinel + visit-result codes ---------------------------- }
{                                                                       }
{ Mirrored from shared/cspro_helpers.py::AAPOR_DISPOSITION_OPTIONS and  }
{ ENUM_RESULT_OPTIONS. Held as APC constants so end-of-case dispositions }
{ are readable in the PROC code without consulting the DCF value sets.  }

numeric AAPOR_IN_PROGRESS         =   0;   { 000 - In Progress (initial)    }
numeric AAPOR_COMPLETE            = 110;   { 1.1 - Complete interview        }
numeric AAPOR_REFUSED             = 220;   { 2.20 - Refusal / break-off      }

numeric VISIT_RESULT_COMPLETED            = 1;
numeric VISIT_RESULT_WITHDRAW_CONSENT     = 6;


{ ---- Helper: end-of-section terminator ------------------------------ }

function CloseCaseAsComplete()
    { Set the closing AAPOR + visit-result codes when a respondent
      completes through the final terminus item (Q178 SAT_REFERRAL or
      the non-referral terminus at Q172+). Wired from PROC Q178 and the
      end-of-survey paths.

      Also: write F3_STATUS = 1 (completed) back to the listing roster
      row so the listing app's replacement-protocol engine sees the
      F-series slot consumed (no replacement needed). The roster write-
      back uses g_picked_* state captured by PickPatient() at case-open. }
    AAPOR_DISPOSITION        = AAPOR_COMPLETE;
    ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_COMPLETED;
    DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
    StampRosterStatus(F3_STATUS_COMPLETED);
end;


{ ===================================================================== }
{  Patient-pick — globals + helper functions                             }
{ ===================================================================== }

PROC GLOBAL

{ Cap on visible eligible-patient choices per pick screen. CSPro accept()
  is variadic at compile time, not runtime; we hard-build 20 slots and
  fall back to "more rows exist — refine by listing-session" guidance if
  the operator sees the cap hit. With BACKUP_TARGET ~= 0.5 * FACILITY_TARGET
  per session (see 110_F3_listing logic) plus rare same-day backfill, 20
  is generous for a single facility-day session. }
numeric PICK_MAX_CHOICES = 20;

{ State held across the patient-pick + write-back PROCs. Populated by
  PickPatient(), consumed by StampRosterStatus() and the F3 case-save
  finalizer in PROC PATIENTSURVEY_LEVEL.postproc. }
numeric g_picked_roster_seq        =  0;   { ROSTER_SEQ on chosen roster row }
numeric g_picked_listing_date      =  0;   { LISTING_SESSION_DATE of chosen  }
numeric g_picked_listing_seq       =  0;   { LISTING_SESSION_SEQ of chosen   }
string  g_picked_patient_fullname  = "";   { for FIELD_CONTROL stamping     }

{ Status codes — mirror F3_STATUS value set in 110_F3_listing DCF. }
numeric F3_STATUS_PENDING     = 0;
numeric F3_STATUS_COMPLETED   = 1;
numeric F3_STATUS_IN_PROGRESS = 2;
numeric F3_STATUS_REFUSED     = 3;


function StampRosterStatus(numeric newStatus)
    { Re-load the chosen PATIENTLISTING_DICT case (by listing-session ID
      block) into edit mode, locate the matching REC_PATIENT_ROSTER
      occurrence via g_picked_roster_seq, update F3_STATUS, and savecase.

      Called from:
        - PickPatient()                      with F3_STATUS_IN_PROGRESS
        - PROC FIELD_CONTROL postproc        with F3_STATUS_COMPLETED (save)
        - PROC CONSENT_GIVEN postproc        with F3_STATUS_REFUSED   (refuse)

      Failure mode: if loadcase / savecase return false, errmsg the
      operator. The F3 case itself can still be saved — the roster
      flag will be reconciled at next listing-app sync by the desk
      reviewer. }

    if not loadcase(PATIENTLISTING_DICT,
                    REGION_CODE, PROVINCE_HUC_CODE,
                    CITY_MUNICIPALITY_CODE, FACILITY_NO,
                    g_picked_listing_date, g_picked_listing_seq) then
        errmsg("Could not re-open listing session for status write-back. "
               "Roster F3_STATUS will be reconciled at next sync. "
               "Continuing with F3 case.");
        StampRosterStatus = 0;
        exit;
    endif;

    { Locate the matching roster occurrence. ROSTER_SEQ is 1-based and
      contiguous within a session. }
    numeric occIdx = 0;
    numeric i;
    for i = 1 to totocc(REC_PATIENT_ROSTER)
        if PATIENTLISTING_DICT.REC_PATIENT_ROSTER(i).ROSTER_SEQ
                                                = g_picked_roster_seq then
            occIdx = i;
        endif;
    enddo;

    if occIdx = 0 then
        errmsg("Picked ROSTER_SEQ %v not found in re-loaded listing case. "
               "F3 case will still save; reconcile manually.",
               g_picked_roster_seq);
        StampRosterStatus = 0;
        exit;
    endif;

    PATIENTLISTING_DICT.REC_PATIENT_ROSTER(occIdx).F3_STATUS = newStatus;

    if newStatus = F3_STATUS_IN_PROGRESS then
        { Stamp the F3 CASE_SEQ allocation onto the roster row so the
          listing-app's replacement-protocol engine sees the slot
          consumed. CASE_SEQ is the 5th item of F3's ID block. }
        PATIENTLISTING_DICT.REC_PATIENT_ROSTER(occIdx).ASSIGNED_F3_CASE_SEQ
                                                              = CASE_SEQ;
    endif;

    if not savecase(PATIENTLISTING_DICT) then
        errmsg("Could not save listing-session write-back (status=%v). "
               "Roster F3_STATUS will be reconciled at next sync.",
               newStatus);
        StampRosterStatus = 0;
        exit;
    endif;

    StampRosterStatus = 1;
end;


function PickPatient()
    { Build the eligible-patient pick list from PATIENTLISTING_DICT and
      prompt the operator. Eligibility filter:
        - LISTING_TAG = 1 (F3-exit same-day at facility)
        - F3_STATUS   = 0 (pending — not yet attempted)

      Only roster rows from listing sessions for the current facility
      (matched on the 9-digit facility prefix REGION + PROVINCE_HUC +
      CITY_MUNICIPALITY + FACILITY_NO) are considered.

      The operator sees a maximum of PICK_MAX_CHOICES eligible patients;
      additional rows are hidden with a "more rows hidden — refine by
      listing session" footer message.

      On selection:
        - g_picked_roster_seq      = chosen ROSTER_SEQ
        - g_picked_listing_date    = LISTING_SESSION_DATE of chosen case
        - g_picked_listing_seq     = LISTING_SESSION_SEQ of chosen case
        - g_picked_patient_fullname = "First Last" of chosen patient

      Returns 1 on success, 0 on operator-cancel or no-eligible-rows. }

    { Reset state. }
    g_picked_roster_seq        = 0;
    g_picked_listing_date      = 0;
    g_picked_listing_seq       = 0;
    g_picked_patient_fullname  = "";

    { Build choice strings via forcase across all matching listing cases. }
    string choice01 = ""; string choice02 = ""; string choice03 = "";
    string choice04 = ""; string choice05 = ""; string choice06 = "";
    string choice07 = ""; string choice08 = ""; string choice09 = "";
    string choice10 = ""; string choice11 = ""; string choice12 = "";
    string choice13 = ""; string choice14 = ""; string choice15 = "";
    string choice16 = ""; string choice17 = ""; string choice18 = "";
    string choice19 = ""; string choice20 = "";

    { Parallel arrays of the same length tracking the roster identity
      behind each visible choice. CSPro doesn't have native arrays, so
      we use numbered scalars. }
    numeric rs01 = 0; numeric rs02 = 0; numeric rs03 = 0; numeric rs04 = 0;
    numeric rs05 = 0; numeric rs06 = 0; numeric rs07 = 0; numeric rs08 = 0;
    numeric rs09 = 0; numeric rs10 = 0; numeric rs11 = 0; numeric rs12 = 0;
    numeric rs13 = 0; numeric rs14 = 0; numeric rs15 = 0; numeric rs16 = 0;
    numeric rs17 = 0; numeric rs18 = 0; numeric rs19 = 0; numeric rs20 = 0;

    numeric ld01 = 0; numeric ld02 = 0; numeric ld03 = 0; numeric ld04 = 0;
    numeric ld05 = 0; numeric ld06 = 0; numeric ld07 = 0; numeric ld08 = 0;
    numeric ld09 = 0; numeric ld10 = 0; numeric ld11 = 0; numeric ld12 = 0;
    numeric ld13 = 0; numeric ld14 = 0; numeric ld15 = 0; numeric ld16 = 0;
    numeric ld17 = 0; numeric ld18 = 0; numeric ld19 = 0; numeric ld20 = 0;

    numeric ls01 = 0; numeric ls02 = 0; numeric ls03 = 0; numeric ls04 = 0;
    numeric ls05 = 0; numeric ls06 = 0; numeric ls07 = 0; numeric ls08 = 0;
    numeric ls09 = 0; numeric ls10 = 0; numeric ls11 = 0; numeric ls12 = 0;
    numeric ls13 = 0; numeric ls14 = 0; numeric ls15 = 0; numeric ls16 = 0;
    numeric ls17 = 0; numeric ls18 = 0; numeric ls19 = 0; numeric ls20 = 0;

    numeric choice_count = 0;
    numeric rows_total   = 0;

    { Read the current facility's 9-digit prefix from loadsetting() —
      stamped by 101_login at sign-in. }
    numeric login_region  = tonumber(loadsetting("region_code"));
    numeric login_prov    = tonumber(loadsetting("province_huc_code"));
    numeric login_city    = tonumber(loadsetting("city_municipality_code"));
    numeric login_fac     = tonumber(loadsetting("facility_no"));

    forcase PATIENTLISTING_DICT
        where REGION_CODE            = login_region
        and   PROVINCE_HUC_CODE      = login_prov
        and   CITY_MUNICIPALITY_CODE = login_city
        and   FACILITY_NO            = login_fac
    do
        { For each listing session for the current facility, walk the
          roster occurrences. }
        numeric j;
        for j = 1 to totocc(REC_PATIENT_ROSTER)
            if PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).LISTING_TAG = 1
               and PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).F3_STATUS
                                                  = F3_STATUS_PENDING then
                rows_total = rows_total + 1;

                if choice_count < PICK_MAX_CHOICES then
                    choice_count = choice_count + 1;
                    string fullname =
                        strip(
                            PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).P_FIRST_NAME)
                        + " " +
                        strip(
                            PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).P_LAST_NAME);
                    string label =
                        maketext("#%03d  %s  (session %d-%03d)",
                            PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ,
                            fullname,
                            LISTING_SESSION_DATE,
                            LISTING_SESSION_SEQ);

                    if choice_count = 1  then choice01 = label;
                       rs01 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld01 = LISTING_SESSION_DATE; ls01 = LISTING_SESSION_SEQ;
                    elseif choice_count = 2  then choice02 = label;
                       rs02 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld02 = LISTING_SESSION_DATE; ls02 = LISTING_SESSION_SEQ;
                    elseif choice_count = 3  then choice03 = label;
                       rs03 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld03 = LISTING_SESSION_DATE; ls03 = LISTING_SESSION_SEQ;
                    elseif choice_count = 4  then choice04 = label;
                       rs04 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld04 = LISTING_SESSION_DATE; ls04 = LISTING_SESSION_SEQ;
                    elseif choice_count = 5  then choice05 = label;
                       rs05 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld05 = LISTING_SESSION_DATE; ls05 = LISTING_SESSION_SEQ;
                    elseif choice_count = 6  then choice06 = label;
                       rs06 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld06 = LISTING_SESSION_DATE; ls06 = LISTING_SESSION_SEQ;
                    elseif choice_count = 7  then choice07 = label;
                       rs07 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld07 = LISTING_SESSION_DATE; ls07 = LISTING_SESSION_SEQ;
                    elseif choice_count = 8  then choice08 = label;
                       rs08 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld08 = LISTING_SESSION_DATE; ls08 = LISTING_SESSION_SEQ;
                    elseif choice_count = 9  then choice09 = label;
                       rs09 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld09 = LISTING_SESSION_DATE; ls09 = LISTING_SESSION_SEQ;
                    elseif choice_count = 10 then choice10 = label;
                       rs10 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld10 = LISTING_SESSION_DATE; ls10 = LISTING_SESSION_SEQ;
                    elseif choice_count = 11 then choice11 = label;
                       rs11 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld11 = LISTING_SESSION_DATE; ls11 = LISTING_SESSION_SEQ;
                    elseif choice_count = 12 then choice12 = label;
                       rs12 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld12 = LISTING_SESSION_DATE; ls12 = LISTING_SESSION_SEQ;
                    elseif choice_count = 13 then choice13 = label;
                       rs13 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld13 = LISTING_SESSION_DATE; ls13 = LISTING_SESSION_SEQ;
                    elseif choice_count = 14 then choice14 = label;
                       rs14 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld14 = LISTING_SESSION_DATE; ls14 = LISTING_SESSION_SEQ;
                    elseif choice_count = 15 then choice15 = label;
                       rs15 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld15 = LISTING_SESSION_DATE; ls15 = LISTING_SESSION_SEQ;
                    elseif choice_count = 16 then choice16 = label;
                       rs16 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld16 = LISTING_SESSION_DATE; ls16 = LISTING_SESSION_SEQ;
                    elseif choice_count = 17 then choice17 = label;
                       rs17 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld17 = LISTING_SESSION_DATE; ls17 = LISTING_SESSION_SEQ;
                    elseif choice_count = 18 then choice18 = label;
                       rs18 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld18 = LISTING_SESSION_DATE; ls18 = LISTING_SESSION_SEQ;
                    elseif choice_count = 19 then choice19 = label;
                       rs19 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld19 = LISTING_SESSION_DATE; ls19 = LISTING_SESSION_SEQ;
                    elseif choice_count = 20 then choice20 = label;
                       rs20 = PATIENTLISTING_DICT.REC_PATIENT_ROSTER(j).ROSTER_SEQ;
                       ld20 = LISTING_SESSION_DATE; ls20 = LISTING_SESSION_SEQ;
                    endif;
                endif;
            endif;
        enddo;
    enddo;

    if choice_count = 0 then
        errmsg("No eligible patients pending F3 at this facility. "
               "Either no listing session has been run today, or all "
               "F3-tagged rows are already in-progress / completed. "
               "Confirm with the supervisor before creating an F3 case.");
        PickPatient = 0;
        exit;
    endif;

    if rows_total > PICK_MAX_CHOICES then
        errmsg("%v eligible rows found — showing first %v. Refine by "
               "running F3 in a focused listing-session window if the "
               "patient you want is not in the list.",
               rows_total, PICK_MAX_CHOICES);
        { soft — operator continues into the pick list }
    endif;

    numeric pick = accept(
        "Select the patient for this F3 interview",
        choice01, choice02, choice03, choice04, choice05,
        choice06, choice07, choice08, choice09, choice10,
        choice11, choice12, choice13, choice14, choice15,
        choice16, choice17, choice18, choice19, choice20);

    if pick = 0 then
        { Operator cancelled. F3 case cannot proceed without a roster row. }
        errmsg("F3 case creation cancelled — patient not picked.");
        PickPatient = 0;
        exit;
    endif;

    if      pick =  1 then g_picked_roster_seq = rs01;
                            g_picked_listing_date = ld01;
                            g_picked_listing_seq  = ls01;
    elseif  pick =  2 then g_picked_roster_seq = rs02;
                            g_picked_listing_date = ld02;
                            g_picked_listing_seq  = ls02;
    elseif  pick =  3 then g_picked_roster_seq = rs03;
                            g_picked_listing_date = ld03;
                            g_picked_listing_seq  = ls03;
    elseif  pick =  4 then g_picked_roster_seq = rs04;
                            g_picked_listing_date = ld04;
                            g_picked_listing_seq  = ls04;
    elseif  pick =  5 then g_picked_roster_seq = rs05;
                            g_picked_listing_date = ld05;
                            g_picked_listing_seq  = ls05;
    elseif  pick =  6 then g_picked_roster_seq = rs06;
                            g_picked_listing_date = ld06;
                            g_picked_listing_seq  = ls06;
    elseif  pick =  7 then g_picked_roster_seq = rs07;
                            g_picked_listing_date = ld07;
                            g_picked_listing_seq  = ls07;
    elseif  pick =  8 then g_picked_roster_seq = rs08;
                            g_picked_listing_date = ld08;
                            g_picked_listing_seq  = ls08;
    elseif  pick =  9 then g_picked_roster_seq = rs09;
                            g_picked_listing_date = ld09;
                            g_picked_listing_seq  = ls09;
    elseif  pick = 10 then g_picked_roster_seq = rs10;
                            g_picked_listing_date = ld10;
                            g_picked_listing_seq  = ls10;
    elseif  pick = 11 then g_picked_roster_seq = rs11;
                            g_picked_listing_date = ld11;
                            g_picked_listing_seq  = ls11;
    elseif  pick = 12 then g_picked_roster_seq = rs12;
                            g_picked_listing_date = ld12;
                            g_picked_listing_seq  = ls12;
    elseif  pick = 13 then g_picked_roster_seq = rs13;
                            g_picked_listing_date = ld13;
                            g_picked_listing_seq  = ls13;
    elseif  pick = 14 then g_picked_roster_seq = rs14;
                            g_picked_listing_date = ld14;
                            g_picked_listing_seq  = ls14;
    elseif  pick = 15 then g_picked_roster_seq = rs15;
                            g_picked_listing_date = ld15;
                            g_picked_listing_seq  = ls15;
    elseif  pick = 16 then g_picked_roster_seq = rs16;
                            g_picked_listing_date = ld16;
                            g_picked_listing_seq  = ls16;
    elseif  pick = 17 then g_picked_roster_seq = rs17;
                            g_picked_listing_date = ld17;
                            g_picked_listing_seq  = ls17;
    elseif  pick = 18 then g_picked_roster_seq = rs18;
                            g_picked_listing_date = ld18;
                            g_picked_listing_seq  = ls18;
    elseif  pick = 19 then g_picked_roster_seq = rs19;
                            g_picked_listing_date = ld19;
                            g_picked_listing_seq  = ls19;
    elseif  pick = 20 then g_picked_roster_seq = rs20;
                            g_picked_listing_date = ld20;
                            g_picked_listing_seq  = ls20;
    endif;

    { Allocate F3 CASE_SEQ from the enumerator's f3_seq_lo/f3_seq_hi
      range (loaded into loadsetting() by 101_login from user_roster.xlsx).
      Strategy: read both endpoints, use lo + roster_seq - 1 as the
      base allocation, falling back to a free-slot scan if the base is
      already used. For Phase 1 the base allocation is sufficient since
      F3 case-IDs are not reused across sessions. }
    numeric f3_lo = tonumber(loadsetting("f3_seq_lo"));
    CASE_SEQ = f3_lo + g_picked_roster_seq - 1;

    { Stamp the F3 case-ID block (REGION_CODE etc.) from the login
      settings, matching the facility-prefix the listing roster used. }
    REGION_CODE            = login_region;
    PROVINCE_HUC_CODE      = login_prov;
    CITY_MUNICIPALITY_CODE = login_city;
    FACILITY_NO            = login_fac;

    { PATIENT_LISTING_NO copied from the chosen roster row into the F3
      FIELD_CONTROL header (per the FIELD_CONTROL extra item in
      generate_dcf.py::build_f3_field_control). }
    PATIENT_LISTING_NO = g_picked_roster_seq;

    { Write F3_STATUS = 2 (in-progress) + ASSIGNED_F3_CASE_SEQ back
      to the listing roster. }
    StampRosterStatus(F3_STATUS_IN_PROGRESS);

    PickPatient = 1;
end;


PROC PATIENTSURVEY_LEVEL
preproc
    { On every new F3 case, run the patient-pick screen BEFORE any
      form opens. The pick stamps:
        - CASE_SEQ                    (allocated from f3_seq_lo..hi)
        - REGION_CODE..FACILITY_NO    (from login settings)
        - PATIENT_LISTING_NO          (from chosen roster row)
        - g_picked_*                  (state for end-of-case write-back)

      If the operator cancels or no eligible rows exist, PickPatient()
      errmsgs and returns 0; the case still opens, but the operator must
      cancel via the system Stop-case button. We cannot endcase() from
      LEVEL.preproc because the case has not yet been initialized. }

    if not PickPatient() then
        { Stay in the dictionary — operator will see the error and
          cancel the case via the Stop-case shortcut. }
    endif;


{ ===================================================================== }
{  FIELD_CONTROL — case-start setup (template 4.14)                     }
{ ===================================================================== }

PROC FIELD_CONTROL
preproc
    SURVEY_CODE        = "F3";
    DATE_STARTED       = SYSDATE("YYYYMMDD");
    TIME_STARTED       = SYSTIME("HHMMSS");
    AAPOR_DISPOSITION  = AAPOR_IN_PROGRESS;

    { INTERVIEWER_ID and PATIENT_LISTING_NO are stamped by the
      patient-pick preproc (commit 5) before the operator sees any
      form. DATE_FIRST_VISITED defaults to today if the operator does
      not override on the first visit. }
    if DATE_FIRST_VISITED = 0 then
        DATE_FIRST_VISITED = SYSDATE("YYYYMMDD");
    endif;


PROC CONSENT_GIVEN
postproc
    { Hard terminator: if the patient withdraws consent at the read-out,
      mark the case withdrawn and end the interview. The operator is
      expected to save the partial case so the disposition is preserved
      for paradata. Per F3-Skip-Logic-and-Validations.md §2 Section A
      ("Terminate interview" rule). The roster row is flagged
      F3_STATUS = 3 (refused-at-F3) so the listing-app's replacement
      engine pulls a backup slot from the 700-899 range on the next
      listing-event. }
    if CONSENT_GIVEN = 2 then   { 2 = No }
        AAPOR_DISPOSITION        = AAPOR_REFUSED;
        ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_WITHDRAW_CONSENT;
        DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
        StampRosterStatus(F3_STATUS_REFUSED);
        endcase;
    endif;


{ ===================================================================== }
{  Section A — Introduction and Informed Consent (Q1-Q3)                }
{ ===================================================================== }

PROC Q1_IS_PATIENT
postproc
    { Template 4.4 — if respondent IS the patient, skip Q2 (relationship)
      and Q3 (same-house), proceed direct to Q4. Q2/Q3 only asked when
      the respondent is a proxy informant. }
    if Q1_IS_PATIENT = 1 then
        skip to Q4_NAME;
    endif;


PROC Q2_RELATIONSHIP_OTHER_TXT
preproc
    if Q2_RELATIONSHIP <> 19 then   { 19 = "Other (specify)" }
        skip to Q3_SAME_HOUSE;
    endif;
postproc
    { Other-specify enforcement (template 4.6 / validation S5). }
    if Q2_RELATIONSHIP = 19 and strlen(strip(Q2_RELATIONSHIP_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' relationship to the patient.");
        reenter;
    endif;


{ ===================================================================== }
{  Section B — Patient Profile (Q4-Q34)                                 }
{ ===================================================================== }

PROC Q6_AGE
postproc
    { Validation H2/H3 — age range + age-vs-birth-year consistency
      (template 4.7). Allow off-by-one on calendar-rollover edge case. }
    if Q6_AGE < 0 or Q6_AGE > 120 then
        errmsg("Age must be between 0 and 120. Please re-check.");
        reenter;
    endif;

    numeric calc_age = tonumber(SYSDATE("YYYY")) - Q5_BIRTH_YEAR;
    if abs(calc_age - Q6_AGE) > 1 then
        errmsg("Age (%v) inconsistent with birth year %v (computed %v). "
               "Please re-check.",
               Q6_AGE, Q5_BIRTH_YEAR, calc_age);
        reenter;
    endif;

    { Soft S1 — patient <18 (relative reporting allowed via Q1=No,
      so this warns but does not block save). }
    if Q6_AGE < 18 then
        if Q1_IS_PATIENT = 1 then
            errmsg("Patient age <18 and respondent IS the patient. "
                   "Please confirm relative-reporting allowed; F3 "
                   "should not enroll minors as self-respondents.");
            { soft — operator confirms by accepting; no reenter }
        endif;
    endif;


PROC Q11_PWD
postproc
    { PWD-gate: if not PWD, skip the PWD-specific chain Q12-Q14. }
    if Q11_PWD = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q12_PWD_SPECIFY
postproc
    { PWD-specify-gate: if PWD but does not want to specify, skip Q13/Q14. }
    if Q12_PWD_SPECIFY = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q13_PWD_CARD
postproc
    { Card-gate (template 4.x / GATE rule §3): Q14 only when Q13 = 1
      (card was presented and verified). Otherwise skip to Q15. }
    if Q13_PWD_CARD <> 1 then
        skip to Q15_EDUCATION;
    endif;


PROC Q14_DISABILITY_OTHER_TXT
preproc
    if Q14_DISABILITY_TYPE <> 8 then   { 8 = "Other disability (specify)" }
        skip to Q15_EDUCATION;
    endif;
postproc
    { Soft S4 — warn if Other selected but text blank. }
    if Q14_DISABILITY_TYPE = 8 and strlen(strip(Q14_DISABILITY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' disability type.");
        { soft — does not reenter }
    endif;


PROC Q18_INCOME_BRACKET
postproc
    { Template 4.8 — amount-in-bracket consistency (validation H4). }
    numeric lo;
    numeric hi;

    if      Q18_INCOME_BRACKET = 1 then lo = 0;              hi = BRACKET_1_HI;
    elseif  Q18_INCOME_BRACKET = 2 then lo = BRACKET_2_LO;   hi = BRACKET_2_HI;
    elseif  Q18_INCOME_BRACKET = 3 then lo = BRACKET_3_LO;   hi = BRACKET_3_HI;
    elseif  Q18_INCOME_BRACKET = 4 then lo = BRACKET_4_LO;   hi = BRACKET_4_HI;
    elseif  Q18_INCOME_BRACKET = 5 then lo = BRACKET_5_LO;   hi = BRACKET_5_HI;
    elseif  Q18_INCOME_BRACKET = 6 then lo = BRACKET_6_LO;   hi = 9999999;
    endif;

    if not (Q18_INCOME_AMOUNT >= lo and Q18_INCOME_AMOUNT <= hi) then
        errmsg("Income amount %v is outside bracket %v (%v - %v). "
               "Please re-check.",
               Q18_INCOME_AMOUNT, Q18_INCOME_BRACKET, lo, hi);
        reenter;
    endif;


PROC Q19_HH_SIZE
postproc
    { Validation H6 — HH size range. }
    if Q19_HH_SIZE < 1 or Q19_HH_SIZE > 30 then
        errmsg("Household size must be between 1 and 30. Please re-check.");
        reenter;
    endif;


PROC Q21_HH_SENIORS
postproc
    { Validation H5/H6 — HH composition coverage: total HH size must
      accommodate the children + senior sub-counts. Q20+Q21 = subset of Q19. }
    if Q19_HH_SIZE < Q20_HH_CHILDREN + Q21_HH_SENIORS then
        errmsg("HH size %v cannot be smaller than children %v + seniors %v.",
               Q19_HH_SIZE, Q20_HH_CHILDREN, Q21_HH_SENIORS);
        reenter;
    endif;
    if Q20_HH_CHILDREN > Q19_HH_SIZE or Q21_HH_SENIORS > Q19_HH_SIZE then
        errmsg("Children or seniors count exceeds total HH size %v. "
               "Please re-check.", Q19_HH_SIZE);
        reenter;
    endif;


PROC Q23_WATER_OTHER_TXT
preproc
    { Template 4.6 — Other-specify gate + enforcement. }
    if Q23_WATER <> 4 then   { 4 = "Other (specify)" }
        skip to Q24_FAUCET_OWN;
    endif;
postproc
    if Q23_WATER = 4 and strlen(strip(Q23_WATER_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' water source.");
        reenter;
    endif;


PROC Q30_IP
postproc
    { Indigenous Peoples gate — if not IP, skip Q31 (IP group). Q32 in
      the DCF is the 4Ps beneficiary flag (Q32_4PS), per the Apr 20 PDF
      item ordering. }
    if Q30_IP = 2 then   { 2 = No }
        skip to Q32_4PS;
    endif;


PROC Q33_DECISION_MAKER
postproc
    { Template 4.5 — if respondent IS the decision-maker (1), or the
      companion is (3), skip Q34 (DM identification) and go to Q35. }
    if Q33_DECISION_MAKER in 1, 3 then
        skip to Q35_UHC_HEARD;
    endif;


{ ===================================================================== }
{  Section C — UHC Awareness (Q35-Q37)                                  }
{ ===================================================================== }

PROC Q35_UHC_HEARD
postproc
    { Template 4.1 — if has not heard of UHC, skip the awareness-detail
      questions Q36/Q37 and jump to Section D. }
    if Q35_UHC_HEARD = 2 then   { 2 = No }
        skip to Q38_PHILHEALTH_REG;
    endif;


{ ===================================================================== }
{  Section D — PhilHealth Registration + Insurance (Q38-Q52)            }
{ ===================================================================== }

PROC Q38_PHILHEALTH_REG
postproc
    { Template 4.1 — non-registered / DK skips the registration-detail
      questions Q39-Q42 and jumps direct to Q43 (knows-of-assistance). }
    if Q38_PHILHEALTH_REG in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q43_KNOWS_ASSIST;
    endif;


PROC Q41_REG_DIFFICULTY
postproc
    if Q41_REG_DIFFICULTY = 2 then   { 2 = No }
        skip to Q43_KNOWS_ASSIST;
    endif;


PROC Q43_KNOWS_ASSIST
postproc
    { Non-member path: per PDF, Q43=No skips Q44 + Q45-Q50 (all
      asked-only-for-members) and jumps to Q51 (other insurance). }
    if Q43_KNOWS_ASSIST = 2 then   { 2 = No }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q45_CATEGORY
preproc
    { Member-gate: Q45-Q50 asked only when Q38=1 (registered).
      Per PDF "ASKED ONLY FOR PHILHEALTH MEMBERS. SKIP TO 51 FOR NON-MEMBERS". }
    if Q38_PHILHEALTH_REG <> 1 then
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q45_CATEGORY_OTHER_TXT
preproc
    { Other-specify gate (template 4.6). 96 = Other (per PSA convention).
      Q46_BENEFITS is a select_all; route to its first decomposed slot. }
    if Q45_CATEGORY <> 96 then
        skip to Q46_BENEFITS_O01;
    endif;
postproc
    if Q45_CATEGORY = 96 and strlen(strip(Q45_CATEGORY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' PhilHealth category.");
        reenter;
    endif;


PROC Q48_PREMIUM_PAY
postproc
    { Non-payer skips premium-difficulty / amount-difficulty. }
    if Q48_PREMIUM_PAY = 3 then   { 3 = No / does not pay premium }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q49_PREMIUM_DIFFICULT
postproc
    if Q49_PREMIUM_DIFFICULT = 2 then   { 2 = No }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q51_OTHER_INSURANCE
postproc
    { Skip Q52 detail when no other insurance. }
    if Q51_OTHER_INSURANCE = 2 then   { 2 = No }
        skip to Q53_HAS_PCP;
    endif;


{ ===================================================================== }
{  Section E — Primary Care Utilization (Q53-Q82)                       }
{ ===================================================================== }

PROC Q53_HAS_PCP
postproc
    { No-PCP skips the entire PCP-attribute chain Q54-Q62 and jumps to
      Q63 (has-usual-facility). }
    if Q53_HAS_PCP = 2 then   { 2 = No }
        skip to Q63_HAS_USUAL_FACILITY;
    endif;


PROC Q60_SCHED_TELECON_OK
preproc
    { Template 4.2 — Q60 telecon-detail gated by Q59 contains "Teleconsultation".
      The select-all is decomposed into Q59_SCHED_COMM_O01..O0n by the
      DCF generator; option 2 (Teleconsultation) corresponds to
      Q59_SCHED_COMM_O02. Skip Q60 if telecon not chosen; route to the
      first slot of Q61 select_all. }
    if Q59_SCHED_COMM_O02 <> 1 then
        skip to Q61_CONSULT_COMM_O01;
    endif;


PROC Q62_CONSULT_TELECON_OK
preproc
    { Template 4.2 — Q62 telecon-detail gated by Q61 contains "Teleconsultation". }
    if Q61_CONSULT_COMM_O02 <> 1 then
        skip to Q63_HAS_USUAL_FACILITY;
    endif;


PROC Q63_HAS_USUAL_FACILITY
postproc
    { No-usual-facility — Q64 facility name unused; after Q65 (why-no-usual
      select_all) skip Q66-Q70 (same-as-usual chain) and jump to Q71.
      Implementation: defer the routing to Q66.preproc below — when Q66
      opens, if Q63=No we skip the whole same-as-usual chain. }
    { No skip emitted on Q63 — Q65 is still asked when Q63=No. }


PROC Q66_SAME_AS_USUAL
preproc
    { When Q63=No (no usual facility), the entire same-as-usual chain
      (Q66-Q70) is skipped. Route to Q71 (nearest-facility type — the
      first item of the "nearest facility" block asked of everyone). }
    if Q63_HAS_USUAL_FACILITY = 2 then
        skip to Q71_NEAREST_TYPE;
    endif;
postproc
    { If usual = today's facility, skip Q67 (which other facility) and
      proceed to Q68 (usual-facility type). }
    if Q66_SAME_AS_USUAL = 1 then   { 1 = Yes }
        skip to Q68_USUAL_FAC_TYPE;
    endif;


PROC Q74_KON_HEARD
postproc
    { Konsulta awareness chain: never-heard skips Q75-Q82 entirely.
      Q83 is the first item of Section F (Q83_VISIT_REASON). }
    if Q74_KON_HEARD = 2 then   { 2 = No }
        skip to Q83_VISIT_REASON;
    endif;


PROC Q77_KON_REGISTERED
postproc
    { Konsulta registration chain:
        - "Not registered" (2)         -> skip to Q82 (why-not-registered).
        - "Never heard" (3) or DK (4)  -> skip to Q83 (Section F start).
      Q82_KON_WHY_NOT_REG is a select_all; CSPro routes to its first
      decomposed item _O01. }
    if Q77_KON_REGISTERED = 2 then
        skip to Q82_KON_WHY_NOT_REG_O01;
    endif;
    if Q77_KON_REGISTERED in 3, 4 then
        skip to Q83_VISIT_REASON;
    endif;


{ ===================================================================== }
{  Section F — Health-Seeking Behavior (Q83-Q87)                        }
{  Q84 SERVICE_TYPE gates Section G (Outpatient/Primary) vs Section H   }
{  (Inpatient/Emergency) vs Section I direct (Other).                   }
{ ===================================================================== }

PROC Q84_SERVICE_TYPE
postproc
    { Cross-section routing per F3-Skip-Logic-and-Validations.md §2:
        - 1 (Outpatient) or 4 (Primary care)  -> Section G then I.
        - 2 (Inpatient)  or 3 (Emergency)     -> Section H then I.
        - 5 (Other)                            -> skip directly to Section I. }
    if Q84_SERVICE_TYPE = 5 then   { 5 = Other — both G and H skipped }
        skip to Q116_NBB_HEARD;
    endif;
    { 1/2/3/4 fall through; the section-entry gates below route correctly. }


{ ===================================================================== }
{  Section G — Outpatient Care (Q88-Q104)                               }
{ ===================================================================== }

PROC G_OUTPATIENT_CARE
preproc
    { Template 4.10 — section entry gate. If Q84 not in (1,4), skip
      Section G entirely and route to Section H (which has its own
      gate to skip if Q84 not in (2,3)). }
    if not (Q84_SERVICE_TYPE in 1, 4) then
        skip to H_INPATIENT;
    endif;


PROC Q89_ADVISED_ADMIT
postproc
    { Q90 is asked only when patient was advised admit but did not get
      confined. If Q89=No, skip Q90 (reasons-not-confined) and go to
      Q91 (usual outpatient flag). }
    if Q89_ADVISED_ADMIT = 2 then   { 2 = No }
        skip to Q91_USUAL_OUTPATIENT;
    endif;


PROC Q93_LABS_OTHER_TXT
preproc
    { Multi-response Q93 — option 17 = "None". If only "None" selected,
      skip Q94 (no lab costs). PROC checks Q93_LABS_O17 = 1 plus the
      sum of all other Q93_LABS_O## items is zero. }
    numeric count_other_labs = 0;
    numeric i;
    string fldname;
    { Each Q93 option is exposed as Q93_LABS_O01 ... Q93_LABS_O17 by the
      select_all() decomposition in generate_dcf.py. The "None" code lives
      at slot 17. }
    if Q93_LABS_O17 = 1 then
        { Sum all non-None options. }
        if Q93_LABS_O01 + Q93_LABS_O02 + Q93_LABS_O03 + Q93_LABS_O04 +
           Q93_LABS_O05 + Q93_LABS_O06 + Q93_LABS_O07 + Q93_LABS_O08 +
           Q93_LABS_O09 + Q93_LABS_O10 + Q93_LABS_O11 + Q93_LABS_O12 +
           Q93_LABS_O13 + Q93_LABS_O14 + Q93_LABS_O15 + Q93_LABS_O16 = 0 then
            skip to Q95_PRESCRIBED;
        endif;
    endif;


PROC Q95_PRESCRIBED
postproc
    if Q95_PRESCRIBED = 2 then   { 2 = No }
        skip to Q97_FINAL_AMOUNT;
    endif;


PROC Q99_BUCAS_HEARD
postproc
    if Q99_BUCAS_HEARD = 2 then   { 2 = No }
        skip to Q104_WITHOUT_BUCAS;
    endif;


PROC Q102_BUCAS_ACCESSED
postproc
    if Q102_BUCAS_ACCESSED = 2 then   { 2 = No }
        skip to Q104_WITHOUT_BUCAS;
    endif;


PROC Q104_WITHOUT_BUCAS
postproc
    { Template 4.13 — Section G terminus. Jump to Section I (Q116). }
    skip to Q116_NBB_HEARD;


{ ===================================================================== }
{  Section H — Inpatient Care (Q105-Q115)                               }
{ ===================================================================== }

PROC H_INPATIENT
preproc
    { Template 4.9 — section entry gate. Q84 must be 2 (Inpatient) or 3
      (Emergency) to ask Section H. Otherwise route to Section I. }
    if not (Q84_SERVICE_TYPE in 2, 3) then
        skip to I_FINANCIAL_RISK;
    endif;


PROC Q106_DAYS
postproc
    { Validation H7 — nights / days consistency. Days >= 1 must <= nights+1
      (day count cannot exceed night count by more than 1 — accounts for
      admit+discharge spanning two calendar days). }
    if Q106_NIGHTS < 0 or Q106_DAYS < 0 then
        errmsg("Nights / days cannot be negative. Please re-check.");
        reenter;
    endif;
    if Q106_DAYS > Q106_NIGHTS + 1 then
        errmsg("Days admitted (%v) cannot exceed nights (%v) + 1. "
               "Please re-check.", Q106_DAYS, Q106_NIGHTS);
        reenter;
    endif;


PROC Q108_MEDS_OUTSIDE
postproc
    if Q108_MEDS_OUTSIDE = 2 then   { 2 = No }
        skip to Q110_LAB_OUTSIDE;
    endif;


PROC Q110_LAB_OUTSIDE
postproc
    if Q110_LAB_OUTSIDE = 2 then   { 2 = No }
        skip to Q113_PAY_01;   { first item of the 13-source payment matrix }
    endif;


PROC Q114_NO_PH_O01
preproc
    { Q114 (multi-response: reasons for not using PhilHealth) asked
      ONLY if PhilHealth was NOT used in Q113. The Q113 payment matrix
      exposes PhilHealth as Q113_PAY_08 (zero-padded "08" per Q113_SOURCES
      build order in generate_dcf.py). If PhilHealth was used (=1), skip
      the entire Q114 select_all by jumping past it to the next-billed
      sub-block Q1141_1 (first item of Q114.1 in-bill itemization). }
    if Q113_PAY_08 = 1 then
        skip to Q1141_1;
    endif;


PROC Q115_FINAL_CASH
postproc
    { Validation H8 — sum the inpatient payment matrix (Q113_PAY_01_AMT
      through Q113_PAY_13_AMT) and warn if the total is >5% off from
      Q115_FINAL_CASH. The matrix is decomposed by generate_dcf.py
      (Q113_PAY_NN + Q113_PAY_NN_AMT for each of 13 sources). }
    numeric matrix_total =
        Q113_PAY_01_AMT + Q113_PAY_02_AMT + Q113_PAY_03_AMT +
        Q113_PAY_04_AMT + Q113_PAY_05_AMT + Q113_PAY_06_AMT +
        Q113_PAY_07_AMT + Q113_PAY_08_AMT + Q113_PAY_09_AMT +
        Q113_PAY_10_AMT + Q113_PAY_11_AMT + Q113_PAY_12_AMT +
        Q113_PAY_13_AMT;

    if Q115_FINAL_CASH > 0 then
        numeric pct_diff =
            abs(matrix_total - Q115_FINAL_CASH) * 100 / Q115_FINAL_CASH;
        if pct_diff > 5 then
            errmsg("Q113 payment matrix total (%v) differs from "
                   "Q115 final cash (%v) by >5%% (computed %v%%). "
                   "Please re-check.",
                   matrix_total, Q115_FINAL_CASH, pct_diff);
            { soft — operator accepts to continue }
        endif;
    endif;

    { Section H terminus — fall through to Section I (Q116). }


{ ===================================================================== }
{  Section I — Financial Risk Protection (Q116-Q130)                    }
{ ===================================================================== }

PROC I_FINANCIAL_RISK
preproc
    { No section entry gate — Section I is always asked. }


PROC Q116_NBB_HEARD
postproc
    if Q116_NBB_HEARD in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q119_ZBB_HEARD;
    endif;


PROC Q119_ZBB_HEARD
postproc
    if Q119_ZBB_HEARD in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q124_MAIFIP_HEARD;
    endif;


PROC Q124_MAIFIP_HEARD
postproc
    { Three-way routing:
        - Q124 in (2, 3)            -> skip to Q130 (skip Q125-Q129).
        - Q113_PAY_07 = 1 (MAIFIP)  -> handled in Q125_MAIFIP_SOURCE_O01.preproc
                                       below (skip Q125 select_all). }
    if Q124_MAIFIP_HEARD in 2, 3 then
        skip to Q130_REDUCED_SPEND;
    endif;


PROC Q125_MAIFIP_SOURCE_O01
preproc
    { Q125 (MAIFIP awareness source — multi-response) skipped if MAIFIP
      already used in Q113 (operator was already informed during the
      payment-matrix capture). Jump to Q126 (have-you-availed). }
    if Q113_PAY_07 = 1 then
        skip to Q126_MAIFIP_AVAILED;
    endif;


PROC Q126_MAIFIP_AVAILED
postproc
    { Per spec §2 Section I: Q126 = No skips Q127 (OOP) + Q128 (OOP items)
      and routes to Q129 (why-no-MAIFIP — select_all). }
    if Q126_MAIFIP_AVAILED = 2 then   { 2 = No }
        skip to Q129_WHY_NO_MAIFIP_O01;
    endif;


PROC Q127_MAIFIP_OOP
postproc
    { Q127 = No skips Q128 (OOP-items select_all) + Q129 (why-no — N/A) and
      routes direct to Q130. }
    if Q127_MAIFIP_OOP = 2 then   { 2 = No }
        skip to Q130_REDUCED_SPEND;
    endif;


{ ===================================================================== }
{  Section J — Satisfaction (Q131-Q151)                                 }
{ ===================================================================== }

PROC Q134_AMEN_ROOMS
preproc
    { Template 4.3 — Q134 (room amenities) asked only for inpatients.
      If Q84 not Inpatient (2), skip to Q136 (staff courtesy). }
    if Q84_SERVICE_TYPE <> 2 then
        skip to Q136_STAFF_COURTESY;
    endif;


PROC Q135_SAT_OVERALL_TIME
preproc
    { Template 4.3 — Q135 (overall wait-time satisfaction) asked only
      for inpatients per PDF tagging. }
    if Q84_SERVICE_TYPE <> 2 then
        skip to Q136_STAFF_COURTESY;
    endif;


PROC Q150_TRAVEL_MM
postproc
    { Validation H9 — MM in [0, 59]. }
    if Q150_TRAVEL_MM < 0 or Q150_TRAVEL_MM > 59 then
        errmsg("Travel minutes must be between 0 and 59. Please re-check.");
        reenter;
    endif;
    { Soft S2 — both HH and MM zero is unusual unless patient is at the
      pharmacy. Warn but allow. }
    if Q150_TRAVEL_HH = 0 and Q150_TRAVEL_MM = 0 then
        errmsg("Travel time recorded as 0 hours and 0 minutes. "
               "Please confirm patient lives at the pharmacy.");
        { soft — no reenter }
    endif;


{ ===================================================================== }
{  Section K — Access to Medicines (Q152-Q161)                          }
{ ===================================================================== }

PROC Q152_GAMOT_HEARD
postproc
    if Q152_GAMOT_HEARD = 2 then   { 2 = No }
        skip to Q158_BRAND_GEN_KNOW;
    endif;


PROC Q155_GAMOT_GOT_MEDS
postproc
    if Q155_GAMOT_GOT_MEDS = 2 then   { 2 = No }
        skip to Q158_BRAND_GEN_KNOW;
    endif;


PROC Q159_BRAND_GEN_BOUGHT
postproc
    { Branded / generic three-way branch (Q160_WHY_GENERIC and
      Q161_WHY_BRANDED are multi-response select_all items; the routing
      targets their first decomposed slot _O01):
        - 1 (Branded only)        -> skip Q160 select_all,
                                     ask Q161 select_all.
        - 2 (Generic only)        -> ask Q160, skip Q161 (jump to Q162).
                                     Handled in Q161_WHY_BRANDED_O01.preproc.
        - 3 (Both)                -> ask Q160 then Q161 in sequence.
        - 4 (DK) or 5 (NA)        -> skip Q160 and Q161, jump to Q162. }
    if Q159_BRAND_GEN_BOUGHT = 1 then
        skip to Q161_WHY_BRANDED_O01;
    endif;
    { Open-question §1 #2 in spec — DK/NA cross-section. Default = honor
      source: jump to Q162 (REFERRED). }
    if Q159_BRAND_GEN_BOUGHT in 4, 5 then
        skip to Q162_REFERRED;
    endif;
    { Q159 = 2 (Generic) — Q160 asked, then Q161 skipped by
      Q161_WHY_BRANDED_O01.preproc below. }
    { Q159 = 3 (Both) — both Q160 and Q161 asked; fall through. }


PROC Q161_WHY_BRANDED_O01
preproc
    { If Q159 = Generic only (2), skip the Q161 branded-reasons select_all
      and route directly to Q162 (REFERRED). }
    if Q159_BRAND_GEN_BOUGHT = 2 then
        skip to Q162_REFERRED;
    endif;


{ ===================================================================== }
{  Section L — Referrals (Q162-Q178)                                    }
{ ===================================================================== }

PROC Q162_REFERRED
postproc
    { Template 4.11 — non-referral path skips Q163-Q171 and jumps to
      Q172 (PCP referral block, asked of everyone). }
    if Q162_REFERRED = 2 then   { 2 = No }
        skip to Q172_PCP_REFERRAL;
    endif;


PROC Q169_VISITED
postproc
    { Template 4.12 — three-way branch on visit-status of referral.
      Q170_FOLLOWUP = follow-up flag (asked when visited). Q171_WHY_NOT
      is a multi-response select_all (Q171_WHY_NOT_O01.. is the routing
      target). }
    if Q169_VISITED in 2, 3 then
        { Not visiting / planning later — skip Q170 (followup), ask Q171
          (why-not select_all), then proceed to Q172. }
        skip to Q171_WHY_NOT_O01;
    endif;
    { Q169 = 1 (Yes) — fall through to Q170 (followup).
      Q170.postproc handles the jump to Q172 to skip Q171. }


PROC Q170_FOLLOWUP
postproc
    { After Q170 (follow-up flag), skip Q171 (why-not) and proceed
      to Q172 since the patient DID visit the referral. }
    if Q169_VISITED = 1 then
        skip to Q172_PCP_REFERRAL;
    endif;


PROC Q172_PCP_REFERRAL
postproc
    { Non-PCP-referral path skips Q173-Q176 (PCP referral details) and
      jumps to Q177 (why-hospital select_all — first decomposed slot). }
    if Q172_PCP_REFERRAL = 2 then   { 2 = No }
        skip to Q177_WHY_HOSPITAL_O01;
    endif;


PROC Q178_SAT_REFERRAL
postproc
    { Final terminus — close the case as a complete interview. }
    CloseCaseAsComplete();


{ ===================================================================== }
{  GPS + photo capture handlers — wire shared helpers                    }
{ ===================================================================== }

PROC FACILITY_CAPTURE_GPS
onfocus
    { Trigger field — when the operator taps "Capture GPS now" the
      onfocus calls ReadGPSReading() with the F-series defaults:
      maxTimeSec=60, desiredAccuracyM=20. Results are written to
      FACILITY_GPS_LATITUDE, ..., FACILITY_GPS_READTIME. See
      shared/Capture-Helpers.apc for the helper definition. }
    ReadGPSReading(60, 20);


PROC P_HOME_CAPTURE_GPS
onfocus
    { Same as facility GPS but for the patient's home address. Asked at
      the closing of the interview if the patient agrees to share home
      coordinates (for F4 home-visit logistics). }
    ReadGPSReading(60, 20);
'''


def main():
    (HERE / "PatientSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote PatientSurvey.ent.apc ({len(APC)} chars; commit 5/6 — patient-pick + write-back)")


if __name__ == "__main__":
    main()
