"""generate_apc.py — emit PatientSurvey.ent.apc.

F3 Patient Survey logic. Implements §4 of F3-Skip-Logic-and-Validations.md.

This commit (3 of 6 in the F3 quartet build):
  - PROC GLOBAL — named constants + helper-function declarations.
  - PROC PATIENTSURVEY_LEVEL — level-scope placeholder (filled by commit 5
    with the patient-pick LEVEL.preproc + listing roster write-back logic).
  - PROC FIELD_CONTROL — case-start setup (template 4.14 from spec).
  - Section A handlers — Q1 IS_PATIENT branching (template 4.4).
  - Section B handlers — PWD gates (Q11/Q12/Q13/Q14), age/birth consistency
    (template 4.7), income amount-in-bracket consistency (template 4.8),
    HH composition consistency (validation H5/H6), Q33 decision-maker
    routing (template 4.5), Other-specify enforcement (template 4.6).
  - Section C handlers — Q35 UHC_HEARD skip pattern (template 4.1).

Commit 4 will append sections D-L handlers + payment-matrix totals +
all remaining cross-field validations.
Commit 5 will append the patient-pick PATIENTSURVEY_LEVEL.preproc that
queries PATIENTLISTING_DICT and writes F3_STATUS back to the roster.

Reference: F3-Skip-Logic-and-Validations.md (this folder).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'PatientSurvey' logic file generated by CSPro }
{ F3 Patient Survey CAPI app — skip-logic + validations per                 }
{ F3-Skip-Logic-and-Validations.md.                                          }
{                                                                             }
{ Commit 3 of 6 (F3 quartet build): control + sections A-C.                  }
{ Commits 4-5 will append sections D-L + patient-pick preproc.               }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Income bracket boundaries (validation H4) ----------------------- }
{                                                                       }
{ Six brackets from Q18_INCOME_BRACKET value set in PatientSurvey.dcf.  }
{ Used by the Q18 postproc consistency check (template 4.8) and held   }
{ here as named constants so the bracket cutoffs are auditable without  }
{ scrolling into the PROC body.                                         }

numeric BRACKET_1_HI =    39999;   { Under 40,000          }
numeric BRACKET_2_LO =    40000;
numeric BRACKET_2_HI =    59999;   { 40,000 - 59,999       }
numeric BRACKET_3_LO =    60000;
numeric BRACKET_3_HI =    99999;   { 60,000 - 99,999       }
numeric BRACKET_4_LO =   100000;
numeric BRACKET_4_HI =   249999;   { 100,000 - 249,999     }
numeric BRACKET_5_LO =   250000;
numeric BRACKET_5_HI =   499999;   { 250,000 - 499,999     }
numeric BRACKET_6_LO =   500000;   { 500,000 and over      }

{ ---- AAPOR sentinel + visit-result codes ---------------------------- }
{                                                                       }
{ Mirrored from shared/cspro_helpers.py::AAPOR_DISPOSITION_OPTIONS and  }
{ ENUM_RESULT_OPTIONS. Held as APC constants so end-of-case dispositions }
{ are readable in the PROC code without consulting the DCF value sets.  }

numeric AAPOR_IN_PROGRESS         =   0;   { 000 - In Progress (initial)    }
numeric AAPOR_COMPLETE            = 110;   { 1.1 - Complete interview        }
numeric AAPOR_REFUSED             = 220;   { 2.20 - Refusal / break-off      }

numeric VISIT_RESULT_COMPLETED            = 1;
numeric VISIT_RESULT_WITHDRAW_CONSENT     = 6;


{ ---- Helper: end-of-section terminator ------------------------------ }

function CloseCaseAsComplete()
    { Set the closing AAPOR + visit-result codes when a respondent
      completes through the final terminus item (Q178 SAT_REFERRAL or
      the non-referral terminus at Q172+). Wired from PROC Q178 and the
      end-of-survey paths in commit 4. }
    AAPOR_DISPOSITION        = AAPOR_COMPLETE;
    ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_COMPLETED;
    DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
end;


PROC PATIENTSURVEY_LEVEL
{ Level-scope preproc placeholder. Commit 5 will fill this with the
  patient-pick logic that queries PATIENTLISTING_DICT via loadcase()
  and writes ASSIGNED_F3_CASE_SEQ + F3_STATUS=2 back to the chosen
  roster occurrence. }


{ ===================================================================== }
{  FIELD_CONTROL — case-start setup (template 4.14)                     }
{ ===================================================================== }

PROC FIELD_CONTROL
preproc
    SURVEY_CODE        = "F3";
    DATE_STARTED       = SYSDATE("YYYYMMDD");
    TIME_STARTED       = SYSTIME("HHMMSS");
    AAPOR_DISPOSITION  = AAPOR_IN_PROGRESS;

    { INTERVIEWER_ID and PATIENT_LISTING_NO are stamped by the
      patient-pick preproc (commit 5) before the operator sees any
      form. DATE_FIRST_VISITED defaults to today if the operator does
      not override on the first visit. }
    if DATE_FIRST_VISITED = 0 then
        DATE_FIRST_VISITED = SYSDATE("YYYYMMDD");
    endif;


PROC CONSENT_GIVEN
postproc
    { Hard terminator: if the patient withdraws consent at the read-out,
      mark the case withdrawn and end the interview. The operator is
      expected to save the partial case so the disposition is preserved
      for paradata. Per F3-Skip-Logic-and-Validations.md §2 Section A
      ("Terminate interview" rule). }
    if CONSENT_GIVEN = 2 then   { 2 = No }
        AAPOR_DISPOSITION        = AAPOR_REFUSED;
        ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_WITHDRAW_CONSENT;
        DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
        endcase;
    endif;


{ ===================================================================== }
{  Section A — Introduction and Informed Consent (Q1-Q3)                }
{ ===================================================================== }

PROC Q1_IS_PATIENT
postproc
    { Template 4.4 — if respondent IS the patient, skip Q2 (relationship)
      and Q3 (same-house), proceed direct to Q4. Q2/Q3 only asked when
      the respondent is a proxy informant. }
    if Q1_IS_PATIENT = 1 then
        skip to Q4_NAME;
    endif;


PROC Q2_RELATIONSHIP_OTHER_TXT
preproc
    if Q2_RELATIONSHIP <> 19 then   { 19 = "Other (specify)" }
        skip to Q3_SAME_HOUSE;
    endif;
postproc
    { Other-specify enforcement (template 4.6 / validation S5). }
    if Q2_RELATIONSHIP = 19 and strlen(strip(Q2_RELATIONSHIP_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' relationship to the patient.");
        reenter;
    endif;


{ ===================================================================== }
{  Section B — Patient Profile (Q4-Q34)                                 }
{ ===================================================================== }

PROC Q6_AGE
postproc
    { Validation H2/H3 — age range + age-vs-birth-year consistency
      (template 4.7). Allow off-by-one on calendar-rollover edge case. }
    if Q6_AGE < 0 or Q6_AGE > 120 then
        errmsg("Age must be between 0 and 120. Please re-check.");
        reenter;
    endif;

    numeric calc_age = tonumber(SYSDATE("YYYY")) - Q5_BIRTH_YEAR;
    if abs(calc_age - Q6_AGE) > 1 then
        errmsg("Age (%v) inconsistent with birth year %v (computed %v). "
               "Please re-check.",
               Q6_AGE, Q5_BIRTH_YEAR, calc_age);
        reenter;
    endif;

    { Soft S1 — patient <18 (relative reporting allowed via Q1=No,
      so this warns but does not block save). }
    if Q6_AGE < 18 then
        if Q1_IS_PATIENT = 1 then
            errmsg("Patient age <18 and respondent IS the patient. "
                   "Please confirm relative-reporting allowed; F3 "
                   "should not enroll minors as self-respondents.");
            { soft — operator confirms by accepting; no reenter }
        endif;
    endif;


PROC Q11_PWD
postproc
    { PWD-gate: if not PWD, skip the PWD-specific chain Q12-Q14. }
    if Q11_PWD = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q12_PWD_SPECIFY
postproc
    { PWD-specify-gate: if PWD but does not want to specify, skip Q13/Q14. }
    if Q12_PWD_SPECIFY = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q13_PWD_CARD
postproc
    { Card-gate (template 4.x / GATE rule §3): Q14 only when Q13 = 1
      (card was presented and verified). Otherwise skip to Q15. }
    if Q13_PWD_CARD <> 1 then
        skip to Q15_EDUCATION;
    endif;


PROC Q14_DISABILITY_OTHER_TXT
preproc
    if Q14_DISABILITY_TYPE <> 8 then   { 8 = "Other disability (specify)" }
        skip to Q15_EDUCATION;
    endif;
postproc
    { Soft S4 — warn if Other selected but text blank. }
    if Q14_DISABILITY_TYPE = 8 and strlen(strip(Q14_DISABILITY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' disability type.");
        { soft — does not reenter }
    endif;


PROC Q18_INCOME_BRACKET
postproc
    { Template 4.8 — amount-in-bracket consistency (validation H4). }
    numeric lo;
    numeric hi;

    if      Q18_INCOME_BRACKET = 1 then lo = 0;              hi = BRACKET_1_HI;
    elseif  Q18_INCOME_BRACKET = 2 then lo = BRACKET_2_LO;   hi = BRACKET_2_HI;
    elseif  Q18_INCOME_BRACKET = 3 then lo = BRACKET_3_LO;   hi = BRACKET_3_HI;
    elseif  Q18_INCOME_BRACKET = 4 then lo = BRACKET_4_LO;   hi = BRACKET_4_HI;
    elseif  Q18_INCOME_BRACKET = 5 then lo = BRACKET_5_LO;   hi = BRACKET_5_HI;
    elseif  Q18_INCOME_BRACKET = 6 then lo = BRACKET_6_LO;   hi = 9999999;
    endif;

    if not (Q18_INCOME_AMOUNT >= lo and Q18_INCOME_AMOUNT <= hi) then
        errmsg("Income amount %v is outside bracket %v (%v - %v). "
               "Please re-check.",
               Q18_INCOME_AMOUNT, Q18_INCOME_BRACKET, lo, hi);
        reenter;
    endif;


PROC Q19_HH_SIZE
postproc
    { Validation H6 — HH size range. }
    if Q19_HH_SIZE < 1 or Q19_HH_SIZE > 30 then
        errmsg("Household size must be between 1 and 30. Please re-check.");
        reenter;
    endif;


PROC Q21_HH_SENIORS
postproc
    { Validation H5/H6 — HH composition coverage: total HH size must
      accommodate the children + senior sub-counts. Q20+Q21 = subset of Q19. }
    if Q19_HH_SIZE < Q20_HH_CHILDREN + Q21_HH_SENIORS then
        errmsg("HH size %v cannot be smaller than children %v + seniors %v.",
               Q19_HH_SIZE, Q20_HH_CHILDREN, Q21_HH_SENIORS);
        reenter;
    endif;
    if Q20_HH_CHILDREN > Q19_HH_SIZE or Q21_HH_SENIORS > Q19_HH_SIZE then
        errmsg("Children or seniors count exceeds total HH size %v. "
               "Please re-check.", Q19_HH_SIZE);
        reenter;
    endif;


PROC Q23_WATER_OTHER_TXT
preproc
    { Template 4.6 — Other-specify gate + enforcement. }
    if Q23_WATER <> 4 then   { 4 = "Other (specify)" }
        skip to Q24_FAUCET_OWN;
    endif;
postproc
    if Q23_WATER = 4 and strlen(strip(Q23_WATER_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' water source.");
        reenter;
    endif;


PROC Q30_IP
postproc
    { Indigenous Peoples gate — if not IP, skip Q31 (IP group). }
    if Q30_IP = 2 then   { 2 = No }
        skip to Q32_RELIGION;
    endif;


PROC Q33_DECISION_MAKER
postproc
    { Template 4.5 — if respondent IS the decision-maker (1), or the
      companion is (3), skip Q34 (DM identification) and go to Q35. }
    if Q33_DECISION_MAKER in 1, 3 then
        skip to Q35_UHC_HEARD;
    endif;


{ ===================================================================== }
{  Section C — UHC Awareness (Q35-Q37)                                  }
{ ===================================================================== }

PROC Q35_UHC_HEARD
postproc
    { Template 4.1 — if has not heard of UHC, skip the awareness-detail
      questions Q36/Q37 and jump to Section D. }
    if Q35_UHC_HEARD = 2 then   { 2 = No }
        skip to Q38_PHILHEALTH_REG;
    endif;
'''


def main():
    (HERE / "PatientSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote PatientSurvey.ent.apc ({len(APC)} chars; commit 3/6 — control + A/B/C)")


if __name__ == "__main__":
    main()
