"""generate_apc.py — emit PatientSurvey.ent.apc.

F3 Patient Survey logic. Implements §4 of F3-Skip-Logic-and-Validations.md.

Commits in the F3 quartet build:
  - PROC GLOBAL — named constants + helper-function declarations.
  - PROC PATIENTSURVEY_LEVEL — level-scope placeholder (filled by commit 5
    with the patient-pick LEVEL.preproc + listing roster write-back logic).
  - PROC FIELD_CONTROL — case-start setup (template 4.14 from spec).
  - Section A — Q1 IS_PATIENT branching (template 4.4).
  - Section B — PWD gates (Q11/Q12/Q13/Q14), age/birth consistency
    (template 4.7), income amount-in-bracket consistency (template 4.8),
    HH composition consistency (validation H5/H6), Q33 decision-maker
    routing (template 4.5), Other-specify enforcement (template 4.6).
  - Section C — Q35 UHC_HEARD skip pattern (template 4.1).
  - Section D — PhilHealth registration + insurance skip chain (Q38-Q52).
  - Section E — Primary care utilization + Konsulta gates (Q53-Q82).
  - Section F — service-type routing to G/H/I (Q84 SERVICE_TYPE).
  - Section G — outpatient care chain (Q89/Q93/Q95/Q99/Q102/Q104).
  - Section H — inpatient care chain (Q108/Q110/Q113/Q114).
  - Section I — Financial Risk Protection (Q116/Q119/Q124/Q126/Q127).
  - Section J — inpatient-gated amenity questions (Q134/Q135).
  - Section K — Access to Medicines + brand/generic branching (Q152/Q155/Q159).
  - Section L — referrals + end-of-survey terminator (Q162/Q169/Q172/Q178).
  - Payment-matrix totals — Q97/Q115 reconciliation (validation H8/S3).

Reference: F3-Skip-Logic-and-Validations.md (this folder).
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent

APC = r'''{ Application 'PatientSurvey' logic file generated by CSPro }
{ F3 Patient Survey CAPI app — skip-logic + validations per                 }
{ F3-Skip-Logic-and-Validations.md.                                          }
{                                                                             }
{ Commit 3 of 6 (F3 quartet build): control + sections A-C.                  }
{ Commits 4-5 will append sections D-L + patient-pick preproc.               }

#include "../shared/Capture-Helpers.apc"

PROC GLOBAL

{ ---- Income bracket boundaries (validation H4) ----------------------- }
{                                                                       }
{ Six brackets from Q18_INCOME_BRACKET value set in PatientSurvey.dcf.  }
{ Used by the Q18 postproc consistency check (template 4.8) and held   }
{ here as named constants so the bracket cutoffs are auditable without  }
{ scrolling into the PROC body.                                         }

numeric BRACKET_1_HI =    39999;   { Under 40,000          }
numeric BRACKET_2_LO =    40000;
numeric BRACKET_2_HI =    59999;   { 40,000 - 59,999       }
numeric BRACKET_3_LO =    60000;
numeric BRACKET_3_HI =    99999;   { 60,000 - 99,999       }
numeric BRACKET_4_LO =   100000;
numeric BRACKET_4_HI =   249999;   { 100,000 - 249,999     }
numeric BRACKET_5_LO =   250000;
numeric BRACKET_5_HI =   499999;   { 250,000 - 499,999     }
numeric BRACKET_6_LO =   500000;   { 500,000 and over      }

{ ---- AAPOR sentinel + visit-result codes ---------------------------- }
{                                                                       }
{ Mirrored from shared/cspro_helpers.py::AAPOR_DISPOSITION_OPTIONS and  }
{ ENUM_RESULT_OPTIONS. Held as APC constants so end-of-case dispositions }
{ are readable in the PROC code without consulting the DCF value sets.  }

numeric AAPOR_IN_PROGRESS         =   0;   { 000 - In Progress (initial)    }
numeric AAPOR_COMPLETE            = 110;   { 1.1 - Complete interview        }
numeric AAPOR_REFUSED             = 220;   { 2.20 - Refusal / break-off      }

numeric VISIT_RESULT_COMPLETED            = 1;
numeric VISIT_RESULT_WITHDRAW_CONSENT     = 6;


{ ---- Helper: end-of-section terminator ------------------------------ }

function CloseCaseAsComplete()
    { Set the closing AAPOR + visit-result codes when a respondent
      completes through the final terminus item (Q178 SAT_REFERRAL or
      the non-referral terminus at Q172+). Wired from PROC Q178 and the
      end-of-survey paths in commit 4. }
    AAPOR_DISPOSITION        = AAPOR_COMPLETE;
    ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_COMPLETED;
    DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
end;


PROC PATIENTSURVEY_LEVEL
{ Level-scope preproc placeholder. Commit 5 will fill this with the
  patient-pick logic that queries PATIENTLISTING_DICT via loadcase()
  and writes ASSIGNED_F3_CASE_SEQ + F3_STATUS=2 back to the chosen
  roster occurrence. }


{ ===================================================================== }
{  FIELD_CONTROL — case-start setup (template 4.14)                     }
{ ===================================================================== }

PROC FIELD_CONTROL
preproc
    SURVEY_CODE        = "F3";
    DATE_STARTED       = SYSDATE("YYYYMMDD");
    TIME_STARTED       = SYSTIME("HHMMSS");
    AAPOR_DISPOSITION  = AAPOR_IN_PROGRESS;

    { INTERVIEWER_ID and PATIENT_LISTING_NO are stamped by the
      patient-pick preproc (commit 5) before the operator sees any
      form. DATE_FIRST_VISITED defaults to today if the operator does
      not override on the first visit. }
    if DATE_FIRST_VISITED = 0 then
        DATE_FIRST_VISITED = SYSDATE("YYYYMMDD");
    endif;


PROC CONSENT_GIVEN
postproc
    { Hard terminator: if the patient withdraws consent at the read-out,
      mark the case withdrawn and end the interview. The operator is
      expected to save the partial case so the disposition is preserved
      for paradata. Per F3-Skip-Logic-and-Validations.md §2 Section A
      ("Terminate interview" rule). }
    if CONSENT_GIVEN = 2 then   { 2 = No }
        AAPOR_DISPOSITION        = AAPOR_REFUSED;
        ENUM_RESULT_FINAL_VISIT  = VISIT_RESULT_WITHDRAW_CONSENT;
        DATE_FINAL_VISIT         = SYSDATE("YYYYMMDD");
        endcase;
    endif;


{ ===================================================================== }
{  Section A — Introduction and Informed Consent (Q1-Q3)                }
{ ===================================================================== }

PROC Q1_IS_PATIENT
postproc
    { Template 4.4 — if respondent IS the patient, skip Q2 (relationship)
      and Q3 (same-house), proceed direct to Q4. Q2/Q3 only asked when
      the respondent is a proxy informant. }
    if Q1_IS_PATIENT = 1 then
        skip to Q4_NAME;
    endif;


PROC Q2_RELATIONSHIP_OTHER_TXT
preproc
    if Q2_RELATIONSHIP <> 19 then   { 19 = "Other (specify)" }
        skip to Q3_SAME_HOUSE;
    endif;
postproc
    { Other-specify enforcement (template 4.6 / validation S5). }
    if Q2_RELATIONSHIP = 19 and strlen(strip(Q2_RELATIONSHIP_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' relationship to the patient.");
        reenter;
    endif;


{ ===================================================================== }
{  Section B — Patient Profile (Q4-Q34)                                 }
{ ===================================================================== }

PROC Q6_AGE
postproc
    { Validation H2/H3 — age range + age-vs-birth-year consistency
      (template 4.7). Allow off-by-one on calendar-rollover edge case. }
    if Q6_AGE < 0 or Q6_AGE > 120 then
        errmsg("Age must be between 0 and 120. Please re-check.");
        reenter;
    endif;

    numeric calc_age = tonumber(SYSDATE("YYYY")) - Q5_BIRTH_YEAR;
    if abs(calc_age - Q6_AGE) > 1 then
        errmsg("Age (%v) inconsistent with birth year %v (computed %v). "
               "Please re-check.",
               Q6_AGE, Q5_BIRTH_YEAR, calc_age);
        reenter;
    endif;

    { Soft S1 — patient <18 (relative reporting allowed via Q1=No,
      so this warns but does not block save). }
    if Q6_AGE < 18 then
        if Q1_IS_PATIENT = 1 then
            errmsg("Patient age <18 and respondent IS the patient. "
                   "Please confirm relative-reporting allowed; F3 "
                   "should not enroll minors as self-respondents.");
            { soft — operator confirms by accepting; no reenter }
        endif;
    endif;


PROC Q11_PWD
postproc
    { PWD-gate: if not PWD, skip the PWD-specific chain Q12-Q14. }
    if Q11_PWD = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q12_PWD_SPECIFY
postproc
    { PWD-specify-gate: if PWD but does not want to specify, skip Q13/Q14. }
    if Q12_PWD_SPECIFY = 2 then   { 2 = No }
        skip to Q15_EDUCATION;
    endif;


PROC Q13_PWD_CARD
postproc
    { Card-gate (template 4.x / GATE rule §3): Q14 only when Q13 = 1
      (card was presented and verified). Otherwise skip to Q15. }
    if Q13_PWD_CARD <> 1 then
        skip to Q15_EDUCATION;
    endif;


PROC Q14_DISABILITY_OTHER_TXT
preproc
    if Q14_DISABILITY_TYPE <> 8 then   { 8 = "Other disability (specify)" }
        skip to Q15_EDUCATION;
    endif;
postproc
    { Soft S4 — warn if Other selected but text blank. }
    if Q14_DISABILITY_TYPE = 8 and strlen(strip(Q14_DISABILITY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' disability type.");
        { soft — does not reenter }
    endif;


PROC Q18_INCOME_BRACKET
postproc
    { Template 4.8 — amount-in-bracket consistency (validation H4). }
    numeric lo;
    numeric hi;

    if      Q18_INCOME_BRACKET = 1 then lo = 0;              hi = BRACKET_1_HI;
    elseif  Q18_INCOME_BRACKET = 2 then lo = BRACKET_2_LO;   hi = BRACKET_2_HI;
    elseif  Q18_INCOME_BRACKET = 3 then lo = BRACKET_3_LO;   hi = BRACKET_3_HI;
    elseif  Q18_INCOME_BRACKET = 4 then lo = BRACKET_4_LO;   hi = BRACKET_4_HI;
    elseif  Q18_INCOME_BRACKET = 5 then lo = BRACKET_5_LO;   hi = BRACKET_5_HI;
    elseif  Q18_INCOME_BRACKET = 6 then lo = BRACKET_6_LO;   hi = 9999999;
    endif;

    if not (Q18_INCOME_AMOUNT >= lo and Q18_INCOME_AMOUNT <= hi) then
        errmsg("Income amount %v is outside bracket %v (%v - %v). "
               "Please re-check.",
               Q18_INCOME_AMOUNT, Q18_INCOME_BRACKET, lo, hi);
        reenter;
    endif;


PROC Q19_HH_SIZE
postproc
    { Validation H6 — HH size range. }
    if Q19_HH_SIZE < 1 or Q19_HH_SIZE > 30 then
        errmsg("Household size must be between 1 and 30. Please re-check.");
        reenter;
    endif;


PROC Q21_HH_SENIORS
postproc
    { Validation H5/H6 — HH composition coverage: total HH size must
      accommodate the children + senior sub-counts. Q20+Q21 = subset of Q19. }
    if Q19_HH_SIZE < Q20_HH_CHILDREN + Q21_HH_SENIORS then
        errmsg("HH size %v cannot be smaller than children %v + seniors %v.",
               Q19_HH_SIZE, Q20_HH_CHILDREN, Q21_HH_SENIORS);
        reenter;
    endif;
    if Q20_HH_CHILDREN > Q19_HH_SIZE or Q21_HH_SENIORS > Q19_HH_SIZE then
        errmsg("Children or seniors count exceeds total HH size %v. "
               "Please re-check.", Q19_HH_SIZE);
        reenter;
    endif;


PROC Q23_WATER_OTHER_TXT
preproc
    { Template 4.6 — Other-specify gate + enforcement. }
    if Q23_WATER <> 4 then   { 4 = "Other (specify)" }
        skip to Q24_FAUCET_OWN;
    endif;
postproc
    if Q23_WATER = 4 and strlen(strip(Q23_WATER_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' water source.");
        reenter;
    endif;


PROC Q30_IP
postproc
    { Indigenous Peoples gate — if not IP, skip Q31 (IP group). Q32 in
      the DCF is the 4Ps beneficiary flag (Q32_4PS), per the Apr 20 PDF
      item ordering. }
    if Q30_IP = 2 then   { 2 = No }
        skip to Q32_4PS;
    endif;


PROC Q33_DECISION_MAKER
postproc
    { Template 4.5 — if respondent IS the decision-maker (1), or the
      companion is (3), skip Q34 (DM identification) and go to Q35. }
    if Q33_DECISION_MAKER in 1, 3 then
        skip to Q35_UHC_HEARD;
    endif;


{ ===================================================================== }
{  Section C — UHC Awareness (Q35-Q37)                                  }
{ ===================================================================== }

PROC Q35_UHC_HEARD
postproc
    { Template 4.1 — if has not heard of UHC, skip the awareness-detail
      questions Q36/Q37 and jump to Section D. }
    if Q35_UHC_HEARD = 2 then   { 2 = No }
        skip to Q38_PHILHEALTH_REG;
    endif;


{ ===================================================================== }
{  Section D — PhilHealth Registration + Insurance (Q38-Q52)            }
{ ===================================================================== }

PROC Q38_PHILHEALTH_REG
postproc
    { Template 4.1 — non-registered / DK skips the registration-detail
      questions Q39-Q42 and jumps direct to Q43 (knows-of-assistance). }
    if Q38_PHILHEALTH_REG in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q43_KNOWS_ASSIST;
    endif;


PROC Q41_REG_DIFFICULTY
postproc
    if Q41_REG_DIFFICULTY = 2 then   { 2 = No }
        skip to Q43_KNOWS_ASSIST;
    endif;


PROC Q43_KNOWS_ASSIST
postproc
    { Non-member path: per PDF, Q43=No skips Q44 + Q45-Q50 (all
      asked-only-for-members) and jumps to Q51 (other insurance). }
    if Q43_KNOWS_ASSIST = 2 then   { 2 = No }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q45_CATEGORY
preproc
    { Member-gate: Q45-Q50 asked only when Q38=1 (registered).
      Per PDF "ASKED ONLY FOR PHILHEALTH MEMBERS. SKIP TO 51 FOR NON-MEMBERS". }
    if Q38_PHILHEALTH_REG <> 1 then
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q45_CATEGORY_OTHER_TXT
preproc
    { Other-specify gate (template 4.6). 96 = Other (per PSA convention).
      Q46_BENEFITS is a select_all; route to its first decomposed slot. }
    if Q45_CATEGORY <> 96 then
        skip to Q46_BENEFITS_O01;
    endif;
postproc
    if Q45_CATEGORY = 96 and strlen(strip(Q45_CATEGORY_OTHER_TXT)) = 0 then
        errmsg("Please specify the 'Other' PhilHealth category.");
        reenter;
    endif;


PROC Q48_PREMIUM_PAY
postproc
    { Non-payer skips premium-difficulty / amount-difficulty. }
    if Q48_PREMIUM_PAY = 3 then   { 3 = No / does not pay premium }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q49_PREMIUM_DIFFICULT
postproc
    if Q49_PREMIUM_DIFFICULT = 2 then   { 2 = No }
        skip to Q51_OTHER_INSURANCE;
    endif;


PROC Q51_OTHER_INSURANCE
postproc
    { Skip Q52 detail when no other insurance. }
    if Q51_OTHER_INSURANCE = 2 then   { 2 = No }
        skip to Q53_HAS_PCP;
    endif;


{ ===================================================================== }
{  Section E — Primary Care Utilization (Q53-Q82)                       }
{ ===================================================================== }

PROC Q53_HAS_PCP
postproc
    { No-PCP skips the entire PCP-attribute chain Q54-Q62 and jumps to
      Q63 (has-usual-facility). }
    if Q53_HAS_PCP = 2 then   { 2 = No }
        skip to Q63_HAS_USUAL_FACILITY;
    endif;


PROC Q60_SCHED_TELECON_OK
preproc
    { Template 4.2 — Q60 telecon-detail gated by Q59 contains "Teleconsultation".
      The select-all is decomposed into Q59_SCHED_COMM_O01..O0n by the
      DCF generator; option 2 (Teleconsultation) corresponds to
      Q59_SCHED_COMM_O02. Skip Q60 if telecon not chosen; route to the
      first slot of Q61 select_all. }
    if Q59_SCHED_COMM_O02 <> 1 then
        skip to Q61_CONSULT_COMM_O01;
    endif;


PROC Q62_CONSULT_TELECON_OK
preproc
    { Template 4.2 — Q62 telecon-detail gated by Q61 contains "Teleconsultation". }
    if Q61_CONSULT_COMM_O02 <> 1 then
        skip to Q63_HAS_USUAL_FACILITY;
    endif;


PROC Q63_HAS_USUAL_FACILITY
postproc
    { No-usual-facility — Q64 facility name unused; after Q65 (why-no-usual
      select_all) skip Q66-Q70 (same-as-usual chain) and jump to Q71.
      Implementation: defer the routing to Q66.preproc below — when Q66
      opens, if Q63=No we skip the whole same-as-usual chain. }
    { No skip emitted on Q63 — Q65 is still asked when Q63=No. }


PROC Q66_SAME_AS_USUAL
preproc
    { When Q63=No (no usual facility), the entire same-as-usual chain
      (Q66-Q70) is skipped. Route to Q71 (nearest-facility type — the
      first item of the "nearest facility" block asked of everyone). }
    if Q63_HAS_USUAL_FACILITY = 2 then
        skip to Q71_NEAREST_TYPE;
    endif;
postproc
    { If usual = today's facility, skip Q67 (which other facility) and
      proceed to Q68 (usual-facility type). }
    if Q66_SAME_AS_USUAL = 1 then   { 1 = Yes }
        skip to Q68_USUAL_FAC_TYPE;
    endif;


PROC Q74_KON_HEARD
postproc
    { Konsulta awareness chain: never-heard skips Q75-Q82 entirely.
      Q83 is the first item of Section F (Q83_VISIT_REASON). }
    if Q74_KON_HEARD = 2 then   { 2 = No }
        skip to Q83_VISIT_REASON;
    endif;


PROC Q77_KON_REGISTERED
postproc
    { Konsulta registration chain:
        - "Not registered" (2)         -> skip to Q82 (why-not-registered).
        - "Never heard" (3) or DK (4)  -> skip to Q83 (Section F start).
      Q82_KON_WHY_NOT_REG is a select_all; CSPro routes to its first
      decomposed item _O01. }
    if Q77_KON_REGISTERED = 2 then
        skip to Q82_KON_WHY_NOT_REG_O01;
    endif;
    if Q77_KON_REGISTERED in 3, 4 then
        skip to Q83_VISIT_REASON;
    endif;


{ ===================================================================== }
{  Section F — Health-Seeking Behavior (Q83-Q87)                        }
{  Q84 SERVICE_TYPE gates Section G (Outpatient/Primary) vs Section H   }
{  (Inpatient/Emergency) vs Section I direct (Other).                   }
{ ===================================================================== }

PROC Q84_SERVICE_TYPE
postproc
    { Cross-section routing per F3-Skip-Logic-and-Validations.md §2:
        - 1 (Outpatient) or 4 (Primary care)  -> Section G then I.
        - 2 (Inpatient)  or 3 (Emergency)     -> Section H then I.
        - 5 (Other)                            -> skip directly to Section I. }
    if Q84_SERVICE_TYPE = 5 then   { 5 = Other — both G and H skipped }
        skip to Q116_NBB_HEARD;
    endif;
    { 1/2/3/4 fall through; the section-entry gates below route correctly. }


{ ===================================================================== }
{  Section G — Outpatient Care (Q88-Q104)                               }
{ ===================================================================== }

PROC G_OUTPATIENT_CARE
preproc
    { Template 4.10 — section entry gate. If Q84 not in (1,4), skip
      Section G entirely and route to Section H (which has its own
      gate to skip if Q84 not in (2,3)). }
    if not (Q84_SERVICE_TYPE in 1, 4) then
        skip to H_INPATIENT;
    endif;


PROC Q89_ADVISED_ADMIT
postproc
    { Q90 is asked only when patient was advised admit but did not get
      confined. If Q89=No, skip Q90 (reasons-not-confined) and go to
      Q91 (usual outpatient flag). }
    if Q89_ADVISED_ADMIT = 2 then   { 2 = No }
        skip to Q91_USUAL_OUTPATIENT;
    endif;


PROC Q93_LABS_OTHER_TXT
preproc
    { Multi-response Q93 — option 17 = "None". If only "None" selected,
      skip Q94 (no lab costs). PROC checks Q93_LABS_O17 = 1 plus the
      sum of all other Q93_LABS_O## items is zero. }
    numeric count_other_labs = 0;
    numeric i;
    string fldname;
    { Each Q93 option is exposed as Q93_LABS_O01 ... Q93_LABS_O17 by the
      select_all() decomposition in generate_dcf.py. The "None" code lives
      at slot 17. }
    if Q93_LABS_O17 = 1 then
        { Sum all non-None options. }
        if Q93_LABS_O01 + Q93_LABS_O02 + Q93_LABS_O03 + Q93_LABS_O04 +
           Q93_LABS_O05 + Q93_LABS_O06 + Q93_LABS_O07 + Q93_LABS_O08 +
           Q93_LABS_O09 + Q93_LABS_O10 + Q93_LABS_O11 + Q93_LABS_O12 +
           Q93_LABS_O13 + Q93_LABS_O14 + Q93_LABS_O15 + Q93_LABS_O16 = 0 then
            skip to Q95_PRESCRIBED;
        endif;
    endif;


PROC Q95_PRESCRIBED
postproc
    if Q95_PRESCRIBED = 2 then   { 2 = No }
        skip to Q97_FINAL_AMOUNT;
    endif;


PROC Q99_BUCAS_HEARD
postproc
    if Q99_BUCAS_HEARD = 2 then   { 2 = No }
        skip to Q104_WITHOUT_BUCAS;
    endif;


PROC Q102_BUCAS_ACCESSED
postproc
    if Q102_BUCAS_ACCESSED = 2 then   { 2 = No }
        skip to Q104_WITHOUT_BUCAS;
    endif;


PROC Q104_WITHOUT_BUCAS
postproc
    { Template 4.13 — Section G terminus. Jump to Section I (Q116). }
    skip to Q116_NBB_HEARD;


{ ===================================================================== }
{  Section H — Inpatient Care (Q105-Q115)                               }
{ ===================================================================== }

PROC H_INPATIENT
preproc
    { Template 4.9 — section entry gate. Q84 must be 2 (Inpatient) or 3
      (Emergency) to ask Section H. Otherwise route to Section I. }
    if not (Q84_SERVICE_TYPE in 2, 3) then
        skip to I_FINANCIAL_RISK;
    endif;


PROC Q106_DAYS
postproc
    { Validation H7 — nights / days consistency. Days >= 1 must <= nights+1
      (day count cannot exceed night count by more than 1 — accounts for
      admit+discharge spanning two calendar days). }
    if Q106_NIGHTS < 0 or Q106_DAYS < 0 then
        errmsg("Nights / days cannot be negative. Please re-check.");
        reenter;
    endif;
    if Q106_DAYS > Q106_NIGHTS + 1 then
        errmsg("Days admitted (%v) cannot exceed nights (%v) + 1. "
               "Please re-check.", Q106_DAYS, Q106_NIGHTS);
        reenter;
    endif;


PROC Q108_MEDS_OUTSIDE
postproc
    if Q108_MEDS_OUTSIDE = 2 then   { 2 = No }
        skip to Q110_LAB_OUTSIDE;
    endif;


PROC Q110_LAB_OUTSIDE
postproc
    if Q110_LAB_OUTSIDE = 2 then   { 2 = No }
        skip to Q113_PAY_01;   { first item of the 13-source payment matrix }
    endif;


PROC Q114_NO_PH_O01
preproc
    { Q114 (multi-response: reasons for not using PhilHealth) asked
      ONLY if PhilHealth was NOT used in Q113. The Q113 payment matrix
      exposes PhilHealth as Q113_PAY_08 (zero-padded "08" per Q113_SOURCES
      build order in generate_dcf.py). If PhilHealth was used (=1), skip
      the entire Q114 select_all by jumping past it to the next-billed
      sub-block Q1141_1 (first item of Q114.1 in-bill itemization). }
    if Q113_PAY_08 = 1 then
        skip to Q1141_1;
    endif;


PROC Q115_FINAL_CASH
postproc
    { Validation H8 — sum the inpatient payment matrix (Q113_PAY_01_AMT
      through Q113_PAY_13_AMT) and warn if the total is >5% off from
      Q115_FINAL_CASH. The matrix is decomposed by generate_dcf.py
      (Q113_PAY_NN + Q113_PAY_NN_AMT for each of 13 sources). }
    numeric matrix_total =
        Q113_PAY_01_AMT + Q113_PAY_02_AMT + Q113_PAY_03_AMT +
        Q113_PAY_04_AMT + Q113_PAY_05_AMT + Q113_PAY_06_AMT +
        Q113_PAY_07_AMT + Q113_PAY_08_AMT + Q113_PAY_09_AMT +
        Q113_PAY_10_AMT + Q113_PAY_11_AMT + Q113_PAY_12_AMT +
        Q113_PAY_13_AMT;

    if Q115_FINAL_CASH > 0 then
        numeric pct_diff =
            abs(matrix_total - Q115_FINAL_CASH) * 100 / Q115_FINAL_CASH;
        if pct_diff > 5 then
            errmsg("Q113 payment matrix total (%v) differs from "
                   "Q115 final cash (%v) by >5%% (computed %v%%). "
                   "Please re-check.",
                   matrix_total, Q115_FINAL_CASH, pct_diff);
            { soft — operator accepts to continue }
        endif;
    endif;

    { Section H terminus — fall through to Section I (Q116). }


{ ===================================================================== }
{  Section I — Financial Risk Protection (Q116-Q130)                    }
{ ===================================================================== }

PROC I_FINANCIAL_RISK
preproc
    { No section entry gate — Section I is always asked. }


PROC Q116_NBB_HEARD
postproc
    if Q116_NBB_HEARD in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q119_ZBB_HEARD;
    endif;


PROC Q119_ZBB_HEARD
postproc
    if Q119_ZBB_HEARD in 2, 3 then   { 2 = No, 3 = DK }
        skip to Q124_MAIFIP_HEARD;
    endif;


PROC Q124_MAIFIP_HEARD
postproc
    { Three-way routing:
        - Q124 in (2, 3)            -> skip to Q130 (skip Q125-Q129).
        - Q113_PAY_07 = 1 (MAIFIP)  -> handled in Q125_MAIFIP_SOURCE_O01.preproc
                                       below (skip Q125 select_all). }
    if Q124_MAIFIP_HEARD in 2, 3 then
        skip to Q130_REDUCED_SPEND;
    endif;


PROC Q125_MAIFIP_SOURCE_O01
preproc
    { Q125 (MAIFIP awareness source — multi-response) skipped if MAIFIP
      already used in Q113 (operator was already informed during the
      payment-matrix capture). Jump to Q126 (have-you-availed). }
    if Q113_PAY_07 = 1 then
        skip to Q126_MAIFIP_AVAILED;
    endif;


PROC Q126_MAIFIP_AVAILED
postproc
    { Per spec §2 Section I: Q126 = No skips Q127 (OOP) + Q128 (OOP items)
      and routes to Q129 (why-no-MAIFIP — select_all). }
    if Q126_MAIFIP_AVAILED = 2 then   { 2 = No }
        skip to Q129_WHY_NO_MAIFIP_O01;
    endif;


PROC Q127_MAIFIP_OOP
postproc
    { Q127 = No skips Q128 (OOP-items select_all) + Q129 (why-no — N/A) and
      routes direct to Q130. }
    if Q127_MAIFIP_OOP = 2 then   { 2 = No }
        skip to Q130_REDUCED_SPEND;
    endif;


{ ===================================================================== }
{  Section J — Satisfaction (Q131-Q151)                                 }
{ ===================================================================== }

PROC Q134_AMEN_ROOMS
preproc
    { Template 4.3 — Q134 (room amenities) asked only for inpatients.
      If Q84 not Inpatient (2), skip to Q136 (staff courtesy). }
    if Q84_SERVICE_TYPE <> 2 then
        skip to Q136_STAFF_COURTESY;
    endif;


PROC Q135_SAT_OVERALL_TIME
preproc
    { Template 4.3 — Q135 (overall wait-time satisfaction) asked only
      for inpatients per PDF tagging. }
    if Q84_SERVICE_TYPE <> 2 then
        skip to Q136_STAFF_COURTESY;
    endif;


PROC Q150_TRAVEL_MM
postproc
    { Validation H9 — MM in [0, 59]. }
    if Q150_TRAVEL_MM < 0 or Q150_TRAVEL_MM > 59 then
        errmsg("Travel minutes must be between 0 and 59. Please re-check.");
        reenter;
    endif;
    { Soft S2 — both HH and MM zero is unusual unless patient is at the
      pharmacy. Warn but allow. }
    if Q150_TRAVEL_HH = 0 and Q150_TRAVEL_MM = 0 then
        errmsg("Travel time recorded as 0 hours and 0 minutes. "
               "Please confirm patient lives at the pharmacy.");
        { soft — no reenter }
    endif;


{ ===================================================================== }
{  Section K — Access to Medicines (Q152-Q161)                          }
{ ===================================================================== }

PROC Q152_GAMOT_HEARD
postproc
    if Q152_GAMOT_HEARD = 2 then   { 2 = No }
        skip to Q158_BRAND_GEN_KNOW;
    endif;


PROC Q155_GAMOT_GOT_MEDS
postproc
    if Q155_GAMOT_GOT_MEDS = 2 then   { 2 = No }
        skip to Q158_BRAND_GEN_KNOW;
    endif;


PROC Q159_BRAND_GEN_BOUGHT
postproc
    { Branded / generic three-way branch (Q160_WHY_GENERIC and
      Q161_WHY_BRANDED are multi-response select_all items; the routing
      targets their first decomposed slot _O01):
        - 1 (Branded only)        -> skip Q160 select_all,
                                     ask Q161 select_all.
        - 2 (Generic only)        -> ask Q160, skip Q161 (jump to Q162).
                                     Handled in Q161_WHY_BRANDED_O01.preproc.
        - 3 (Both)                -> ask Q160 then Q161 in sequence.
        - 4 (DK) or 5 (NA)        -> skip Q160 and Q161, jump to Q162. }
    if Q159_BRAND_GEN_BOUGHT = 1 then
        skip to Q161_WHY_BRANDED_O01;
    endif;
    { Open-question §1 #2 in spec — DK/NA cross-section. Default = honor
      source: jump to Q162 (REFERRED). }
    if Q159_BRAND_GEN_BOUGHT in 4, 5 then
        skip to Q162_REFERRED;
    endif;
    { Q159 = 2 (Generic) — Q160 asked, then Q161 skipped by
      Q161_WHY_BRANDED_O01.preproc below. }
    { Q159 = 3 (Both) — both Q160 and Q161 asked; fall through. }


PROC Q161_WHY_BRANDED_O01
preproc
    { If Q159 = Generic only (2), skip the Q161 branded-reasons select_all
      and route directly to Q162 (REFERRED). }
    if Q159_BRAND_GEN_BOUGHT = 2 then
        skip to Q162_REFERRED;
    endif;


{ ===================================================================== }
{  Section L — Referrals (Q162-Q178)                                    }
{ ===================================================================== }

PROC Q162_REFERRED
postproc
    { Template 4.11 — non-referral path skips Q163-Q171 and jumps to
      Q172 (PCP referral block, asked of everyone). }
    if Q162_REFERRED = 2 then   { 2 = No }
        skip to Q172_PCP_REFERRAL;
    endif;


PROC Q169_VISITED
postproc
    { Template 4.12 — three-way branch on visit-status of referral.
      Q170_FOLLOWUP = follow-up flag (asked when visited). Q171_WHY_NOT
      is a multi-response select_all (Q171_WHY_NOT_O01.. is the routing
      target). }
    if Q169_VISITED in 2, 3 then
        { Not visiting / planning later — skip Q170 (followup), ask Q171
          (why-not select_all), then proceed to Q172. }
        skip to Q171_WHY_NOT_O01;
    endif;
    { Q169 = 1 (Yes) — fall through to Q170 (followup).
      Q170.postproc handles the jump to Q172 to skip Q171. }


PROC Q170_FOLLOWUP
postproc
    { After Q170 (follow-up flag), skip Q171 (why-not) and proceed
      to Q172 since the patient DID visit the referral. }
    if Q169_VISITED = 1 then
        skip to Q172_PCP_REFERRAL;
    endif;


PROC Q172_PCP_REFERRAL
postproc
    { Non-PCP-referral path skips Q173-Q176 (PCP referral details) and
      jumps to Q177 (why-hospital select_all — first decomposed slot). }
    if Q172_PCP_REFERRAL = 2 then   { 2 = No }
        skip to Q177_WHY_HOSPITAL_O01;
    endif;


PROC Q178_SAT_REFERRAL
postproc
    { Final terminus — close the case as a complete interview. }
    CloseCaseAsComplete();


{ ===================================================================== }
{  GPS + photo capture handlers — wire shared helpers                    }
{ ===================================================================== }

PROC FACILITY_CAPTURE_GPS
onfocus
    { Trigger field — when the operator taps "Capture GPS now" the
      onfocus calls ReadGPSReading() with the F-series defaults:
      maxTimeSec=60, desiredAccuracyM=20. Results are written to
      FACILITY_GPS_LATITUDE, ..., FACILITY_GPS_READTIME. See
      shared/Capture-Helpers.apc for the helper definition. }
    ReadGPSReading(60, 20);


PROC P_HOME_CAPTURE_GPS
onfocus
    { Same as facility GPS but for the patient's home address. Asked at
      the closing of the interview if the patient agrees to share home
      coordinates (for F4 home-visit logistics). }
    ReadGPSReading(60, 20);
'''


def main():
    (HERE / "PatientSurvey.ent.apc").write_text(APC, encoding="utf-8")
    print(f"wrote PatientSurvey.ent.apc ({len(APC)} chars; commit 4/6 — sections D-L + validations)")


if __name__ == "__main__":
    main()
